### PR TITLE
[plugin.program.autocompletion] v2.0.2

### PR DESCRIPTION
**Pull request by Hawkedon**
### Description

Fixed the crash on some platforms

Give the busy dialog a little more time to finish, otherwise Kodi will crash on some platforms (Xbox, for example)

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by enen92** [comment]
@sualfred are you fine with this? It seems upstream of this addon is still pointing to phil's version

**Review by basrieter — DISMISSED** [review]

**Review by basrieter — CHANGES_REQUESTED** [review]
Original Dev should approve and was this PR done on the original repo? Which seems like the right course of action.

**Comment by Goldenfreddy0703** [comment]
> Original Dev should approve and was this PR done on the original repo? Which seems like the right course of action.

Hey, im not trying to be mean and im sorry for asking but is the original dev phill still alive or still active?
image
image
I mean yeah he made 297 contributions and comment on a few in the past but he never reviewed these 4 pull request that have been there sense 2018-2019. 

Is it possible to still get in contact with him by anychance in order to get approval from him???

**Comment by enen92** [comment]
This was updated by another dev already. Closing.
Thanks for the contribution

**Pull request closed without merging**
