### PR TITLE
[plugin.video.syfy] 1.0.8

### PR DESCRIPTION
**Pull request by learningit**
Hopefully this will create just one pull request for the current commit of the syfy addon

### CODE REVIEW

**Comment by learningit** [comment]
Actually how the hell do I create a separate pull request for each addon? Everytime I do a new commit it adds to the open pull request.

**Comment by MartijnKaijser** [comment]
you need to create a new branch each time from the "gotham" one

**Comment by learningit** [comment]
Is there a naming convention for the new branches?

**Comment by MartijnKaijser** [comment]
nope, branch is what ever you call and is just a temporary name for it. It has no affect on the outcome

**Comment by learningit** [comment]
Another really stupid question was it really necessary to clone the entire repo-plugins? I would think I only need the addons that I'm dealing with.

**Comment by MartijnKaijser** [comment]
Yes it's only a one time clone for the entire repo. After you can just pull the latest changes and a new PR.

**Comment by learningit** [comment]
Ok. Thanks for doing the commit, I was stuck because I didn't create a separate branch name for that one. I think I've got it now and can finish editting Bromix's scripts to fit my setup. Thanks!

**Pull request merged**
