### PR TITLE
[plugin.audio.eradio.gr] 1.0.0

### PR DESCRIPTION
**Pull request by lambda81**
radio addon for
http://www.e-radio.gr

### CODE REVIEW

**Comment by phil65** [comment]
that's much easier to review now. :)
Looks good to me.

**Comment by lambda81** [comment]
phil can i ask you something here?
it's not about this addon, but it's better asking here before making a pull request
it's about service.subtitles.subtitles.gr
https://github.com/xbmc/repo-scripts/pull/186
it's not a new subtitle service
i have it coded about 2 years ago
i want to send an updated version
can i use the module i created on it?
what i mean
the first versions of the service had been added to gotham
the module is new, so it's jarvis or higher
what are my options?
can i send version 1.2.0 to jarvis?
if i send it to gotham i won't be able to use the module

**Comment by phil65** [comment]
yeah you can send the updated version to jarvis branch and use the module then. Older kodi versions will still get the previous subtitle addon then.

**Comment by lambda81** [comment]
thanks for your reply, i will send it to jarvis

**Pull request merged**
