### PR TITLE
[plugin.video.svtplay] 4.0.40

### PR DESCRIPTION
**Pull request by linqcan**
### Description
Fix broken episode listing.
Updated visuals.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
that icon.png looks quite horrible imo

**Comment by linqcan** [comment]
Yep, can not find their new logotype in high resolution. They use small UI
elements nowadays...

You'd say I am better off not updating?

**Comment by MartijnKaijser** [comment]
Personally i would keep the old icon :)
Especially since we also allow 512x512 icons nowdays for bigger screens.

**Comment by linqcan** [comment]
Yeah, if it is upscaled to 512x512 then it will look really bad. Reverting the icon and will come back with a new PR.

**Pull request closed without merging**
