### PR TITLE
[plugin.video.youtube] 5.3.3

### PR DESCRIPTION
**Pull request by jdf76**
Updating Youtube Plugin from 5.2.1 to 5.3.3

### CODE REVIEW

**Comment by Razzeee** [comment]
Your not updating the addon, your trying to add a new one in the folder `plugin.video.youtube-5.3.3`

**Comment by jdf76** [comment]
Oh I thought I was supposed to create a new folder. I move it to an existing folder, would you want me to create a new PR?

Jeff

**Comment by Razzeee** [comment]
Will you can just edit your previous commit with the changes and force push this branch. If you can manage that otherwise a new pr would be good.

**Comment by jdf76** [comment]
Lets just close this, were about to make some minor bug fixes and language fixes as well.

**Pull request closed without merging**
