### PR TITLE
Updating Youtube Plugin from 5.1.17 to 5.2.1

### PR DESCRIPTION
**Pull request by jdf76**
This will update the Broken 5.1.17 to the working 5.2.1 (2016-05-12).
Changed Author from Bromix to jdf76 and h0d3nt3uf3l.
[add] Additional "Recommend for You" section (thanks to anxdpanic)
[upd] APi-Changer - First login delete old Credentials - New Login Required! Sorry :)
Workaround for the Quota Exceed-Error.
[add] API-Changer for a Pool of 6 API-Keys
[add] Auto-Reauthenticate with Pool-Key on "Quota Exceed" error
[add] "Use own API"-Button
[hint] The Message "Invalid Credentials" after Update could be fixed with deleting the Userdata-Settings.xml
[add] add Recommendations to main listing when logged in [anxdpanic]
[add] Greek Translation from twilight0
[upd] Fixed italian translation from DjDiabolik
[upd] Ignore if '.apps.googleusercontent.com' entered in API Id string in add-on settings
[add] API Key in add-on settings
[upd] All string.po for new API Key functionality. New entries in language string.po files not translated from English.
[fix] All Key changed with YouTube TV
[fix] Live streams itag 91 patch
[add] Kodi 17 Krypton support. Patch by Uukrul
[fix] Final fix for APIs

### CODE REVIEW

**Comment by Razzeee** [comment]
Two Problems:

1) Your PR can't be against master, it has to target the branchof the minimal Kodi version your supporting.
2) It needs to be one commit, not more :)

**Comment by jdf76** [comment]
Yes, i noticed that after i submitted.

I’m going to make sure i do this right so

if I submit a PR

I create a branch in the Jarvis branch to get all the branches “Gotham and up” like it says in http://kodi.wiki/view/Submitting_Add-ons <http://kodi.wiki/view/Submitting_Add-ons> or do i put it in helix and it gets everything up to jarvis.

do i use the name plugin.video.youtube-5.2.1 for the branch or just plugin.video.youtube. and then in the commit i put [plugin.video.youtube] 5.2.1

Thanks for the help you guys are giving me with this.

Jeff

**Comment by Razzeee** [comment]
The branch name itself doesn't matter. 
If you choose Jarvis it will be Jarvis and up, unless you commit something to krypton in that case the change to Jarvis will be Jarvis only. 
Please check the readme of the branches for info if that branch accepts PRs. 
The commit message as your named it is correct.

**Comment by jdf76** [comment]
ok i resubmitted #479 can you verify with me that it’s correct. 

Again Thank you for your help!!

Jeff

**Pull request closed without merging**
