### PR TITLE
[plugin.video.southpark_unofficial] v0.5.8

### PR DESCRIPTION
**Pull request by wargio**
### Description
Upgrade to 0.5.8 as asked by many users.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by wargio** [comment]
This does not make sense. if users cannot use Kodi 19 plugins, why i can't release the same version for a lower repo?

**Comment by pkscout** [comment]
Because Matrix for the first time requires Python3, add-on versions in the Matrix repo must be higher than any other repo to ensure the add-on is upgraded when someone upgrades to Matrix.

If the two versions of your add-on share the same code, then just submit the PRs for both at the same time (one PR for each version). Once we review and merge the Matrix one, we can re-run the Travis test and then approve and merge the other one.

If the two versions of your add-on don't share the same code base, I'd suggest submitting a PR for the Matrix version to bump it to a much higher version number (in your case either to 0.6.0 or even 1.0.0). Then you can keep submitting updates to the older branch using, for instance, 0.5.xx version numbers without having to submit just a version bump for the Matrix version. That's what I did for one of my add-ons where the code ended up being different.

**Comment by wargio** [comment]
they are exactly the same. the only issue is that this version for matrix was released a few months ago, but i never bothered to update the current one on helix, because i thought the kodi 17 and 18 would start use py3, but they never did.

**Comment by pkscout** [comment]
The convention then is to append the Matrix version with +matrix.1. If you submit a PR to the Matrix branch with nothing but a version change to 0.5.8+matrix.1, then we can approve/merge that, wait a couple hours for the repo to sync, then review this one.

**Comment by wargio** [comment]
@pkscout done as you have proposed.

**Review by pkscout — APPROVED** [review]

**Pull request merged**
