### PR TITLE
[plugin.video.snnow] 1.0.5

### PR DESCRIPTION
**Pull request by micahg**

### CODE REVIEW

**Comment by phil65** [comment]
Damn, commit message is wrong. :/

**Comment by micahg** [comment]
So I can fix it next time, what was wrong?

**Comment by learningit** [comment]
should be same format as the PR - [addonname] x.y.z

**Comment by micahg** [comment]
OK, wont flub it next time. Sorry.

On Thu, Jun 9, 2016 at 1:00 PM, learningit <notifications@github.com> wrote:

> should be same format as the PR - [addonname] x.y.z
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/492#issuecomment-224959361>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABK4SDHtRxrnymYkDSN-qDC1bckWIFjrks5qKEaQgaJpZM4IoFzH>
> .
>



-- 
"The mark of an immature man is that he wants to die nobly for a cause,
while the mark of the mature man is that he wants to live humbly for
one."   --W. Stekel

**Pull request merged**
