### PR TITLE
[plugin.video.nhlgcl@jarvis] 2021.3.23

### PR DESCRIPTION
**Pull request by eracknaphobia**
### Add-on details:

- **General**
  - Add-on name: NHL TV™
  - Add-on ID: plugin.video.nhlgcl
  - Version number: 2021.3.23
  - Kodi/repository version: jarvis

- **Code location**
  - URL: https://github.com/eracknaphobia/plugin.video.nhlgcl
  
With NHL.TV you can access revolutionary 60fps (frames per second) video through Kodi
        

### Description of changes:

            - Fix for past game not showing in Kodi 19 (thanks mrawji)
            - Squashed some bugs and other minor fixes
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by eracknaphobia** [comment]
Not sure why this is getting an older tag and version number. The latest in my github is 2021.3.23, is there something I need to look into with the kodi addon submitter?

**Comment by enen92** [comment]
I think you need to delete your repo-plugins fork, something has changed when we started to use GitHub actions instead of Travis (maybe the repo configuration)

**Comment by eracknaphobia** [comment]
Should I delete this PR and start a new one after I delete my fork? Thanks for the guidance @enen92.

**Comment by enen92** [comment]
Yeah, close this one, delete your fork and tag a new release. The submitter script should handle the fork creation itself

**Pull request closed without merging**
