### PR TITLE
Jarvis: plugin.video.magaritv

### PR DESCRIPTION
**Pull request by ogiliberti**
Hallo Kodi mantainer,

I would like to push my Kodi Addon to the official repository
to allow people to watch MagariTV.

****************************************************************************************
* addon - plugin.video.magaritv
* version - 1.0.0
* url - https://github.com/ogiliberti/magaritv/blob/master/plugin.video.magaritv-1.0.0.zip
* revision - e7dd764  (latest commit to master)
* branch - master
* xbmc version - jarvis

****************************************************************************************
Thanks for your kind attention.
Best Regards,

Orazio Giliberti 

[https://github.com/ogiliberti/magaritv/blob/master/plugin.video.magaritv-1.0.0.zip
](url)

### CODE REVIEW

**Comment by phil65** [comment]
Something went wrong with your pull request, there should only be one commit.

**Comment by MartijnKaijser** [comment]
You made a request against wrong branch

**Comment by ogiliberti** [comment]
Dear All,

May I know what is the correct branch, the correct repository and 
everything I am expected to comply with ?

Thanks for your kind attention.

Best Regards,

Orazio Giliberti


Il 30/04/2016 15:51, Martijn Kaijser ha scritto:
> You made a request against wrong branch
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/449#issuecomment-215964363>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Comment by ogiliberti** [comment]
Dear All,

I followed this procedure

﻿http://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging

and I get this result:
..............................................................
git clone@github.com:ogiliberti/repo-plugins.git
git: 'clone@github.com:ogiliberti/repo-plugins.git' is not a git command.
See 'git --help'.
[root@titano kodi_delivery]# git clone git@github.com:
ogiliberti/repo-plugins.git
Cloning into 'repo-plugins'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129'
to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
-------------------------------------------------------------

so I inserted a PR #450 from web interface to repo-plugin.



Thanks for your attention

Best Regards,

Orazio Giliberti


2016-04-30 15:56 GMT+02:00 Orazio Giliberti <ogiliberti@gmail.com>:

>
>
> Dear All,
>
> May I know what is the correct branch, the correct repository and
> everything I am expected to comply with ?
>
> Thanks for your kind attention.
>
> Best Regards,
>
> Orazio Giliberti
>
>
> Il 30/04/2016 15:51, Martijn Kaijser ha scritto:
>
>> You made a request against wrong branch
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xbmc/repo-plugins/pull/449#issuecomment-215964363>
>>
>>
> --
> ______________________________________________
>
> Ing. Orazio Giliberti
>
> mobile:  +393389847233
> email:   ogiliberti@gmail.com
> pec/cem: ogiliberti@pec.ording.roma.it
>



-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Pull request closed without merging**
