### PR TITLE
[plugin.video.filmsforaction] v1.0.10

### PR DESCRIPTION
**Pull request by jamontes**
Hi,

This is a new maintenance update for plugin.video.filmsforaction over Helix branch.

Changelog: 1.0.10 (2018.09.05)
- Removed add-on dependencies.
- Deprecated Gotham release due to missing add-on dependency.
- Modified to allow upgrades from Helix release onwards.

Please, bear in mind that i have to made the PR over Helix branch due to Youtube add-on missing dependency on Gotham. I've updated the add-on following the Travis-CI reports on my last PR attempt over Gotham branch in order to made it compliant with Helix. 

For more info, please see the last PR over Gotham: [#2026](https://github.com/xbmc/repo-plugins/pull/2026)

Many thanks in advance for your help and best regards,

jamontes.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by jamontes** [comment]
Hi Rechi,

As you can see on my submission, the changes submitted corresponds to just a single commit into my personal forked repo: [[plugin.video.filmsforaction] v1.0.10 ](https://github.com/jamontes/repo-plugins/commit/5b27f4380064ce125f0227d0fb58a8fd8291dcf9), and the maintenance add-on fixes corresponds as well to a single commit in my local repository: [commit f2415f7](https://github.com/jamontes/plugin.video.filmsforaction/commit/f2415f7ef2f164e9a39a17986048467c7058b4cc), although i made additional changes to my initial commit in order to adapt the add-on for Helix, from my add-on local copy to my personal add-on repo, following this link: [HOW-TO:Update a pull request to an official addon repository on GitHub](https://kodi.wiki/view/HOW-TO:Update_a_pull_request_to_an_official_addon_repository_on_GitHub).

However, and i don't know why, it appears into the PR as if I made several consecutive commits before requesting the current PR, although the commits "[plugin.audio.rne] 1.0.9" and  "[plugin.audio.rne] 1.0.10" belong to older already merged PRs into the official repo over the Helix branch. That astonishes me and honestly, i don't know how to get the current PR to the official repo with just the commit of the fixed add-on released (i.e. the one which entitles the PR, "[plugin.video.filmsforaction] v1.0.10" in this case). I don't use any git GUI tool, except the command line. Whenever i synchronize the cloned repo-plugins from the official repo (aka the upstream) by using a fetch and right afterwords a merge over the branch i want to update, the git command line always ask me to edit a message commit (the one you can see above). But when i send the push to my personal repo-plugins fork it only appears the single commit with the updated add-on, alike the PR i requested right afterwords over the official repo. Maybe in the middle i'm skipping some git command to prevent the older commits to appear into the PR.

So please, i very appreciate your help if you tell me how can i get the PR with just the wanted commit. 

Many thanks in advance for your help and best regards,

jamontes.

**Comment by Rechi** [comment]
> [...] Whenever i synchronize the cloned repo-plugins from the official repo (aka the upstream) by using a fetch and right afterwords a merge over the branch i want to update [...]

If `Squash and merge` (https://blog.github.com/2016-04-01-squash-your-commits/) or `Rebase and merge` (https://blog.github.com/2016-09-26-rebase-and-merge-pull-requests/) is used for your PRs a later local merge like you did will create an additional merge commit. This happens as your original commit isn't in the upstream branch, but only a nearly identical commit.


To fix your pull request execute the following commands (origin is your repo, upstream is the xbmc repo)

```
git fetch upstream
# just to make sure you have checked out the correct branch (this PR branch)
git checkout helix
git rebase upstream helix 
git push -f origin helix
```

**Comment by jamontes** [comment]
Hi Rechi,

I've followed your indications in order to fix the PR, but after made the rebase i've got stuck with the following error:
git rebase upstream helix
fatal: Needed a single revision
invalid upstream upstream

I've double checked the current branch, the remotes and the status, but everything seems to be correct. It's the first time i did a rebase or squash before at any of my PRs until now that i tried to fix this one. This is the state before perform the fetch and rebase commands (I only show the affected repos):
git status
On branch helix
Your branch is up-to-date with 'origin/helix'.

git remote -v
filmsforaction  git@github.com:jamontes/plugin.video.filmsforaction.git (fetch)
filmsforaction  git@github.com:jamontes/plugin.video.filmsforaction.git (push)
origin  git@github.com:jamontes/repo-plugins.git (fetch)
origin  git@github.com:jamontes/repo-plugins.git (push)
rne     git@github.com:jamontes/plugin.audio.rne.git (fetch)
rne     git@github.com:jamontes/plugin.audio.rne.git (push)
upstream        https://github.com/xbmc/repo-plugins.git (fetch)
upstream        https://github.com/xbmc/repo-plugins.git (push)

As I'm not sure to fix my local copy neither my forked repo at this point, i'm going to start from scratch (i.e. to fork and clone again the repo-plugin) just to get a clean copy to work with from now on in the future.

I'll close this PR and be back in a while with a new one hopefully right.

Many thanks for all your help and patience, and best regards,

jamontes.

**Comment by Rechi** [comment]
Sorry, correct is `git rebase upstream/helix`.

**Comment by jamontes** [comment]
Hi Rechi,

Thanks for the correction :-) So I guess i shall do the rebase of the upstream branch before the submerge-tree with my add-on repo, and then, perform the commit with the add-on release label and push over the origin, as usual, right?

If that's the case, then i think i've got the whole process for next time. But now that i've broken my local fork, I'll start with a fresh fork and PR, just to make it sure that everything is OK for the coming PRs.

Thanks a lot for your help and support.

Best regards,

jamontes.

**Comment by jamontes** [comment]
Hi Rechi,

I've never thought of make the branch attached to the upstream, but to the origin. That changes everything.

I guess your method should be valid as well if you maintain several add-ons on the same upstream branch, right?

I'll try as you suggest for next time.

Thanks a lot for your help and time.

Best regards,

jamontes.

**Pull request closed without merging**
