### PR TITLE
[plugin.video.fsgo] 1.1.7

### PR DESCRIPTION
**Pull request by peak3d**
### Description

Parse arguments in default.py to allow reusepython mode

### CODE REVIEW

**Comment by enen92** [comment]
@peak3d does this have the author (@emilsvennesson) approval? If so feel free to merge

**Comment by Lunatixz** [comment]
LGTM

**Comment by peak3d** [comment]
I'm in contact with the author currently discussing the options.
Please don't spend any time on it, most probably I'll change something in kodi to get rid of this issue

**Comment by enen92** [comment]
No problem, just ping (if you don't have permissions to merge)

**Comment by peak3d** [comment]
Fixed in kodi python handling

**Pull request closed without merging**
