### PR TITLE
[plugin.video.dumpert] 1.1.1

### PR DESCRIPTION
**Pull request by skipmodea1**

### CODE REVIEW

**Comment by learningit** [comment]
Sorry, can you select the branch that you want to merge this into? I don't think you want to use the "master" branch

**Comment by skipmodea1** [comment]
How do i do that? I tried following the instructions in CONTRIBUTING.md, but aparantly messed up somewhere...

**Comment by Razzeee** [comment]
Unfortunatly github doesn't allow to change that after the PR creation. So either someone with the needed rights here can do if for you (if you let us know which version) or you create a new PR and make sure to target the correct branch.

**Comment by learningit** [comment]
Close this pull request. Create a new pull request and specify which branch to do the compare against - if you do the PR on the web it's a dropdown box to select the branch when you create the pull request.

**Comment by MartijnKaijser** [comment]
@skipmodea1 you first need to switch to jarvis branch, then create a branch from that and afterwards do your changes. You now started from master branch

**Comment by learningit** [comment]
Yes - sorry Martijn's comment is much clearer than mine.

**Pull request closed without merging**
