### PR TITLE
plugin.audio.calmradio - 0.1.4

### PR DESCRIPTION
**Pull request by nire0510**

### CODE REVIEW

**Comment by phil65** [comment]
Please change commit message to "plugin.audio.calmradio - 0.1.4"

**Comment by phil65** [comment]
are those backgrounds really needed? my preference would be to remove them.

**Comment by nire0510** [comment]
@phil65 the background images are quite small size-wise and improve the look and feel. I will examine a different layout for the plugin on the next version.
Thanks!

**Comment by phil65** [comment]
Please at least reduce the image amount to a reasonable level. >200 background images is too much.
Also, commit message != PR title  ;)

**Comment by nire0510** [comment]
Hi @phil65 , thank you for your comments! I believe that the commit message has changed now. As for the background images, 98% of them are less than 40kb. There is a video file, however, which is 10mb and is not in use. Can you remove it, please? (I don't want to make any changes to the branch and to violate your guidelines).
Can we please publish it as is and to think about a way to reduce the images w/o affecting the L&F on the next version?
Thanks!

**Comment by learningit** [comment]
This PR is on the wrong branch. You definitely don't want to commit this to the master branch.

**Comment by learningit** [comment]
Seeing that this is supposed to an "official" add-on, I'm surprised that you aren't hosting the images on the "official" website, rather than putting them in the add-on. I would agree with @phil65 on his comments about this.

**Comment by nire0510** [comment]
@learningit i followed your comment and created a new PR in Jarvis branch. Closing current PR.

**Pull request closed without merging**
