### PR TITLE
[plugin.video.RTK] 1.0

### PR DESCRIPTION
**Pull request by hkastrati7**
### Description
This is the official channel of Radio Television of Kosovo. You can now watch diversity of our program here.It contains four TV channels and two radio stations. 
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuesly monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by phil65** [comment]
please unzip the add-on. ;)

**Comment by MartijnKaijser** [comment]
@hkastrati7 please also check https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md
as that explains something about branching from the "jarvis" branch and pushing it to github.

Thank you for your submitting an add-on. We'll help you get through this as it can be quite difficult.

**Comment by MartijnKaijser** [comment]
Haven't looked at code yet but the Plugin ID should be lowercase

**Comment by hkastrati7** [comment]
@MartijnKaijser it is obligative for the Plugin ID to be lowercase, or just an advice ?

**Comment by ronie** [comment]
looks like a copy of some piracy addon.
even has obfuscated code.

**Comment by learningit** [comment]
I'm sorry but we can't put this add-on in the kodi.org repo. There are urls to piracy sites, modules from banned add-ons and just too many issues with the code to enumerate, starting with the obfuscated code and ending with print statements everywhere. I suggest that you go back and read the submission rules really carefully, make your corrections (assuming you still want to try to submit) and re-submit. I am closing this PR for the above reasons.

**Pull request closed without merging**
