### PR TITLE
[plugin.video.mlbtv@matrix] 2022.4.19+matrix.1

### PR DESCRIPTION
**Pull request by eracknaphobia**
### Add-on details:

- **General**
  - Add-on name: MLB.TV®
  - Add-on ID: plugin.video.mlbtv
  - Version number: 2022.4.19+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/eracknaphobia/plugin.video.mlbtv
  
Watch every out-of-market regular season game in the office or on the go. The #1 LIVE
            Streaming Sports Service
        

### Description of changes:

            - featured videos, including Big Inning
            - audio-only streams
            - unique game icons
            - probable pitchers
            - doubleheader/TBD start times
            - restored "play all recaps" behavior when selecting date
            - moved more text to language localization file
            - additional AddonIsEnabled detection for inputstream adaptive
            - code cleanup
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by eracknaphobia** [comment]
`ERROR: ./plugin.video.mlbtv/resources/lib/mlb.py is marked as stand-alone executable` 
I've never seen this error before so I'm not sure how to fix it?

**Comment by enen92** [comment]
@eracknaphobia just remove the executable permission on the file: 
`git update-index --chmod=-x myfile.py`
commit and push

**Comment by eracknaphobia** [comment]
@enen92 Ok, thanks for the info! I tried to resubmit but hit the same error everything looks correct from what I can tell. I'll keep digging.

image

**Comment by enen92** [comment]
In this submissing mlb.py is marked as executable:
image

**Comment by eracknaphobia** [comment]
I forgot to commit the change before submitting... need more coffee

**Comment by eracknaphobia** [comment]
On another note my changes aren't being sent to the matrix pr, just the kyrpton. Should i just close them both and start over?

**Comment by enen92** [comment]
I am not sure what you're using to submit. If using the kodi-addon-submitter action, removing the (local and remote tag) and tagging it again should force push to both PRs.
If you find it easier to just close and resubmit please do

**Pull request closed without merging**
