### PR TITLE
[plugin.video.nfl.gamepass] 0.11.1

### PR DESCRIPTION
**Pull request by aqw**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

Sorry for the quick version bump. Game Pass is going through their yearly ritual of breaking their API at a whim. And this year is worse than usual as the NFL split their service between two competing hosting providers.

We're working to restore support for the older service, and hopefully we only need one more release in the next 2-3 weeks. Then everything will calm down again...

Let me know if you have any questions or concerns.

---Alex

### CODE REVIEW

**Comment by enen92** [comment]
Try to add the description on the top (before the checklist) next time. Easy to miss if you add it on the bottom.

**Comment by aqw** [comment]
@enen92 Makes sense; I wasn't thinking. A habit from bottom-posting emails. ;-)

Thanks for pointing it out. :-)

---Alex

**Comment by aqw** [comment]
@enen92 Oh, and thanks for the super-quick merge!

---Alex

**Comment by enen92** [comment]
Thanks for the quick update. Don't worry with the amount of updates we are trying to speed things up on the repo :)
Cheers

**Comment by MartijnKaijser** [comment]
@aqw please check this for next update
PROBLEM: Invalid xml found. /home/travis/build/xbmc/repo-plugins/plugin.video.nfl.gamepass/resources/skins/Default/colors/defaults.xml

**Pull request merged**
