### PR TITLE
[plugin.video.rivedila7] 3.1.1

### PR DESCRIPTION
**Pull request by luivit**
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- New version, compatible from kodi 17

### CODE REVIEW

**Comment by enen92** [comment]
@luivit your add-on is already on the Jarvis branch. Any reason for submitting it to krypton?

**Comment by Testato** [comment]
The new 3.x version need the inputstream adaptive
<import addon="inputstream.adaptive"/>

It is not present on kodi16

**Comment by enen92** [comment]
Ok, we don't accept new addons in the krypton branch but I guess this can be considered an update to an already existing addon. Please mark the jarvis version as broken if it doesn't work anymore. Also keep in mind that from Leia and upper kodi versions, addons have to be compatible with python3

**Comment by Rechi** [comment]
@luivit this add-on isn't Python 3 compatible. Future updates have to be compatible with Python 3.
Have a look at https://kodi.tv/article/attention-addon-developers-migration-python-3 for more information.

**Pull request merged**
