### PR TITLE
[plugin.video.aktualnetv] 2.1.1

### PR DESCRIPTION
**Pull request by petrkutalek**
### Description

just update, adapted to webpage videoplayer update 
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by petrkutalek** [comment]
Hi guys, I do not understand what is wrong with this Travis CI check. It is just a minor fix for update of the source website. Fully working. No big changes. Thanks a lot for your assistance.

**Comment by petrkutalek** [comment]
OK, that means that even it is an update to Jarvis I need to change a language structure from `/resources/language/Czech/strings.po` I use currently to a new structure `/language/resource.language.cs_cz/strings.po`. Am I right? Is it an issue for accepting this pull-request?

**Comment by Rechi** [comment]
Yes you have to change it. The new directory layout should be used for everything targeting isengard or higher. It seems like it slipped through in the initial submission as there wasn't an automated check.

Here are the required commands to adjust your add-on.
```
git mv plugin.video.aktualnetv/resources/language/Czech/ plugin.video.aktualnetv/resources/language/resource.language.cs_cz/
git mv plugin.video.aktualnetv/resources/language/English/ plugin.video.aktualnetv/resources/language/resource.language.gb_en/
git mv plugin.video.aktualnetv/resources/language/Hebrew/ plugin.video.aktualnetv/resources/language/resource.language.he_il/
git mv plugin.video.aktualnetv/resources/language/Slovak/ plugin.video.aktualnetv/resources/language/resource.language.sk_SK/
```

**Comment by petrkutalek** [comment]
@Rechi Thank you for your assistance, I just created new pull request, tests passed OK.

**Pull request closed without merging**
