### PR TITLE
[plugin.video.orftvthek] 0.8.4

### PR DESCRIPTION
**Pull request by s0faking**
### Description
reverted changes from 0.8.3 which caused kodi to crash when using the playall listitem
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
@s0faking if it still crashes this needs a different fix, marking an item as folder which doesn't add items or marking it playable when it doesn't point to a media url is wrong.

**Comment by s0faking** [comment]
@Rechi i agree but until we have a solution i want to prevent those kodi crashes which we have with the new fix. i suggest we work on that on the devel branch and release it when we have a stable version

**Comment by Rechi** [comment]
If only v18 crashes, please let it crash.

**Comment by s0faking** [comment]
17.6 is crashing. if it would have been v18 i certainly wouldnt have commited this temporary fix. i havent tested this with other version but since the current stable release is affected, i cant leave this as it is now until there is a working solution.  is it working with your kodi version? which one are you using?

**Comment by Rechi** [comment]
newer version (0.8.5) submitted

**Pull request closed without merging**
