### PR TITLE
[plugin.video.reddit_viewer] 2.7.6

### PR DESCRIPTION
**Pull request by gedisony**

### CODE REVIEW

**Comment by learningit** [comment]
I'm pretty sure I requested that you change the strings.xml files to strings.po files in your next (this) update when I committed 2.7.5.

**Comment by gedisony** [comment]
yes, no more strings.xml, just strings.po

**Comment by learningit** [comment]
I didn't look at the default.py very carefully last PR, there's an awful lot of behaviour in there that would make this more of a script than a plugin - you actually have work arounds to accomplish some things that shouldn't be in a plugin.  Is there any particular reason that you made this a plugin?

**Comment by gedisony** [comment]
Finnish and german files were in strings.xml. I removed them. 
This is my first addon, The original reddit addon for kodi have support for media from 4 or 5 sites. I decided to extend it. Do you want me to make this addon into script.something.something?

**Comment by gedisony** [comment]
I can't get the plugin the work as a script. It is a plugin because the original was a plugin and I cannot find a workaround to make the plugin work as a script.

**Comment by learningit** [comment]
I need to let someone who's more familiar with add-ons that combine/shift between a custom gui in a do.modal loop combined with plugin event management review this.  Some of the processing looks strange to me, but maybe it's ok.

**Pull request closed without merging**
