### PR TITLE
[plugin.video.composite_for_plex@nexus] 2.0.0

### PR DESCRIPTION
**Pull request by anxdpanic**
### Add-on details:

- **General**
  - Add-on name: Composite
  - Add-on ID: plugin.video.composite_for_plex
  - Version number: 2.0.0
  - Kodi/repository version: nexus

- **Code location**
  - URL: https://github.com/anxdpanic/plugin.video.composite_for_plex
  
Browse and play video, music and photo media files managed by Plex Media Server.[CR][CR]Fork of PleXBMC by Hippojay

### Description of changes:

[add] Kodi Nexus v20 support
[chg] changed settings format to the latest format
[rem] removed support for all version of Kodi pre-Nexus v20
[rem] removed Python 2 support
[rem] removed dependency on kodi-six
[rem] removed dependency on six
[lang] update translations from Weblate
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by anxdpanic** [comment]
@jurialmunkey This will be waiting on infotagger v0.0.5+ to be submitted, when you have a chance.

**Comment by anxdpanic** [comment]
Actual changes for this version: https://github.com/anxdpanic/plugin.video.composite_for_plex/compare/ff0b2cd76b0ba81630ae11150518c9e3be3d2f79..5594a7861b17843ed94df400007dff80df04b7d8

**Comment by jurialmunkey** [comment]
> @jurialmunkey This will be waiting on infotagger v0.0.5+ to be submitted, when you have a chance.

No worries! 
PR for infotagger submitted here: https://github.com/xbmc/repo-scripts/pull/2412

**Review by enen92 — APPROVED** [review]
Wow, this was a cleanup :)

**Pull request merged**
