### PR TITLE
[plugin.video.magaritv] 1.0.0

### PR DESCRIPTION
**Pull request by ogiliberti**
Dear All,

I would like to push my Kodi Addon to the official repository
to allow people to watch MagariTV

    addon - plugin.video.magaritv
    version - 1.0.0
    revision - ae38b7c
    url - https://github.com/ogiliberti/plugin.video.magaritv
    xbmc version - jarvis

I hope this time my PR is correct.
Apologise in advance for any inconvenience.
Thanks for your kind attention.

Best Regards,

Orazio Giliberti

### CODE REVIEW

**Comment by ogiliberti** [comment]
I closed 451 and reopened another one.
Now ?
Is it corrrect ?

**Comment by ogiliberti** [comment]
The system from web interface automatically insert "Added files via upload".
If I send files by email is wrong....
If I send files by github is wrong...
It is an Open Foundation or what ?

Best Regards

**Comment by Razzeee** [comment]
@ogiliberti 
when you upload, just change this text box:
image

**Comment by ogiliberti** [comment]
Ranzee,

I didn't find the area you describe.

Anyway I send you a .pdf file with all printscreens of the step I have done.

Best Regards,

Orazio

Il 05/05/2016 19:30, Razzeee ha scritto:
> @ogiliberti <https://github.com/ogiliberti>
> when you upload, just change this text box:
> image
> <https://cloud.githubusercontent.com/assets/5943908/15051219/c6409f8a-12f7-11e6-8a38-5b7392fd91bf.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/459#issuecomment-217218427>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Comment by ogiliberti** [comment]
To whom it may concern,

I send a .pdf file with the printscreen of all steps I follow to submit 
a plugin that always is considered uncorrect because the commit message 
is Added files via upload

I didn't find the text area kindly suggested by Razzee.

Any help will be warmly welcomed

Best Regards,

Orazio Giliberti



Il 05/05/2016 19:30, Razzeee ha scritto:
> @ogiliberti <https://github.com/ogiliberti>
> when you upload, just change this text box:
> image
> <https://cloud.githubusercontent.com/assets/5943908/15051219/c6409f8a-12f7-11e6-8a38-5b7392fd91bf.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/459#issuecomment-217218427>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Pull request closed without merging**
