### PR TITLE
[plugin.video.myvevo] 3.0.5

### PR DESCRIPTION
**Pull request by learningit**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by phil65** [comment]
should go to jarvis branch I think?

**Comment by learningit** [comment]
Not sure. It is not a new add-on. I thought it was in Isengard, I guess
it's in Helix. Let me know what you want to do and I'll do it.

**Comment by phil65** [comment]
2.24.0 is Jarvis though?
I thaught we only add new add-ons to jarvis and newer. Not sure if add-ons which are already existing in "lower" repos are an exception for that rule.

**Comment by learningit** [comment]
I could change to Jarvis, but that would leave a hole for Isengard. I can't
update the Helix one because I'm using setArt() and subtitle stuff that
only came in Isengard.  I can't remember what happened here, if it was just
missed when a bunch of add-ons were automatically added to Isengard from
the Helix branch or if there was a reason I didn't update for Isengard.

On Jan 2, 2017 6:49 PM, "Philipp Temminghoff" <notifications@github.com>
wrote:

2.24.0 is Jarvis though?
I thaught we only add new add-ons to jarvis and newer. Not sure if add-ons
which are already existing in "lower" repos are an exception for that rule.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xbmc/repo-plugins/pull/834#issuecomment-270033784>, or mute
the thread

**Comment by learningit** [comment]
Nevermind I'll close this later and submit in Jarvis branch. I really can't
remember if I use anything which is only Jarvis, so better to be safe. I'll
close this later.

**Pull request closed without merging**
