### PR TITLE
[plugin.video.filmfriend] 1.0.1

### PR DESCRIPTION
**Pull request by Ingo-FP-Angel**
### Description

- [Fix] Makes the plugin work again
- [Feature] Allows to play videos from your personal watchlist

The previous maintainer sarbes seems to have abandoned this plugin (last word from Nov. 2021, see https://forum.kodi.tv/showthread.php?tid=353903&pid=3073503#pid3073503)

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by basrieter** [comment]
@sarbes are you OK with this?

**Review by romanvm — APPROVED** [review]

**Comment by basrieter** [comment]
We still need an answer from @sarbes

**Comment by petterreinholdtsen** [comment]
How long is it reasonable to wait for replies from @sarbes before concluding no answer will show up?

**Comment by basrieter** [comment]
Pinged him again.

**Comment by sarbes** [comment]
Hi there. Sorry for the delay, I was a bit busy in the last few months.

Are you willing to take over the support of the add-on?

**Comment by basrieter** [comment]
@petterreinholdtsen  ping

**Comment by petterreinholdtsen** [comment]
[Bas Rieter]
> @petterreinholdtsen  ping

What can I do to help?  Note, I have nothing to do with filmfriend, and
am just a drive-by user trying to move a ticket forward. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Ingo-FP-Angel** [comment]
> Are you willing to take over the support of the add-on?

In principle yes.

One small complication: this addon depends on your "script.module.libmediathek4" which needs an additional change for this addon to work. And this PR here just fixes the login issues (also adds the personal watchlist), there are a couple of other things that do not work.

For lack of feedback here I created a fork with a slightly different addon id/name which has the necessary parts of "script.module.libmediathek4" embedded and fixed so using it would work out of the box. That fork is available via the Kodinerds addon repo which allowed me a much faster release/feedback cycle. Your name is still referenced as author and the metadata plus readme mentions where it was forked from.

So right now I'm a little unsure how to proceed. Keep working on the fork, abandon the fork and focus on the official addon repo (needs either fixing "script.module.libmediathek4" or embedding it into this repo), or keep both (the fork for rapid development and only porting stable versions over to the official repo)?

**Comment by petterreinholdtsen** [comment]
[Ingo-FP-Angel]
> Are you willing to take over the support of the add-on?

I do not use it, so I have no motivation.  Sorry.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sarbes** [comment]
The idea behind libmediathek was to decouple the content scraper from the Kodi API, so that I could mess with it separately. But besides some private prototypes, I have not used the scrapers in other capacities.

But still, it allowed me to have a single base for my common boiler plate code I use for my add-ons. And in combination by having the scrapers as libraries, I could have one lib powering multiple add-ons. For example, libzdf is used by the ZDF Mediathek, the 3Sat Mediathek and ZDF Tivi.

I don't know how invasive your changes to libmediathek are, but I could update it in my GH repository, so that you could start a PR which I can review. I'm just traveling at the moment, so it would have to wait a bit.

If your changes to LM4 are not detrimental for the other add-ons which use it, it is highly preferred to merge them there to avoid duplicate code we have to review.

**Comment by Ingo-FP-Angel** [comment]
In fact somebody else already created a PR with the necessary changes a while ago: https://github.com/sarbes/script.module.libmediathek4/pull/1
The change is pretty minimal I'd say.

**Pull request closed without merging**
