### PR TITLE
[plugin.video.catchuptvandmore@matrix] 0.2.37+matrix.1

### PR DESCRIPTION
**Pull request by joaopa00**
### Description
[Version 0.2.37]
[FR - Cnews] Fix live and replay
[CH - SSR] Fix error on SSR channels replay
[FR - SSR] Fix Alsace 20 and LaChaineNormande (DRM)
[BE - RTBF] Fix RTBF sometimes down
[BE - RTLPlay] Fix replay
[Website - FFF] Fix video playback error
[IT - Rai] Fix live TV
[FR - france.tv] Fix replay
[JP - FujiTV] Add the replay for FujiTV
[Website - FFF] Add more replays
[FR - Mycanal] Fix replay pour mycanal
[BE - RTLPlay] [FR - M6] choose live quality
[ES Live RTVE] Fix broken live url
[FR - RMC] Fix live for RMC channels
[FR - Replay] Fix Lumni replay
[BE - AB] Fix AB3 and AB Xplore
[SG] Add Channel News Asia (CNA) live
[FR] Add Tahiti Nui Télévision (TNTV) live
[ES live RealMadridTV] Fix broken url parsing
[BE-RTC] fix live
[WO- TV5MONDE] Fix TV5Monde live
[PL - TVP] Add stream for TVP Wilnoi
[BE - RTBFAuvio] Add TipikVision live
[FR - AlbiTV] Add live and replay for AlbiTV
[FR - RTL] Fix live for RTL radios group
[FR - DICI] Fix live for DICI and implement replay
[FR - RMCBMFPLAY] Add local BFM
[LT] Add LRT channels live
[WO - TV5MONDEPLUS] Enable TV5mondeplus
[Project] Add joaopa00 as releaser

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by enen92** [comment]
ping @sy6sy2 as @joaopa00 is flagged as first time contributor. Is this fine for review?

**Comment by joaopa00** [comment]
No news about this PR?

**Comment by sy6sy2** [comment]
Hi @enen92, sorry for the delay.
I'm a bit busy in real life since some time and @joaopa00 offered its help and motivation to update and maintains the add-on 😉
So no problem! Thank you in advance for the review!

**Comment by joaopa00** [comment]
Is it possible to have a review for this Pull Request?
Thanks in advance?

**Comment by joaopa00** [comment]
Is it possible to receive a feedback for this PR? It spent 2 months from the first request. The owner of Catchuptvandmore pushes himself the patch and he confirmed I can send pull request for Catchuprvandmore.

So, why is this pul request  not merget yet?

Thanks in advance for any hints to make this pull request merged...

**Review by enen92 — APPROVED** [review]
Sorry for the delay. This addon is always a pain in the ass to review because of its size.

**Pull request merged**
