### PR TITLE
[plugin.video.ustvnow] 12.0.23

### PR DESCRIPTION
**Pull request by Lunatixz**
USTVnow plugin is broken, I do not plan on maintain code any longer. Please update... Thanks

### CODE REVIEW

**Comment by phil65** [comment]
commit message is wrong, PR title is wrong.

**Comment by Lunatixz** [comment]
addons.xml wiki doesn't indicate what broken types are available... "deprecated" is the only example given.

Can you tell me the proper title for the commit?

Thanks

**Comment by phil65** [comment]
"Commit message". ;) 
[addon.name] versionnumber

**Comment by learningit** [comment]
The PR is now correct, the Commit Message is still incorrect. They should basically be the same.
You can put any message that you wanted displayed in the \<broken\> tag field, far as I know there is no standard.

**Comment by Lunatixz** [comment]
Thanks, figured there was a standard for the tag.

**Comment by phil65** [comment]
Even wronger now :) You now have two commits with message "Update addon.xml". You need to make it one commit with message "ADDON_ID ADDON_VERSION"

**Comment by MartijnKaijser** [comment]
pushed it myself

**Pull request closed without merging**
