### PR TITLE
Add travis buddy to Krypton

### PR DESCRIPTION
**Pull request by razzeee**
Travis buddy will comment on every PR on either failure or success of the ci and attach the log. That way authors don't need to leave github or search in travis.

I figured we can start with one branch take some time, maybe align it and then role it out to everywhere.

So this is mostly about a nice frendly message on success/failure.

@enen92 @Rechi @Lunatixz

### CODE REVIEW

**Comment by Razzeee** [comment]
This above example is not what we will get with that markdown file. As travis buddy looks in the targeted branch for those files (no idea why, but that's how it is)

**Review by Rechi — APPROVED** [review]

**Comment by enen92** [comment]
Thanks :)

**Comment by Razzeee** [comment]
Let's see how it works before you thank me ;)
@mzfr was also involved big time

**Comment by mzfr** [comment]
@Razzeee I think everything will be nice and good :)

**Comment by Razzeee** [comment]
Hrm https://github.com/xbmc/repo-plugins/pull/1781#issuecomment-380597454

**Pull request merged**
