### PR TITLE
[plugin.video.tv3.cat] 1.4.0

### PR DESCRIPTION
**Pull request by jqandreu**
### Description
Fixed website changes

### Checklist:

- [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
Applying the following pacth will fix the failing addon-checker.
```
--- a/plugin.video.tv3.cat/resources/lib/tv3cat.py
+++ b/plugin.video.tv3.cat/resources/lib/tv3cat.py
@@ -18,6 +18,7 @@
 class UI:
     
     def __init__(self, url):
+        pass
         
         
     def addDir(name, url, mode,iconimage):
@@ -107,21 +108,28 @@ class UI:
         return ok
         
     def playVideo(self):
+        pass
 
 
 class DestaquemAction:
+    pass
     
     
     
 class MesVistAction:
+    pass
     
     
 class NoperdisAction:
+    pass
     
 
 class ColeccionsAction:
+    pass
     
     
 class SearchAction:
+    pass
     
 class ProgramesAction:
+    pass
```

**Comment by jqandreu** [comment]
Thanks Rechi. I will fix it

**Comment by jqandreu** [comment]
This error was solved previously. The actual code does not have <> operators

**Comment by Rechi** [comment]
Please adjust the following lines in the next update.
https://github.com/xbmc/repo-plugins/blob/18951c93684127dbce9d36c1b2133f17c978e16d/plugin.video.tv3.cat/default.py#L1049-L1051

**Comment by jqandreu** [comment]
Ok, I will adjust. Anyway I want to clean and redesign all the plugin in the next update

**Pull request merged**
