### PR TITLE
[plugin.video.cbcolympics] 2.1.0

### PR DESCRIPTION
**Pull request by fourpointsix**
### Description
- Better handling of M3U8 files and bitrate selection since 7 Mbit 1080p streams were added.
- More consistent handling of URLs containing Unicode characters
- Added five more "features" categories
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by basrieter** [comment]
Why not use the InputStream Adaptive add-on for the M3u8 streams? It does it all for you?

**Comment by fourpointsix** [comment]
Originally I did play the M3U8 and expected InputStream Adaptive to dynamically switch streams as bandwidth allowed, but in my testing on both Kodi 18 and 19 I found that it just picked the first stream and never upgraded it even as lots of bandwidth was available. The "adaptive" part didn't seem to function in the way I expected it would. I was able to use the "choose program" feature to choose the stream manually so I knew it was reading all of the streams correctly at least. But I wanted the highest bitrate stream to be automatically used so I made the addon pick it itself.
If there's something I missed or needed to do to make it adapt dynamically, I'd prefer that route.

**Comment by basrieter** [comment]
> Originally I did play the M3U8 and expected InputStream Adaptive to dynamically switch streams as bandwidth allowed, but in my testing on both Kodi 18 and 19 I found that it just picked the first stream and never upgraded it even as lots of bandwidth was available. The "adaptive" part didn't seem to function in the way I expected it would. I was able to use the "choose program" feature to choose the stream manually so I knew it was reading all of the streams correctly at least. But I wanted the highest bitrate stream to be automatically used so I made the addon pick it itself.
> If there's something I missed or needed to do to make it adapt dynamically, I'd prefer that route.

It picks the best resolution when starting. It takes into consideration the resolution of Kodi (if you have it Windowed, it will not exceed the window size). It does not "just pick" the first stream available. For me, it picks the best stream for the Kodi size. 

It will not dynamically switch while playback, nor will your solution. It does automatically add subtitles and handle encryption for Widevine streams.

**Comment by fourpointsix** [comment]
That was also not my experience. It consistently picked the first stream regardless of resolution (720p stream on full-screen 1080p system). Maybe it wasn't functioning correctly for me. Regardless, when there are multiple streams of the same resolution I would want it to prioritize them by bitrate.

You're correct, mine won't dynamically change. My goal was to max out the bitrate and stay there.

**Review by basrieter — APPROVED** [review]

**Comment by basrieter** [comment]
Well, I will merge this. Double check the InputStream Adaptive and see if it was configured correctly. It usually helps you with the streams.

**Comment by fourpointsix** [comment]
Thank you! I'll take another look at InputStream Adaptive. Maybe it'll work better for me before the next Olympics :-)

**Pull request merged**
