### PR TITLE
[plugin.video.composite_for_plex] 0.8.3.1

### PR DESCRIPTION
**Pull request by anxdpanic**
### Description
Equivalent version: https://github.com/xbmc/repo-plugins/pull/2724
Required Matrix changes only: https://github.com/anxdpanic/plugin.video.composite_for_plex/compare/official_repository_matrix

Requires `script.module.kodi-six` and `script.module.pyxbmct` in [repo-scripts/matrix](https://github.com/xbmc/repo-scripts/tree/matrix) before merging.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by anxdpanic** [comment]
@romanvm This add-on requires `script.module.kodi-six` and `script.module.pyxbmct` in the matrix repository, is there anything I can do to help with that?

**Comment by romanvm** [comment]
@anxdpanic I'll submit the modules ASAP.

**Comment by romanvm** [comment]
Travis failure is a false positive, BTW.

**Comment by enen92** [comment]
Oops. Made a mistake and merged the wrong PR.
@romanvm can you bump kodi-six in matrix as soon as possible?

**Comment by anxdpanic** [comment]
@enen92 No worries, I'll field any issues that crop up. The add-on is still relatively new so should be very low impact.

@romanvm This add-on also requires script.module.pyxbmct in matrix, no rush though. As I mentioned above this should be very low impact.

**Pull request merged**
