### PR TITLE
[plugin.video.southpark_unofficial] 0.4.7

### PR DESCRIPTION
**Pull request by wargio**
### Description

I've just added the next season (22) since it's going to be aired September 26 (2018)

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by wargio** [comment]
Must be a false positive. those XML are Valid. i've validated them against several parsers.

**Comment by Rechi** [comment]
@wargio please migrate strings.xml language files to strings.po. See https://kodi.wiki/view/Language_support#What_is_strings.po for more info.

**Comment by Rechi** [comment]
> Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

As you checked that point in the PR description, also follow it.

**Comment by wargio** [comment]
Oh. i will!

**Comment by wargio** [comment]
@Rechi is that `*.po` format also supported on older version of Kodi?

**Comment by Rechi** [comment]
Yes it is, even supported in Gotham. Only the new language folder layout (mentioned in the wiki article) isn't supported in Helix and lower so keep your directory structure as is. Example for your add-on `plugin.video.southpark_unofficial/resources/language/German/strings.po`.

**Comment by wargio** [comment]
ok, i've also tested on helix and it seems to work.

**Comment by Rechi** [comment]
Please also fix the commit message.

```
git commit --amend -m '[plugin.video.southpark_unofficial] 0.4.7'
git push -f ....
```

**Comment by wargio** [comment]
ops, sorry :(

**Pull request merged**
