### PR TITLE
[plugin.video.truthvideos] v2.0.0

### PR DESCRIPTION
**Pull request by milezzz**
### Description
- Update to an existing addon: Truth Videos is a simple aggregator of alternative news sources.
- Requires: xbmc.python, script.module.addon.common, plugin.video.youtube

v2.0.0 - Apr 9, 2017

- Now has 25 different alternative news sources

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Razzeee** [comment]
As this is a new addon it needs to target krypton at minimum to get accepted. 

See for more information:
http://kodi.wiki/view/Submitting_Add-ons#Allowed_submissions

**Comment by milezzz** [comment]
Well technically it's not a new addon, it is already in the repository but was accepted before you started using Github. Anyways I will resubmit targeting the Krypton branch.

**Comment by Razzeee** [comment]
Just for the sake of clearness. We've been using github in the background since dharma. So if you submitted something via the mailinglist, we've basically added it to the github repo for you.
I've just searched for your addon in every current branch, nothing there. So either the name changed or it was removed at one point. :/

**Comment by milezzz** [comment]
@razzeee: Thanks friend...That's strange because it's still appearing in the repo and myself and others have been installing it recently. Anyways, I resubmitted it under branch Krypton just now  =)

**Comment by Razzeee** [comment]
@milezzz which repo? which version? is it also named `truthvideos`?

**Comment by milezzz** [comment]
Krypton. Here it is:  https://github.com/xbmc/repo-plugins/pull/1139

**Comment by Razzeee** [comment]
Sorry, I was asking which kodi version you were using when you installed it, I can search for it again then.
I'm pretty sure you might have had other repos installed which offered your addon.

**Comment by milezzz** [comment]
@Razzeee I see it in the Kodi official repos on v16 and v17, but I can see from searching me email it was originally submitted to the mailing list as:

*addon - plugin.video.truthvideos
*version - 1.0.1
*url - https://github.com/milezteg/truthvideos.git
*revision - 360a1c675aa620598b2ff50567451404
*branch - master
*xbmc version - helix

See it here:  http://kodi.wiki/view/Add-on:Truth_Videos

Hope that helps...I currently have it as a PR on both Helix and Krypton branches so not sure which you want to accept but I will leave both open.  Thanks for your help =)

**Comment by milezzz** [comment]
Woops forgot the exec call...going to fix this now and resubmit.

**Pull request closed without merging**
