### PR TITLE
[plugin.video.tv3.cat]1.3.9

### PR DESCRIPTION
**Pull request by jqandreu**
### Description
Fixed web server changes. Adapted to Kodi Krypton

### Checklist:

- [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
@jqandreu please take a close look até the issues found by the continuous integration bot (Travis)

**Comment by jqandreu** [comment]
Ok, thanks. I have seen the errors with strings.xml files and new folder hierachy. I will fix it

**Comment by Rechi** [comment]
@jqandreu any reason to not updated your addon in [gotham branch](https://github.com/xbmc/repo-plugins/tree/gotham/plugin.video.tv3.cat)[](https://github.com/xbmc/repo-plugins/tree/gotham/plugin.video.tv3.cat)?

**Comment by jqandreu** [comment]
No. I only want the plugin could be compatible with krypton. If I update in gotham branch will be compatible with krypton?

**Comment by Rechi** [comment]
If you updated it in gotham branch the new version will be available for gotham - leia (including krypton).
With your current PR the new version will be only available for Krypton and new versions.
see https://kodi.wiki/view/Submitting_Add-ons#Allowed_submissions (Which repos are used)

**Comment by jqandreu** [comment]
Ok. Then I will close this PR and will open another in the gotham branch. People with old kodi versions would install the plugin also. Thanks

**Comment by jqandreu** [comment]
Rechi, enen92, I opened a new PR to gotham  4 days ago and has not been reviewed yet. Is there any problem with the PR? Anything wrong?

**Pull request closed without merging**
