### PR TITLE
[plugin.video.cdapl] v1.0.0

### PR DESCRIPTION
**Pull request by avalanchy**
The first version of a properly working addon for http://www.cda.pl/ web application. Cda.pl is a polish portal with flash games and videos. This addon obviously focuses only on displaying the videos.

Cda.pl, unfortunately, does not provide API, so this addon is a scrapper for their mobile (m.cda.pl) page which is couple times lighter than desktop.

Motivation is to create unofficial but dedicated and simple addon that does a good job in one thing - watching videos from cda.pl and nothing more.
 
Features in this (1.0.0) version:
- Opening addon displays list with "Szukaj..." (en. "Search...") directory that opens dialog window and waits for user input. 
- Leaving dialog empty does nothing.
- No results returned from cda.pl, makes "ok" dialog to pop with the message that there were no results.
- Proper typing will present a list with up to 10 results.
- Results contain title, duration, and thumbnail.
- Playing the video will always use the highest quality available. 
- All art images are added and based on those provided by http://www.cda.pl/logotyp
- The addon XML file is in English and Polish. 

QA:
- Done by me under Kodi 16.1 Git:c327c53 Ubuntu 16.04.1 LTS

Screenshots:

- [kodi_012](https://cloud.githubusercontent.com/assets/1640089/22628696/1fa164b4-ebd9-11e6-9285-672470c99851.png)
- [kodi_016](https://cloud.githubusercontent.com/assets/1640089/22628701/3143fe48-ebd9-11e6-922d-37d7a5610c9c.png)
- [kodi_017](https://cloud.githubusercontent.com/assets/1640089/22628943/3be0099c-ebdd-11e6-8a9b-5170ee3eafd6.png)
- [kodi_018](https://cloud.githubusercontent.com/assets/1640089/22628945/443dff9a-ebdd-11e6-9c70-e0a17cd8c685.png)
- [kodi_019](https://cloud.githubusercontent.com/assets/1640089/22628946/45feb144-ebdd-11e6-93d7-033314afdb89.png)

Plans for next versions:
- Use xbmcswift2 framework ([at least its router for the start](https://xbmcswift2.readthedocs.io/en/latest/quickstart.html#url-routing)).
- Translate python strings to English ([in disclose_tv addon it looks nice](https://github.com/avalanchy/repo-plugins/blob/jarvis/plugin.video.disclose_tv/addon.py)).
- Add the pagination support.
- Add search history.
- Add views history.
- Add quality info (480p, 720p, 1080p) in the search results.
- Scraper client class (based on requests lib) with a proper User-Agent header.

### CODE REVIEW

**Comment by enen92** [comment]
@avalanchy cda.pl seems to be a site to which anyone can upload content. There are there recently released movies and shows with "DVDrip" in the title. So this is probably just another piracy addon. Have you read our piracy policy (http://forum.kodi.tv/showthread.php?tid=119117) ?

**Comment by enen92** [comment]
@avalanchy any comment?

**Comment by avalanchy** [comment]
Anyone can upload the videos to cda.pl - that's true. But what I know, they are responsive, and for every request about pirated content videos are being removed. But still, you are able to find pirated content in there.

Additionally, they are a very popular streaming portal in Poland, next to YouTube, LiveLeak or DailyMotion. A lot of "funny" videos are uploaded there. Also a lot of vloggers got their channel:
http://www.cda.pl/arhn-eu
http://www.cda.pl/UwagaNaukowyBelkot
http://www.cda.pl/VideoKuchniapl

**Comment by romanvm** [comment]
> Use xbmcswift2 framework (at least its router for the start).

xbmcswift2 is seriously outdated so I would not recommend to use it. I'd recommend [routing](https://github.com/tamland/kodi-plugin-routing) module that does only routing as the name implies.

**Comment by enen92** [comment]
Unfortunately this website is full of pirated content. Due to this reason, we cannot accept it on the official repository.

**Pull request closed without merging**
