### PR TITLE
[plugin.video.intergalacticfm] 2.3.0

### PR DESCRIPTION
**Pull request by dromer**
### Description
Version 2.3.0
Added Austin Cassel and The Dream Machine
Temp disable YouTube channels (needs API key)

Version 2.2.0
Added IFM and Viewlexx YouTube channels

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by dromer** [comment]
(should be ok now .. I hope :) )

**Comment by enen92** [comment]
^^ please fix the `ERROR` and `WARNING` generated by addon-checker

**Comment by dromer** [comment]
yes we are looking in to it. images are being made smaller, but is the diff a suggested fix to force a `list()` casting?

**Comment by enen92** [comment]
That's just a 2to3 auto-conversion warning you can safely ignore it - false positive. See here for a explanation: https://stackoverflow.com/questions/27476079/why-does-2to3-change-mydict-keys-to-listmydict-keys

**Comment by enen92** [comment]
Closing as it looks stalled. Please resubmit to a proper branch if you're still interested in having this plugin on the official repo.

**Comment by dromer** [comment]
Yeah sorry, had some hickups. Thnx for the reminder ;)

**Pull request closed without merging**
