### PR TITLE
plugin.video.dumpert111 2nd try

### PR DESCRIPTION
**Pull request by skipmodea1**
PR on jarvis in stead of master. I hope this works ...

### CODE REVIEW

**Comment by learningit** [comment]
This shouldn't have 4 commits in it. I'm not sure, but it looks like you didn't do a rebase before doing the 'compare and create pull request', so your local jarvis repo was out of sync with the current xbmc/repo-plugins version.

**Comment by skipmodea1** [comment]
Here is what i did this morning, please look at it and say what should be done differently exactly (in git commands).

Cd C:\Kodi_fork
# Clone your fork of kodi's repo into the current directory in terminal
git clone git@github.com:skipmodea1/repo-plugins.git repo-plugins
# Navigate to the newly cloned directory
cd C:\Kodi_fork\repo-plugins
# Assign the original repo to a remote called "upstream"
git remote add upstream https://github.com/xbmc/repo-plugins.git
cd C:\Kodi_fork\repo-plugins
#If you cloned a while ago, get the latest changes from upstream:
# Fetch upstream changes
git fetch upstream
# Goto the jarvis branch
git checkout -b jarvis
# Merge upstream changes
git merge upstream/jarvis
#Create a new branch to contain your new add-on or subsequent update:
git checkout -b b-plugin.video.dumpert111-2
Copy the updated addon dir to C:\Kodi_fork
Delete .git dir, .gitattributes, .gitignore and .pyo from the addon dir
Git status
Git add .
Git status
Git commit -m "[plugin.video.dumpert] 1.1.1-2"
#Push your topic branch up to your fork
git push origin b-plugin.video.dumpert111-2
And then made Pull Request.

**Comment by kib** [comment]
When you make the pull request, select the same branch as you previously
pulled and don't leave it at master.

:)

**Comment by skipmodea1** [comment]
If i knew how, i would

**Comment by kib** [comment]
select the correct branch on both sides before clicking on make pull
request on github.

**Comment by skipmodea1** [comment]
So this isn't correct?
pull request

**Comment by learningit** [comment]
No because you didn't create a separate branch for 1.1.1, Look here: https://github.com/skipmodea1/repo-plugins/tree/b-plugin.video.dumpert111-2

There's a bunch of other stuff which shouldn't be in the branch.

**Comment by skipmodea1** [comment]
I give up

**Comment by Paxxi** [comment]
Don't give up @skipmodea1 we'll get this sorted. This is where you went wrong
```
git fetch upstream
git checkout -b jarvis
git merge upstream/jarvis
git checkout -b b-plugin.video.dumpert111-2
```
if you replace those steps with
```
git fetch upstream
git branch jarvis b-plugin.video.dumpert111-2
git checkout b-plugin.video.dumpert111-2
```
That should give you a clean PR. What has happened is that checkout -b creates a new branch and then merging another branch into it creates a merge commit which drags in all the commits that got merged.

**Comment by skipmodea1** [comment]
Thanks Paxxi! I will give it another go.

**Comment by skipmodea1** [comment]
I'm getting an error:
C:\Kodi_fork\repo-plugins [master]> git branch jarvis b-plugin.video.dumpert111-3
>>
fatal: Not a valid object name: 'b-plugin.video.dumpert111-3'.

**Comment by phil65** [comment]
branch names may not contain dots.

**Comment by Paxxi** [comment]
sorry about that, think I got the order mixed up with the move command, switch to `git branch b-plugin.video.dumpert111-3 jarvis` and it should work better

**Comment by skipmodea1** [comment]
Btw, thanks for the help, guys. 

Unfortunately i'm still getting the same error:
C:\Kodi_fork\repo-plugins [master]> git branch b-plugin.video.dumpert111-3 jarvis
fatal: Not a valid object name: 'jarvis'.

**Comment by Razzeee** [comment]
You probably need to do upstream/jarvis

**Pull request closed without merging**
