### PR TITLE
[plugin.video.adultswim] v2.0.0

### PR DESCRIPTION
**Pull request by jsergio123**
### Description
Stream unlocked episodes from adultswim.com
Existing metahandler and multiple bitrates support

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by learningit** [comment]
This is already in the Kodi.org repo.

**Comment by learningit** [comment]
You can update the existing add-on with a PR, but you cannot add a new one.

**Comment by learningit** [comment]
You can update the existing add-on with a PR, but you cannot add a new one.

**Comment by jsergio123** [comment]
@learningit my version differs from yours not to mention I submitted mine first which I don't want to get into. Also I believe your version is broken currently.

**Comment by jsergio123** [comment]
@learningit but you're not the author....

**Comment by jsergio123** [comment]
@learningit but you're not the author of adultswim kodi addon...

**Comment by jsergio123** [comment]
@MartijnKaijser

**Comment by learningit** [comment]
It's a 10 second fix for the one in the repo. Until you pointed it out, no one indicated it's broken so thanks for that. I'll update it tomorrow when I'm in a place that has real internet,
There's really no reason to remove the one in the repo.

**Comment by jsergio123** [comment]
@learningit where does it state in the in the addon rules or contributing docs that there can't be 2 different version of an addon that uses the same site?

**Comment by learningit** [comment]
It's to do with your past actions, which I find extremely offensive and unprofessional. Luckily for you, I've washed my hands of this and will let others decide.

**Comment by jsergio123** [comment]
then open the pr and let someone else review it. thanks

**Comment by learningit** [comment]
Everyone on the team does see it, regardless of open or closed. Any team member can reopen it as they desire.

**Comment by learningit** [comment]
I believe in fairness, so I've messaged the team internally that I will not be dealing with this and that another team member should.

**Comment by learningit** [comment]
I will also be submitting a PR to fix the existing Adult Swim add-on in the repo when I have access to stable internet.

**Comment by jsergio123** [comment]
That's fine can we just scratch this pr and just start a new one? I hate having conversions on github plus I like to have just one commit for them to review.

**Comment by learningit** [comment]
It's actually good to have this conversation for context so everyone can read and understand it. Feel free to squash all your commits here. I will reopen the PR so that you can.

**Comment by learningit** [comment]
If you need help to squash, let me know.

**Comment by jsergio123** [comment]
oops lol

**Pull request closed without merging**
