### PR TITLE
[plugin.video.videolina] 1.0.0

### PR DESCRIPTION
**Pull request by NextStepUnione**
### Description

Watch Videolina live streaming

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Tadly** [comment]
We've had internal discussion about fanart right after your initial PR and the conclusion was that it is in fact a requirement (sorry for that, this one's on me).

Now, before you close this PR and create a new one. You can just force push.

Just add a fanart and commit it, than squash the two commits and finally force push.
This will save you the trouble of recreating the whole PR and save you some time if you know how to.

**Comment by Razzeee** [comment]
But please don't use the Kodi logo for it :)

**Comment by Tadly** [comment]
Whew! That's one humongous fanart.
Lemme phrase a line from the [add-on rules](http://kodi.wiki/view/Add-on_rules):
> fanart.jpg must be present (1280x720 or 1920x1080)

8000x4500 is just a tiny little bit to big

**Comment by Tadly** [comment]
that's better.
I approve, anyone else having any objections?

**Comment by NextStepUnione** [comment]
@Tadly forgive me for the wrong size, I've added a new one with the right size now. @Razzeee As you surely have Noted I've used one example plugin and edited the files, I'm not a python programmer so forgive me for the previous unnecessary imports in addon.py. For the funart image I forgot to delete it (I did not know That it was mandatory). I'm tenacious, I Know That soon or later our TV plugin will be on Kodi :) thanks for your patience

**Pull request merged**
