### PR TITLE
[plugin.video.jafc] 1.1.0

### PR DESCRIPTION
**Pull request by FraserChapman**
### Description

Updated to (hopefully) be Python 3 compatible 
Removed all special:// uris
Changed streams from M3U8 to MPD

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by FraserChapman** [comment]
Travis barffed 1st go...simply closing and reopening the PR fixed it though...Looks like a read time out on mirror.hro.nl FWIW

> /virtualenv/python3.7.1/lib/python3.7/site-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/sessions.py", line 668, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/sessions.py", line 668, in <listcomp>
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
>     **adapter_kwargs
>   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPConnectionPool(host='mirror.hro.nl', port=80): Read timed out. (read timeout=10)
> ```

**Comment by Rechi** [comment]
@FraserChapman this add-on isn't Python 3 compatible. Future updates have to be compatible with Python 3.
Have a look at https://kodi.tv/article/attention-addon-developers-migration-python-3 for more information.

**Comment by FraserChapman** [comment]
@Rechi - thanks for that...again sorry to be a pest - what is incompatible with P3? I had thought based on the last 2 PRs that it was simply the bit in the generic logging script that was the issue. Really would like to get these merged with P2/3 compatibility. Thanks

**Comment by Rechi** [comment]
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'ModuleNotFoundError'>
    Error Contents: No module named 'kodilogging'
    Traceback (most recent call last):
      File "<...>\plugin.video.jafc\main.py", line 3, in <module>
        from resources.lib import plugin
      File "<...>\plugin.video.jafc\resources\lib\plugin.py", line 16, in <module>
        import kodilogging
    ModuleNotFoundError: No module named 'kodilogging'
    -->End of Python script error report<--
```
But there are further issues after fixing that error.

**Comment by FraserChapman** [comment]
@Rechi - thanks... thats really odd as the import is working. FWIW I am just building Kodi for OSX now with Python 3 so I can test myself. As an aside, it would be great if a test binary for Kodi with P3 was available as building from source is a faff and it would be really great to test the plugins against (for others).

Many thanks for your reply :)

**Pull request merged**
