### PR TITLE
[plugin.video.magaritv] 1.0.0

### PR DESCRIPTION
**Pull request by ogiliberti**
Dear All,
I would like to add the plugin described below
addon - plugin.video.magaritv
version - 1.0.0
revision - ae38b7c
url - https://github.com/ogiliberti/plugin.video.magaritv
xbmc version - jarvis

Best Regards,
Orazio Giliberti

### CODE REVIEW

**Comment by ogiliberti** [comment]
I know this PR is perfect wrongly.
I didn't find any area where to modify the mythical phrase "Added files via upload"

However I attached a .pdf files with the prontscreen about what I have done to be at this point.
Please tell me where I did wrongly.

Thanks for your kind attention.

Best Regards,

Orazio Giliberti
[SubmitGitHubProcess.pdf](https://github.com/xbmc/repo-plugins/files/251059/SubmitGitHubProcess.pdf)

**Comment by hudokkow** [comment]
While in branch <code>plugin.video.magaritv</code> of repo-plugins (make sure you are with <code>git checkout plugin.video.magaritv</code>) and using shell/terminal/whatever you call it:

- git commit --amend -m "[plugin.video.magaritv] 1.0.0"
- git push -f

Magic things will happen! :wink:

**Comment by Razzeee** [comment]
@ogiliberti 
your PDF missed the step where you added/uploaded the files to your fork. That's where the dialog from my screenshot shows up.

**Comment by ogiliberti** [comment]
Razzee,

Thanks for your reply.

With reference to my .pdf file:

what is the page before this missed step ?

what steps/pages are correct ?

Basically I would like to know from what step/page my submit process 
diverts from the right path.

Thanks for your attention.

Best Regards,

Orazio Giliberti


Il 06/05/2016 09:36, Razzeee ha scritto:
> @ogiliberti <https://github.com/ogiliberti>
> your PDF missed the step where you added/uploaded the files to your
> fork. That's where the dialog from my screenshot shows up.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/460#issuecomment-217371214>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Comment by Razzeee** [comment]
Between pages 1 and 2. You somehow added your files to your fork. Before you can create a new pull request and compare your changes.

**Comment by ogiliberti** [comment]
Razzeee,

Thanks!

So in page 2 I have to press button upload file ?

Best Regards,

Orazio


Il 06/05/2016 10:12, Razzeee ha scritto:
> Between pages 1 and 2. You somehow added your files to your fork. Before
> you can create a new pull request and compare your changes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/460#issuecomment-217377282>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Comment by Razzeee** [comment]
Well I would guess that you did that?
Or how did you get your files uploaded?

**Comment by ogiliberti** [comment]
Razzeee,

I followed the steps in the .pdf file.
To create this file a resubmitted the PR.

Best Regards,

Orazio


Il 06/05/2016 10:34, Razzeee ha scritto:
> Well I would guess that you did that?
> Or how did you get your files uploaded?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/460#issuecomment-217383251>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Pull request closed without merging**
