### PR TITLE
[plugin.video.crackle] 2020.10.4

### PR DESCRIPTION
**Pull request by eracknaphobia**
### Description

        - Improve Sorting of list items (thanks ssreekanth)
        - Add DRM playback support for HD quality
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by enen92** [comment]
2020.10.4 > 2020.10.1, you have to update matrix first otherwise users won't be able to migrate your addon when updating kodi from leia to matrix

**Comment by eracknaphobia** [comment]
Ok, I wasn't sure about that. Would it be ok to make it the same version number or should I make it 2020.9.30?

**Comment by enen92** [comment]
No as it will not update too (same version). That's why we are using PEP440 localversion identifiers:

Leia: 2020.10.4
Matrix: 2020.10.4+matrix.0

That way the version is effectively the same (usually just the xbmc.python bump in addon.xml) but the matrix version is still lexically higher than the leia one

**Comment by eracknaphobia** [comment]
So in order to get the new version of this addon out for python 2 versions of kodi I should create two pull requests, correct? One to bump the matrix version to include the new `+matrix.0` and one targeting the krypton branch without.

**Comment by enen92** [comment]
Yes, and then the matrix one should be merged and we need to wait for the repo to sync (~2hours) so that this one is green on travis

**Review by enen92 — APPROVED** [review]

**Pull request merged**
