### PR TITLE
[plugin.video.media-ccc-de] 0.0.6 (Mark old versions as broken, see #1154).

### PR DESCRIPTION
**Pull request by TobiX**
### Description

Remove the old version of the plugin from the Gotham repository, to be reintroduced in Jarvis, mostly out of TLS 1.2 compatibility concerns (all media.ccc.de servers only support TLS 1.2, some still support TLS 1.1).

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Razzeee** [comment]
I don't think we remove stuff, I think we mark it as broken first.

http://kodi.wiki/view/Addon.xml#.3Cbroken.3E

Right @MartijnKaijser ?

**Comment by MartijnKaijser** [comment]
Usually we mark it broken with a message. After several months we remove it

**Comment by TobiX** [comment]
Then how is the process to move a plugin to a newer branch (see #1154)?

**Comment by Razzeee** [comment]
Just set it as broken and move everything to the new branch. The branches are done in a way that they don't conflict as long, as the version numbers are not higher in the older branch.

**Comment by MartijnKaijser** [comment]
you can bump this one to 0.0.6 and use the broken tag in addon.xml
The one for Jarvis has a higher version so that will auto override the broken version for Jarvis users.
My suggestion is to first push the newer version and then this one broken (or at same moment)

**Comment by TobiX** [comment]
Like this?

**Pull request merged**
