### PR TITLE
[plugin.audio.pureradio] 1.0.0 

### PR DESCRIPTION
**Pull request by bdommel**
### Description
This plugin enables the playback of the PureRadio audio stream, which can be set in different qualities using different bitrates. Also a selection of podcast, hosted on Spreaker, are available for instant playback.
### Checklist:
- [X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by Razzeee** [comment]
The first commit tries to add the folder ` plugin.audio.pureradio.git` I think that's not what you want to do is it?

**Comment by bdommel** [comment]
I thought I had that removed and cleaned it up before commiting. It should only contain the plugin folder.

**Comment by bdommel** [comment]
I removed the folder with the .git extention. Sorry for the inconvience.

**Comment by Razzeee** [comment]
Are you able to squash these three commits into one?

**Comment by bdommel** [comment]
I squashed the commits.

**Comment by bdommel** [comment]
Perhaps it is better to close this commit and do a single commit with all changes.

**Pull request closed without merging**
