### PR TITLE
[plugin.video.eafa 1.1.0

### PR DESCRIPTION
**Pull request by FraserChapman**
### Description

Updated to be Python 3 compatible and use the script.module.cache addon - for Leia. 

Ideally I'd like to leave the Krypton version at 1.0.0.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by enen92** [comment]
Hey @FraserChapman any reason for submitting to leia and not just updating the version already in the krypton branch? I strongly recommend to keep only one version (both py2 and py3 compatible) since doing this for all addons might easily turn into a maintenance nightmare.

**Comment by FraserChapman** [comment]
@enen92 - Hey - yes the main reason is that I was moving the older plugins over to use the script.module.cache I created - but this is only in Leia unfortunately...

I did post a question about versioning on the forum but it got no response - https://forum.kodi.tv/showthread.php?tid=344934 so just did what I figured was best.
My thinking was - the older ones aren't PY3 compatible (hence need updating) and when I update them I'd like them to use the common cache module I created. 

For what it is worth I the Krypton add-ons are:
plugin.video.jafc
plugin.video.eafa
plugin.video.bfi
plugin.video.bcf

If the maintenance gets to be a chore then could I just deprecate the Krypton versions of the add-ons? Be super interested to know what you think is best here. 

Thanks for the question!

**Comment by enen92** [comment]
I'd be fine with including a new module in the krypton branch, as long as it a requirement for updating an already existing addon and you ensure both py2/py3 compatibility. Ofc this is no rule but some exceptions can be granted.

**Comment by FraserChapman** [comment]
OK cool - that sounds like a plan. I'll put together a PR for script.module.cache to go in Krypton and that way the existing add-ons can use it too. Pretty sure the module is PY2/3 compatible as it was originally intended for Krypton but was told in that PR "nothing new except in Leia".

Maybe leave this eafa PR open for now - then I'll close it and resubmit to krypton when I've made sure it is all working. 

Thanks for the support and slight bending of the rules :)

**Comment by FraserChapman** [comment]
@enen92 - OOI when I submit the PR for the script.module.cache to Krypton - I presume that if/when I update it in future would I need to PR the same to both branches (Krypton and Leia)? 

Also I presume that I would also need to do that for the plugins that are currently in both - i.e. PR  the same version in two branches? Sorry for all the questions - just want to make sure I understand the versioning properly before I start issuing PRs :)

**Comment by enen92** [comment]
No. Leia has access to all addons that are in Leia, Krypton, Jarvis, Isengard, Helix and Gotham branches. Krypton has access to Krypton, Jarvis, Isengard, Helix and Gotham, and so on.
So you only need to have 1 version of the script.module, as long as the addons that depend on it are either in the same or upper branches

**Comment by FraserChapman** [comment]
@enen92  - OK there is a PR for a new version of script.module.cache here: https://github.com/xbmc/repo-scripts/pull/1115

Hope that updating the version doesn't complicate things further. 

To clarify - after the merge - script.module.cache would be:
Leia: 1.0.0, 1.0.1
Krypton: 1.0.2

So I would then go back and amend this EAFA PR to merge into Krypton referencing the 1.0.2 version of the cache module.

Thanks.

**Pull request closed without merging**
