### PR TITLE
[plugin.video.invidious] 0.2.8+nexus.0

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
A privacy-friendly way of watching YouTube content. Uses the great Invidious web service's API to do the heavy lifting.

Adjusted autodetection code to avoid picking partly working service provider. Made first run more robust.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by basrieter** [comment]
Please fix your conflict @petterreinholdtsen

**Comment by petterreinholdtsen** [comment]
[Bas Rieter]
> Please fix your conflict @petterreinholdtsen

Done.  Sorry for the confusion.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Do I need to fix anything more before this is ready for publication?

**Review by basrieter — APPROVED** [review]

**Comment by basrieter** [comment]
Thanks for you contribution @petterreinholdtsen and your patience.

**Pull request merged**
