### PR TITLE
[plugin.video.catchuptvandmore] 0.1.2

### PR DESCRIPTION
**Pull request by SylvainCecchetto**
### Description
Update of Catch-up TV & More plugin from v0.1.0 to v0.1.2

**Changelog :**
 
[Add channel] 6ter
[Bug] NRJ 12: No video
[Improvement] NRJ 12: Add listing for categories and seasons
[Improvement] France Télévision (pluzz): Add search feature and "last videos" categories
[Bug] TF1: Video URL failed
[Bug] Gulli: Doesn't work
[Add channel] Numéro 23
[Add channel] Chérie 25
[Bug] Arte: Doesn't work
[Bug] Canal+: Bug with subcategories
[Add channel] France Ô
[Add channel] HD1
[Add channel] L'Équipe

Thanks a lot for your job!

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Razzeee** [comment]
Please have a look at your PR it's conflicting right now

**Comment by SylvainCecchetto** [comment]
Hi, It's possible to force the merge by overwrite older files? How can I do that?
Thanks a lot!

**Comment by Razzeee** [comment]
@SylvainCecchetto 
you will have to fetch the branches again and rebase your commit upon the updated krypton branch, then force push

**Comment by SylvainCecchetto** [comment]
Oh, I made to many errors, I closed this PR and I create a new one. Sorry for that ...

**Pull request closed without merging**
