### PR TITLE
[plugin.video.vrt.nu] v2.3.2

### PR DESCRIPTION
**Pull request by dagwieers**
### Description
- Fix issues related to categories scraping and caching (@mediaminister)
- Various improvements to TV guide (@dagwieers)

This is another bugfix release. Without the bugfix some of our users will have issues with the categories listing in 2 days (it expires after 7 days, since our last release).

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by dagwieers** [comment]
The error does not relate to our add-on, since it does not use **urllib3** or **requests**.
Something must be wrong with the build infrastructure.

**Comment by enen92** [comment]
@dagwieers xsd schema for addon.xml is defined to a max of 1500 chars: `<xs:maxLength xmlns:xs="http://www.w3.org/2001/XMLSchema" value="1500" /> `. Please try to keep it to the last release only (it is not a full changelog)

**Comment by dagwieers** [comment]
@enen92 We trim the news-section, but prefer to keep a few releases in there. I would have cleaned it up if Travis would have given me a sensible error :-) Thanks for your help!

**Comment by enen92** [comment]
The reason for the char limit is because, since news is part of addon.xml, it'll be available on the xml.gz manifest kodi downloads from the mirrors periodically. So if everyone abuses on the size of the news element, it causes harm to the infrastructure
Cheers, merged

**Comment by dagwieers** [comment]
Sure, I have no problem with the 1500 char limit. And we are not adding the complete changelog.

**Pull request merged**
