### PR TITLE
[plugin.video.cbc] 4.0.16+matrix.1

### PR DESCRIPTION
**Pull request by micahg**
### Description
Integrate with CBC Gem's new AAD B2C authorization system.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Review by romanvm — APPROVED** [review]
LGTM

**Comment by micahg** [comment]
Ty

**Comment by micahg** [comment]
Sorry - not clear - does this merge on its own or do I have to do something else?

Thanks in advance,

**Comment by micahg** [comment]
Hi - I don't have the option to merge - is there something else I need to do or are people just busy?

Thanks,

**Comment by micahg** [comment]
ty

**Pull request merged**
