### PR TITLE
[plugin.video.dazn] 1.3.2

### PR DESCRIPTION
**Pull request by JinRonin**
added youth protection pin (mainly for german users)

### CODE REVIEW

**Comment by dc95336** [comment]
What's the protection pin be for

**Comment by JinRonin** [comment]
Some content is protected in germany (pg-18) and you have to verify your age with dazn in order to watch it.
The update allows you to enter the pin you create.

**Comment by dc95336** [comment]
Ok thank you

**Comment by Rechi** [comment]
@JinRonin this add-on isn't Python 3 compatible, but all add-ons in Leia branch and higher have to be Python 3 compatible (see https://kodi.tv/article/attention-addon-developers-migration-python-3). Seems like the add-on was accepted before this rule was enforced. So please make your add-on Python 3 compatible.

**Pull request merged**
