### PR TITLE
[plugin.service.gto] 2.0.4

### PR DESCRIPTION
**Pull request by b-jesch**
Build this from scratch and I think now it's okay. Very hard for me.

### CODE REVIEW

**Comment by phil65** [comment]
Sorry, not ok. :) you might want to remove the second commit.

**Comment by b-jesch** [comment]
Language files converted from .xml to Transifex .po
Bump version to 2.0.3

**Comment by b-jesch** [comment]
- Improved channel comparsion and selection
- Improved ChannelTranslate.json
- Bump version to 2.0.4

**Comment by learningit** [comment]
Now there are 4 commits. Please see this for how to squash: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by b-jesch** [comment]
Not possible:
`
$ git rebase -i HEAD~4
Cannot rebase: You have unstaged changes.
Please commit or stash them.
`

`$ git status
On branch jarvis
Your branch is up-to-date with 'origin/jarvis'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   plugin.video.disclose_tv/LICENSE.txt
        modified:   plugin.video.disclose_tv/addon.py
        modified:   plugin.video.disclose_tv/addon.xml
        modified:   plugin.video.disclose_tv/changelog.txt
        modified:   plugin.video.disclose_tv/resources/language/Afrikaans/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Albanian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Amharic/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Arabic/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Basque/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Belarusian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Bulgarian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Burmese/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Catalan/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Chinese (Simple)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Chinese (Traditional)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Croatian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Czech/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Danish/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Dutch/strings.po
        modified:   plugin.video.disclose_tv/resources/language/English (Australia)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/English (New Zealand)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/English/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Estonian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Faroese/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Finnish/strings.po
        modified:   plugin.video.disclose_tv/resources/language/French (Canada)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/French/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Galician/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Georgian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/German/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Greek/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Hebrew/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Hindi (Devanagiri)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Hungarian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Icelandic/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Indonesian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Italian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Japanese/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Korean/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Latvian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Lithuanian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Macedonian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Malay/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Norwegian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Persian (Iran)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Persian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Polish/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Portuguese (Brazil)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Portuguese/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Romanian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Russian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Serbian (Cyrillic)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Serbian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Slovak/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Slovenian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Spanish (Argentina)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Spanish (Mexico)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Spanish/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Swedish/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Tamil (India)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Thai/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Turkish/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Ukrainian/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Vietnamese (Viet Nam)/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Vietnamese/strings.po
        modified:   plugin.video.disclose_tv/resources/language/Welsh/strings.po
        modified:   plugin.video.disclose_tv/resources/lib/scraper.py
        modified:   plugin.video.disclose_tv/resources/settings.xml
        modified:   plugin.video.infowars/License.txt
        modified:   plugin.video.infowars/addon.xml
        modified:   plugin.video.infowars/changelog.txt
        modified:   plugin.video.infowars/default.py
        modified:   plugin.video.tyt/resources/settings.xml

no changes added to commit (use "git add" and/or "git commit -a")
`

**Comment by learningit** [comment]
You don't want to include the first and second commit, so either don't pick them to be included in the squash.

**Comment by b-jesch** [comment]
Yeah, this is the last shit ever! This is drivin' me nuts!

**Comment by learningit** [comment]
Well, when I start getting lots of conflicts, I take the brute force method - delete the xbmc/repo-plugins from my local system and my github repo, fork the repo again, clone it to my local system, create a new branch from the base repo, add the add-on and do the compare and PR.

I can't see what you did to get the repo in this state, but I'm guessing the delete (which I've never used) did you in.

**Comment by b-jesch** [comment]
I use PyCharm for Development & Deployment and in normal circumstances this is ok for me even with the integrated VCS. Will close this crappy shit and start from scratch again as suggested - hey once again? Oh what a hell.

**Pull request closed without merging**
