### PR TITLE
[plugin.video.imdb.trailers] v2.1.7

### PR DESCRIPTION
**Pull request by Gujal00**
### Description
This addon allows to watch movie trailers available on IMDb Website
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
New add-ons are only allowed for Leia, see https://kodi.wiki/view/Submitting_Add-ons#Allowed_submissions.

**Comment by Gujal00** [comment]
okay but this addon will work on jarvis onwards and upto Matrix as it is py2/py3 compliant. Why not support even krypton? please confirm and I will close this PR.
A lot of devices still run Jarvis and so I thought it was appropriate, given that this addon has existed since Eden days, just not in the official repo. Thanks

**Comment by Razzeee** [comment]
Sorry, but if it has not been in the official repo, we can't have you "update" it. It counts as a new addon and needs to be send in to the leia branch.

**Comment by Gujal00** [comment]
okay will raise a new PR

**Pull request closed without merging**
