### PR TITLE
[plugin.video.skynews] 1.0.1

### PR DESCRIPTION
**Pull request by Lunatixz**
missing screenshots

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
missing screenshots? Isn't this a new addition?

**Comment by Lunatixz** [comment]
Lol my bad that's from my rename before the PR. Still learning how to squash commits.

**Comment by Lunatixz** [comment]
Sorry this is a new push, same code as 1.0.0 just a small correction and version bump. I'm still trying to get the hang of squashing my commit history. I apologize if things look messy.

**Comment by enen92** [comment]
No prob, sorry for taking a bit of time checking it.
Please next time try to add a simple description on the PR itself (it saves time since it states what to expect).
Cheers

**Comment by Lunatixz** [comment]
@enen92 np, I'm trying to figure out the best way to maintain my plugins without clearing my branch for each update. I noticed when I squashed commit history and PR it doesn't highlight changes but rather the whole code. Which makes your job harder :( any advice?

**Pull request merged**
