### PR TITLE
[plugin.video.vrt.nu] 1.9.0

### PR DESCRIPTION
**Pull request by dagwieers**
### Description
New release to remove dependency on requests/urllib3.
Recent issues causing performance degradation on Raspberry Pi made us decide to no longer rely on requests/urllib3.

**Update:** This also pro-actively fixed the current VRT NU website change that breaks category listing.

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by dagwieers** [comment]
cc @pietje666

**Comment by dagwieers** [comment]
@pietje666 Can you sign this one off ?

**Comment by pietje666** [comment]
Allowed!

**Comment by dagwieers** [comment]
@Rechi Can we get this released as soon as possible?

The VRT NU website today has again changed their categories listing and as such the addon failed on this. This v1.9.0 release already has fallback code, so is not affected.

Reference: https://github.com/pietje666/plugin.video.vrt.nu/pull/220

**Comment by dagwieers** [comment]
Thanks ! :+1:

**Pull request merged**
