### PR TITLE
[plugin.video.filmarkivet] 3.0.0

### PR DESCRIPTION
**Pull request by pugo**
### Description
Complete rewrite of the plugin to match the new updated source site (filmarkivet.se).
Removed several dependencies and new code is much cleaner and smaller.
Added caching for speed-ups.
### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a sinlge commit with using the following style: [plugin.video.foo] v1.0.0

Addtional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuesly monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by pugo** [comment]
If you by any chance react on the family name change of the author (me), from Karlsson to Piniesjö... it's still me. Me and my wife both changed family names when we married, a possible thing here in Sweden.

**Comment by phil65** [comment]
Please send the pull request to jarvis branch (and adjust your addon.xml accordingly)
We do not add new add-ons to isengard branch anymore.
Thanks in advance.

**Comment by pugo** [comment]
Ok, as this is an update for a plugin that has been existing in the repo for Kodi (and XBMC) for some 4-5 years, not a completely new one,  I thought it was OK to add it at least for one older version, to fix the broken-status with the add-on also for people not yet updated to latest version.

Will make a new PR tonight then.

**Comment by phil65** [comment]
ok, thx.

**Pull request closed without merging**
