### PR TITLE
plugin.audio.calmradio - 0.1.4

### PR DESCRIPTION
**Pull request by nire0510**
A new Kodi add-on for calmradio.com internet radio website (official add-on)

### CODE REVIEW

**Comment by nire0510** [comment]
@learningit I really hope I did it well this time :)

**Comment by learningit** [comment]
No good. You can't submit a subproject commit.

**Comment by nire0510** [comment]
@learningit First I followed the guidelines [here](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) then I tried to create branch from another branch as you told me to. Can you elaborate what exactly should I do?

**Comment by phil65** [comment]
1) you fork our script repository
2) you clone that repository so you have a local copy.
3) you switch to the correct branch in your local repository, then you create a new branch from there.
3) you add your script as a single commit to this new branch
4) you push that new branch to your github repository.
5) you set up a pull request: your new branch --> correct script repository branch

**Comment by learningit** [comment]
One small embellishment on the above. in item #1 you fork the xbmc/plugin-repo repository.

**Comment by nire0510** [comment]
@phil65 thanks a lot, but this is exactly what I did... Can you point me to the step you think I missed?

**Comment by phil65** [comment]
Perhaps you also accidentally added your .git folder in step 3?

**Comment by nire0510** [comment]
@phil65 maybe that's what happened... Sorry for all the mess, it's my first submission to your repo... Just submitted a new PR, hopefully this time it'll pass ;)

**Pull request closed without merging**
