### PR TITLE
[plugin.video.tvvlaanderen@matrix] 1.0.3+matrix.1

### PR DESCRIPTION
**Pull request by michaelarnauts**
### Add-on details:

- **General**
  - Add-on name: TV Vlaanderen
  - Add-on ID: plugin.video.tvvlaanderen
  - Version number: 1.0.3+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/add-ons/plugin.video.tvvlaanderen
  
This add-on gives access to the live tv channels and the video-on-demand content available in your TV Vlaanderen subscription.

### Description of changes:

v1.0.3 (2021-02-04)
- Add HTTP Proxy support.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by Lunatixz** [comment]
PLS squash to a single commit, thx

**Comment by michaelarnauts** [comment]
> PLS squash to a single commit, thx

Oh sure, I'll do this. What's the difference between manually squashing or having GitHub do a squash and merge? I always do a squash and merge, bit maybe there's a difference?

**Comment by Lunatixz** [comment]
Repository maintenance responsibilities default to the submitter... As stated in the rules for this repository, a single commit is required.

**Comment by Lunatixz** [comment]
@michaelarnauts please check Travis error; the report indicates the Inputstream version required: 2.4.3, Available: 2.3.4

**Comment by michaelarnauts** [comment]
> @michaelarnauts please check Travis error; the report indicates the Inputstream version required: 2.4.3, Available: 2.3.4

I also see this in the CI pipeline of my add-ons. I think there is an issue with the mirrors, or the kodi-addon-checker. The latest version of IA for Leia is actually 2.4.5.

**Comment by michaelarnauts** [comment]
> @michaelarnauts please check Travis error; the report indicates the Inputstream version required: 2.4.3, Available: 2.3.4

Just noticed this is actually for Matrix. The latest version for IA on Matrix is even 2.6.7. I guess this has recently changed somehow in the addon-checker, since this was valid in the past just fine...

See https://github.com/xbmc/inputstream.adaptive/releases/tag/2.6.7-Matrix

**Pull request merged**
