### PR TITLE
[plugin.video.thinktv] Fixes for PBS update 3.0.14

### PR DESCRIPTION
**Pull request by brianjmurrell**
### Description
Update for changes to website.

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by learningit** [comment]
This is not the correct repo

**Comment by brianjmurrell** [comment]
> This is not the correct repo

So what is the correct repo?

**Comment by brianjmurrell** [comment]
@learningit When you updated your comment 4 minutes after I asked:

> So what is the correct repo?

you failed to answer that question.  So what is the correct repo that I should submit my PR against?

**Comment by Rechi** [comment]
In general only the author is allowed to push updates to this repo.
Submit your changes to the author of the plugin.

**Comment by brianjmurrell** [comment]
> Submit your changes to the author of the plugin.

If the author would say how he would like that done, I would.  But twice he has ignored my query about to where/how to submit.

**Comment by brianjmurrell** [comment]
And still, 7 hours later @learningit has not said where/how to submit my PR, yet he was right on closing out this issue within minutes of it being opened.

**Comment by enen92** [comment]
@brianjmurrell the source element in addon.xml clearly points to the upstream location of the code, in this case (https://github.com/learningit/repo-plugins). 
The kodi official repository just aggregates addons submitted and mantained by each individual developer - it is not the upstream location of all plugins. Generally devs develop iin their own individual repositories or forks of this repository (like in this case) and push changes to this repo when they are done. It is common to see newer versions of addons in those repos (and even shared via beta repositories) before they hit our repo. Generally we only allow updates to other developer addons when the original developer is MIA for a long time and another dev wants to take ownership over the maintenance of the addon (e.g. youtube plugin).
This is how we (and open-source in general) work. You basically have two options:

- Submit the changes to the proper repository, i.e. learningit repository identified above
- Fork the addon, use a different addon id and name and be responsible for mantaining that fork from now on.
Thanks for the submission

**Comment by brianjmurrell** [comment]
@enen92 Thank you for a most helpful response.

The one thing that I would say differs about this repo and typical open-source repos is the "two stop" nature of it.  That being that this repo is just an aggregation point and that there are other, separate repos to which contributions should go.

It might be worth documenting these details in a document that describes how to contribute to plugins.

**Comment by enen92** [comment]
@brianjmurrell it is written in the CONTRIBUTING document (https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) which is linked from the main README. I agree there is room for improving though. It is grouped in "Quick Kodi development links" and that may cause users to perceive it as a general coding manual. Thanks for the feedback.

**Pull request closed without merging**
