### PR TITLE
[plugin.video.iplayerwww] 3.0.14

### PR DESCRIPTION
**Pull request by primaeval**
### Description
Scraping fix. Hide Watched fix for Live Streams.
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
Please remove videolina license

**Comment by primaeval** [comment]
I have no idea how that got in there. Is this right?

**Comment by primaeval** [comment]
Are you sure about removing it because it is nothing to do with plugin.video.iplayerwww?

**Comment by enen92** [comment]
Don't modify it in any way. Add an upstream remote to your fork that points to xbmc/repo-plugins. Fetch the upstream repo and merge upstream/krypton before adding your files. See here:

https://help.github.com/articles/syncing-a-fork/

If you don't want to waste much time just redo a PR from scratch. It is also a good practice to create branches in your repo-scripts fork for each PR you make.

**Comment by primaeval** [comment]
I don't get this at all. If I make a new branch based on upstream/krypton I still end up with this license file in there.

**Comment by primaeval** [comment]
I'll start again.

**Comment by enen92** [comment]
The videolina license file is already part of the krypton branch (see: https://github.com/xbmc/repo-plugins/blob/krypton/plugin.video.videolina/LICENSE.txt) which means your fork is not synced with the upstream project.

The easiest way to fix this now is to start the process from scratch like explained in https://stackoverflow.com/a/9646323:

`git remote add upstream http://github.com/xbmc/repo-scripts`

`git fetch upstream`

`git checkout krypton`

`git reset --hard upstream/krypton`

`git push origin krypton --force `

Now create a new branch:

`git branch my-plugin && git checkout my-plugin`

Add your files and push to my-plugin branch:

`git push -u origin my-plugin` 

Regards
edit: I see you closed the PR but I'll leave this message anyway.

**Comment by primaeval** [comment]
Thanks. I made a new fork. Checked out that fork with the krypton branch and the license file still appears modified without me doing anything. Maybe its because I'm on Windows and there is some permission or file ending issue. I've just selected the files within this addon now so I'll try again.

**Pull request closed without merging**
