### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by Jonta**
### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by gade01** [comment]
The correct upstream repo is here:
https://github.com/XBMC-Addons/plugin.audio.radio_de

Description in be_by has been removed from addon.xml as it was a duplication of the source description:
https://github.com/xbmc/repo-plugins/pull/3728/files#diff-7a2f15b3026366ba4c1b9fa9a263fcbc30b07ea8b3ac8d95092ec8868c6c2608R44

https://github.com/XBMC-Addons/plugin.audio.radio_de/blob/matrix/addon.xml


You only have to change description of en_gb in addon.xml
But you should also change description for en_gb in all language files:
https://github.com/XBMC-Addons/plugin.audio.radio_de/tree/matrix/resources/language

Eg. https://github.com/XBMC-Addons/plugin.audio.radio_de/blob/matrix/resources/language/resource.language.af_za/strings.po#L25

If you would like to change the descriptions translations for en_au, en_nz and en_us you should do so at Weblate:
https://kodi.weblate.cloud/projects/kodi-add-ons-music/plugin-audio-radio_de/

**Comment by Jonta** [comment]
@gade01 I see 6 links, 1 of them free floating

Just give me the ones where I should make the changes. =)

**Comment by gade01** [comment]
@Jonta 
It should be changed for addon.xml:
https://github.com/XBMC-Addons/plugin.audio.radio_de/blob/matrix/addon.xml#L57

And for all language files:
https://github.com/XBMC-Addons/plugin.audio.radio_de/blob/matrix/resources/language/resource.language.af_za/strings.po#L25

**Comment by enen92** [comment]
This should be done via weblate. See:https://forum.kodi.tv/showthread.php?tid=364989&pid=3065219#pid3065219

**Pull request closed without merging**
