### PR TITLE
[plugin.video.uzg] v2.0.0

### PR DESCRIPTION
**Pull request by Opvolger**
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
If you will only keep supporting leia please mark the one in Gotham broken at some point

**Comment by Opvolger** [comment]
> If you will only keep supporting leia please mark the one in Gotham broken at some point

Gotham version still works. Can the two versions not coexist?
I do not think the api will change in the coming time. Only the subtitles have not been working for a while. But videos just work.
I wanted to update everything for python 3 compatibility. Then I have already solved that.

**Comment by MartijnKaijser** [comment]
Two version can surely exists as long as the one for Leia has a higher version number and you make sure the gotham one will never be bumped higher than what leia is.

**Comment by Opvolger** [comment]
> Two version can surely exists as long as the one for Leia has a higher version number and you make sure the gotham one will never be bumped higher than what leia is.


I'll keep an eye on that. I will release a version 1.3.2, which will support the new subtitles.

**Pull request merged**
