### PR TITLE
[plugin.video.iplayerwww] 1.2.0

### PR DESCRIPTION
**Pull request by CaptainTK**

### CODE REVIEW

**Comment by ronie** [comment]
thanx for submitting your addon the the repo!

i've reviewed the code and the only issue i found are the hardcoded strings in several places.
please ping me once those issues are addressed.

**Comment by CaptainTK** [comment]
Added translations for main menu entries and pop-ups as requested.

**Comment by ronie** [comment]
mind fixing the remaining one?
once you're done, please squash the commits and we should be good to go.

**Comment by CaptainTK** [comment]
Sorry, I can't get my hang around git. It just hates me. I will open a new pull request soon.

**Pull request closed without merging**
