### PR TITLE
plugin.video.youtube [5.5.0]

### PR DESCRIPTION
**Pull request by jdf76**
Updating Youtube Plugin from 5.4.5 to 5.5.0

### CODE REVIEW

**Comment by anxdpanic** [comment]
5.4.5 - 5.5.0 diff 

https://github.com/jdf76/plugin.video.youtube/compare/235b2ef822eaeceb40d2690cc16c2a688ac9c0af...24dc719fc31b79c8edd7705543e281ea947d6ade

**Comment by MartijnKaijser** [comment]
May I ask why this is added to Isengard branch which doesn't yet have a youtube version?

**Comment by anxdpanic** [comment]
moving from helix due to updated string paths requiring 15+

**Comment by MartijnKaijser** [comment]
5.4.5 is located in Helix branch.

**Comment by anxdpanic** [comment]
There is a 5.4.6 which is the last release there will be for helix, it's the same as 5.5.0 minus the string path change. I've reached out to jdf to see about the pr for that.

**Pull request merged**
