### PR TITLE
[plugin.video.itvrs] v0.0.1

### PR DESCRIPTION
**Pull request by remichie**
### Description
ITVRS offers movies and series, TV shows, cartoons, documentaries and shorts, and ITVRS broadcasts.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by remichie** [comment]
Hi @Rechi, My plugin has been waiting 7 days, Anything I can do to help? Thanks.

**Comment by remichie** [comment]
@Rechi, I will try to change the plugin.

**Comment by remichie** [comment]
@Rechi, Done the changes to the add-on, and the add-on is Python 3 compatible now.

**Comment by Rechi** [comment]
No it's still not Python 3 compatible.
`Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0` is also still violated.

**Comment by remichie** [comment]
@Rechi, you are a bit vague, don't really understand.

**Comment by remichie** [comment]
@Rechi, I ran the add-on on the latest nightly build and there were no problems.

**Comment by Rechi** [comment]
Your add-on is still not Python 3 compatible.
The PR now contains two add-ons, but only one per PR is allowed.
Also you still violate the following requirement.
> Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by remichie** [comment]
@Rechi, 

> Each add-on submission should be a single commit with using the following style: [plugin.video.foo] 
 v1.0.0

> 

What do you mean by this?

>Your add-on is still not Python 3 compatible.
The PR now contains two add-ons, but only one per PR is allowed.
Also you still violate the following requirement.
> 
I have deleted the other PR.
Why is my add-on not Python 3 compatible?
What am I violating?

**Comment by remichie** [comment]
@Rechi, Could you let me know what changes are requested.

**Comment by Rechi** [comment]
As already mentioned a few times, the add-on isn't Python3 compatible. If you don't know look up the differences between Python 2.7 and 3.*.

> Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0
If you look at https://github.com/xbmc/repo-plugins/pull/2408/commits you currently see 75 commits. There must be only one commit with the commit message mentioned above.

**Comment by remichie** [comment]
@Rechi, 

> As already mentioned a few times, the add-on isn't Python3 compatible. If you don't know what has to be changed, look up the differences between Python 2.7 and 3.*.
> 
That comment is useless, did not help at all! you as reviewer I would expect some useful help!

Will try to redo the add-on.

**Pull request closed without merging**
