### PR TITLE
[plugin.video.tv3.cat] v1.4.6

### PR DESCRIPTION
**Pull request by jqandreu**
### Description

Fixed web server changes
### Checklist:

- [ x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by enen92** [comment]
Please fix your pull request, you're including merge commits. Are you sure this is correct? You only deleted a log line

**Comment by jqandreu** [comment]
I just want to add the last commit v1.4.6 (8a22504). I dont know why are added the other commits. How can I fix it? Sorry, git is a little confusing to me

**Comment by enen92** [comment]
```
git checkout gotham
git remote add upstream git@github.com:xbmc/repo-plugins.git
git reset --hard upstream/gotham
git cherry-pick bd820c39ea0e76a826b7658cdc57c2557e6a5a45
git push -u origin gotham --force
```

**Comment by jqandreu** [comment]
Error with git cherry-pick command:

git cherry-pick bd820c39ea0e76a826b7658cdc57c2557e6a5a45

error: could not apply bd820c39e... [plugin.video.tv3.cat] 1.4.3
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

**Comment by enen92** [comment]
Just do a hard reset:
```
git checkout gotham
git remote add upstream git@github.com:xbmc/repo-plugins.git
git fetch upstream
git reset --hard upstream/gotham
```

And after that replace your addon files in the folder (plugin.video.tv3.cat) with the new version.
After that commit and push:

```
git commit -a -m "[plugin.video.tv3.cat] 1.4.6"
git push -u origin gotham --force
```

**Comment by jqandreu** [comment]
Yes, because one url has accents and caused error. I know could be a better solution but I have no time now and python is not my language

**Comment by jqandreu** [comment]
> ```
> git checkout gotham
> git remote add upstream git@github.com:xbmc/repo-plugins.git
> git fetch upstream
> git reset --hard upstream/gotham
> git cherry-pick bd820c39ea0e76a826b7658cdc57c2557e6a5a45
> git push -u origin gotham --force
> ```

Fixed to the last commit. Thanks

**Comment by jqandreu** [comment]
> You only removed a logging line?

Yes. Some urls have accents now and this line caused errors. Incomplete listing of programas

**Pull request merged**
