### PR TITLE
[plugin.video.viaplay] 1.0.7.1

### PR DESCRIPTION
**Pull request by emilsvennesson**
### Description
* Update for Krypton
* Fix stream URL retrieval
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
Plugin looks okay, however you have another version in jarvis ( https://github.com/xbmc/repo-plugins/tree/jarvis/plugin.video.viaplay ). Is this older version to deprecate or remove? Or did you submit this one to the wrong branch?

**Comment by phil65** [comment]
since roadmap contains
- MPEG-DASH support using inputstream.adaptive
it probably makes sense to have a separate krypton version.

**Comment by emilsvennesson** [comment]
@enen92 I've decided to drop support for Jarvis, so I'd like 1.0.6 to be the last version available for that Kodi version.

**Comment by enen92** [comment]
okay, nice to know :)

I don't think that versioning is allowed according to addon.xml in the wiki ( This should be use a version scheme like x.y.z (major.minor.patch). )

Also, for the future you might be interested in knowing this: https://github.com/xbmc/generator-kodi-addon/issues/11

**Comment by MartijnKaijser** [comment]
@emilsvennesson are you requiring MPEG-DASH or is it optional? If required you can add it as import to addon.xml

**Comment by emilsvennesson** [comment]
@MartijnKaijser I'm not using MPEG-DASH yet. I'll definitely add in it addon.xml once I've added support for it. :-)

@enen92 Thanks! I'll make sure to fix that for the next version.  I was hoping the versioning scheme would be fine. It'd be annoying to issue yet another release. :-/

**Pull request merged**
