### PR TITLE
[plugin.video.twit] 2.1.5

### PR DESCRIPTION
**Pull request by divingmule**
This update is a workaround for a SSL bug in Python < v3.2, thus the hard coded shows.py file. Luckily that info doesn't change very often.

Thanks!

### CODE REVIEW

**Comment by learningit** [comment]
The current version of twit.tv is in the Jarvis repo, but you want to commit this to Helix?

**Comment by divingmule** [comment]
Humm... I'm not seeing it in Jarvis.  I'm finding the last version in Gotham. Some info label stuff changed with Helix that is why I wanted to move it there.

**Comment by learningit** [comment]
I saw it wasn't in Helix and checked here http://addons.kodi.tv/show/plugin.video.twit/ which has 2.1.3 in Jarvis.

**Comment by learningit** [comment]
Nevermind, it's in both gotham and jarvis. Ok so I'll update into Helix.

**Comment by divingmule** [comment]
Thanks!

**Comment by learningit** [comment]
Damn, I was too quick to merge. In addon.xml xbmc.python needs to be set to 2.19.0 for Helix. Please fix this as it will mess up folks who direct download and install on Gotham.

**Pull request merged**
