### PR TITLE
New Matrix addon 

### PR DESCRIPTION
**Pull request by jbinkley60**
### Description
Initial new Kodi Matrix addon service.autostop submission.
An addon for Kodi (XBMC) which monitors video and music playback. It allows users to selectively stop paused playback or stop current playback after a certain amount of time.

### Checklist:
- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by basrieter** [comment]
Please create a PR with the correct naming and against the `matrix` branch, not `master`. See https://kodi.wiki/view/Submitting_Add-ons.

I guess closing this one and creating a new one is the easiest way?

**Comment by lrusak** [comment]
> Please create a PR with the correct naming and against the `matrix` branch, not `master`. See https://kodi.wiki/view/Submitting_Add-ons.
> 
> I guess closing this one and creating a new one is the easiest way?

I've changed the base branch but looks like it still needs some work.

EDIT: well I tried but I get `There are no new commits between base branch 'matrix' and head branch 'matrix'`

**Comment by jbinkley60** [comment]
Still learning how to do pull requests.

**Comment by basrieter** [comment]
Np, we've all been there.

**Comment by jbinkley60** [comment]
I presume by correct naming you mean the name of the addon, service.autostart ?    I had submitted a question on the forum and hadn’t gotten a response yet, asking for guidance on naming.

 

See:   <https://forum.kodi.tv/showthread.php?tid=364690> https://forum.kodi.tv/showthread.php?tid=364690

 

If this is the issue I can change it to my second option:  

 

plugin.video.autostop

 

but Kodi is dropping it into the service category.

 

Jeff

**Pull request closed without merging**
