### PR TITLE
[plugin.video.pcloud-video-streaming] 1.2.10

### PR DESCRIPTION
**Pull request by gdomenici**
### Description
Version 1.2.10
Fixed issue #17: if a folder contained a large amount of files (typically, 500+), its contents could not be shown.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by gdomenici** [comment]
> Please squash commits for merging

Hi @enen92 . I'm sorry but I am not sure how to do it at this point... do i need to close this PR and open a new one after squashing the commits?

**Comment by enen92** [comment]
- Run `git rebase -i HEAD~3`
You should see a list of commits, each commit starting with the word "pick".
Make sure the first commit says "pick" and change the rest from "pick" to "squash". -- This will squash each commit into the previous commit, which will continue until every commit is squashed into the first commit.
- Save and close the editor.
It will give you the opportunity to change the commit message.
- Save and close the editor again.
- Then you have to force push the final, squashed commit: git push -f

**Comment by enen92** [comment]
did you change `pick` to `squash`? You now have 4 commits instead of 3. Goal is to have only one :)

**Comment by gdomenici** [comment]
> did you change `pick` to `squash`? You now have 4 commits instead of 3. Goal is to have only one :)

I did :) but clearly something got mixed along the way. In my own repo now I do see only 1 commit (https://github.com/gdomenici/plugin.video.pcloud-video-streaming/commits/master). But I do see that in repo-plugins there's indeed 4.

Now I think I know where I went wrong -- I should have done the squash directly on my fork of repo-plugin. Will try again that way and fingers crossed...

**Pull request merged**
