### PR TITLE
[plugin.video.nhklive] v3.0.8

### PR DESCRIPTION
**Pull request by bigretromike**
### Description

NHK Live stopped working because page has changed, this is fix to make it work again.
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by bigretromike** [comment]
> 
> ## Travis tests were successful
> 
> Hey @bigretromike,
> we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

where is `that` logfile ?;-) please tell me bot

**Comment by enen92** [comment]
@bigretromike t1m is not around anymore (not sure if he still maintains his add-ons). Have you tried to bring the change upstream? If so, and if you got no response, please add yourself to the authors list too

**Comment by enen92** [comment]
Also future updates will need to by python3 compatible, if possible try to also run the add-on in a python3 enabled Kodi build to see if the add-on needs further changes.
Thanks a lot

**Comment by bigretromike** [comment]
@enen92 I tried to push them to upstream but he wipe his repositories and this is only place where I was able to get this. I don't need a credits for debugging and changing 1 character to make this work. 
Last time I check python3 builds are not available, but I hope this plugin wont have to be maintain that much. isengard was tagged as still to allow updates, so I pushed mine.
Strange that he is no more, because I recall reading his post on forum, maybe they were old. If anything breaks more I will know - because I use this plugin, so if there will be need I will PEP8, python3 compile and then I will credit my self. 
Will you merge it here then ?

**Comment by enen92** [comment]
Can you just change the upstream source to your account and change the `<source>` in addon.xml with this change. It's temporary till we decide where to move this plugin upstream repo.
Thanks

**Comment by bigretromike** [comment]
are you asking me to change `<source>` to https://github.com/bigretromike/repo-plugins ?
What would be the point of it when I delete that fork as soon as this merge is done, how would that help any one. I think that until the new upstream is decide the old source link is ok, this way people still now that the plugin is semi dead and someone need to do something about it.

But if you really want me to add my forked repo (`https://github.com/bigretromike/repo-plugins`) then I will do that, no issue with it.

**Comment by enen92** [comment]
Leave it as it is then, we'll decide what to do with it later

**Comment by bigretromike** [comment]
@enen92 thanks for merge. As a side note, if there wont any one that could take this plugin, I'm willing to maintain this in my free time, just so it will work as long as possible. 
As a token of gratitude for all your hard work, and helping out with many issues that I post on gh.

**Pull request merged**
