### PR TITLE
[plugin.video.zdf_de_lite] v3.1.0

### PR DESCRIPTION
**Pull request by prof-membrane**
### Description
This is an update for the "ZDF Mediathek". It supports the brand new website at www.zdf.de.

It is dependent on the libMediathek script.

I hope I did everything right with this pr. I will push my other add-ons if this goes well.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by Tadly** [comment]
`strings.xml` is deprecated and you should be using `strings.po`
http://kodi.wiki/view/language_support#Layout_of_the_strings.po_file

**Comment by prof-membrane** [comment]
I'm already on it ;).

**Comment by Razzeee** [comment]
@prof-membrane 
You should have gotten an email form us or a pm on your kodi.tv forum account, can you please check that?

**Comment by prof-membrane** [comment]
Nope. No mail, no pm. Do you have the right user name (http://forum.kodi.tv/private.php?action=send&uid=89843)?

BTW: this PR is currently on hold. I'll have to clean up some things before continuing.

**Pull request closed without merging**
