### PR TITLE
[plugin.audio.absolute-radio] v1.0.0

### PR DESCRIPTION
**Pull request by PhantomRaspberryBlower**
### Description
Kodi Addon for listening to Absolute Radio live broadcasts

Absolute Radio is one of the UK's Independent National Radio stations. The station is based in London and plays popular rock music broadcasting on medium wave and DAB across the UK (105.8 FM in London and 105.2 FM in the West Midlands). It is also available in other parts of the world via satellite, cable, and on the Internet.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by PhantomRaspberryBlower** [comment]
I am new to creating pull requests to Kodi from Git. I have a repository with an addon [plugin.audio.absolute-radio] v1.0.0 and don't know if I have successfully commited the addon. Any help would be greatly appreciated.

**Comment by PhantomRaspberryBlower** [comment]
I am new to creating pull requests to Kodi from Git. I have a repository with an addon [plugin.audio.absolute-radio] v1.0.0 and don't know if I have successfully commited the addon. Any help would be greatly appreciated.

**Comment by Lunatixz** [comment]
@PhantomRaspberryBlower this commit only contains document changes was this your intention? 
If so please withhold document PR's unless the information is vital to the operation of the plugin and/or is Licence related. Otherwise commit document changes when it's time to update the code.

If however you are having issues creating PR's let me know and i'll try my best to help.

**Comment by PhantomRaspberryBlower** [comment]
@Lunatixz thanks for responding. No it was not my intention to only commit document changes. I have a new addon I'm trying to include in the Krypton branch of the Kodi repo (xbmc/repo-plugins). I have created a fork of repo-plugins and included the files belonging to my addon (plugin.audio.absolute-radio). Do I then create a pull-request and wait for the changes to be merged. Or am I going about this in totally the wrong way? Like I said I am a complete novice when using git and creating pull requests.

**Comment by Lunatixz** [comment]
Here is a forum thread with helpful information, if you need specifcs post in this thread. https://forum.kodi.tv/showthread.php?tid=292525

**Comment by PhantomRaspberryBlower** [comment]
I seem to have a conflict in the README.md file of my repo-plugins fork. I haven't changed anything in this file and don't know how to rectify this conflict. When I created the pull request I used the GitHub UI instead of the command line. Would it be better to close this pull request, delete the fork from my PC and try again using the command line as described in the link above that Lunatixz provided? One other question: if I am successful in pushing my addon to the official xbmc\repo-plugins how long should it take to know that everything has worked and it appears in the official Kodi repo? Is this instant or is there an appraisal period?  I apologize for my lack of understanding, it isn't my intention to waste anybodies time.

**Comment by Lunatixz** [comment]
@PhantomRaspberryBlower it looks like you might be trying to commit your master branch to the krypton branch. It will be easier for me to explain the process at the kodi forums, This way it could help others in your same situation.

**Comment by PhantomRaspberryBlower** [comment]
Thanks I will join the Kodi forum, See you on the other side :)

**Comment by PhantomRaspberryBlower** [comment]
@Lunatixz I have tried to join the Kodi Forum so that I can get this addon included but alas as you are probably aware the forum server has been having technical issues since the server started it's migration and has been off-line for the last 6 days. This is just a heads-up to let you know that I haven't abandoned these posts. Looking forward to resolving this ASAP.

**Comment by Lunatixz** [comment]
@PhantomRaspberryBlower thanks, while you wait; can you close this commit. We will probably end up starting a new PR anyway. THX

**Pull request closed without merging**
