### PR TITLE
[plugin.video.worldstarcandy] 1.0.0

### PR DESCRIPTION
**Pull request by skipmodea1**

### CODE REVIEW

**Comment by phil65** [comment]
I am not sure if we allow tits-and-asses content. @ronie, do we have a guideline for stuff like this?

**Comment by ronie** [comment]
nope, nothing written in stone afaik.
i don't recall anyone ever submitted an adult content addon before.

i'd prefer to keep our addon repo suitable for all ages ;-)

**Comment by skipmodea1** [comment]
Just to be clear here, the kodi-team does not allow an addon with adult content in the kodi repo?

**Comment by phil65** [comment]
Correct.

**Comment by skipmodea1** [comment]
Right. Closing the PR.

**Pull request closed without merging**
