### PR TITLE
[plugin.video.youtube@matrix] 7.0.6.2

### PR DESCRIPTION
**Pull request by anxdpanic**
### Add-on details:

- **General**
  - Add-on name: YouTube
  - Add-on ID: plugin.video.youtube
  - Version number: 7.0.6.2
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/anxdpanic/plugin.video.youtube
  
YouTube is one of the biggest video-sharing websites of the world.

### Fixed
- Improve updating containers and (re)loading windows
- Fix refreshing video listing also forcing next pages to refresh when loaded
- Fix overflow error resulting from parsing hashtags as episode numbers
- Fix 6s delay on video playback start
- Further fixes for multiple busy dialog crash workaround
  - Possibly fix issues reported in comments of
- Update error checks to avoid unnecessary retries of player requests
- Fix adding and viewing items to internal bookmarks and watchlater list
- Fix error checks to prevent prematurely stopping retries of player requests

### Changed
- Setup Wizard default settings now disable pre-downloading subtitles if MPEG-DASH is enabled
- Ask for quality, Play with subtitles, Play audio only context menu items only displayed if associated setting is not already enabled
- Only make extra request for subtitles for Android client when all subtitle languages are enabled
- Overhaul alternative player support due to Kodi changes and also improve external player support
- Make "Support alternative player" and "Use YouTube website urls with default player" mutually exclusive options
- Enable OPUS audio by default
- Enable MPEG-DASH for live streams by default
- Setup Wizard will prompt to run when plugin first opens after updating, in order to update default settings
- http server will shutdown on idle timeout
- Update client details used for player requests

### New
- Add recommended settings in Setup Wizard for Raspberry Pi 1/2 

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by MoojMidge** [comment]
Please don't review/merge this just at the moment. More recent Youtube shenanigans are ongoing and minor update to this PR is required.

**Comment by basrieter** [comment]
> Please don't review/merge this just at the moment. More recent Youtube shenanigans are ongoing and minor update to this PR is required.

Can you mark it as `Draft Pull Request`?

**Comment by MoojMidge** [comment]
Might be easier to just close and re-open a new one. Unless someone has already started looking at it?

**Comment by basrieter** [comment]
Np, I will close it for now.

**Pull request closed without merging**
