### PR TITLE
[plugin.video.zeemarathi] 0.0.3

### PR DESCRIPTION
**Pull request by virajkanwade**
Isengard

### CODE REVIEW

**Comment by virajkanwade** [comment]
For some reason, i am unable to find my plugins on kodi running isengard

**Comment by MartijnKaijser** [comment]
well they certainly are there.

**Comment by virajkanwade** [comment]
Ok. Will check. Thanks.

To confirm, if I submit a plugin to helix, it will be available for all versions? or only later?

I will update the wiki http://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging accordingly.

**Comment by MartijnKaijser** [comment]
didn't even know the page was there.
Yes if you submit to helix, Kodi pulls the info and makes it available to Helix and later

**Comment by virajkanwade** [comment]
Updated docs.

**Pull request closed without merging**
