### PR TITLE
[plugin.video.ted.talks] 4.2.11

### PR DESCRIPTION
**Pull request by skipmodea1**
### Description
[B]Version 4.2.11[/B] (Skipmode A1: It seems the developer moreginger isn't active anymore :/. Therefore i made this version.)
Fixed video playback (json changed in website)
Fixed subtitles (json changed in website)
Fixed thumbnails (resizeImage method fubared the thumbs)

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Why that ugly icon image?

**Comment by skipmodea1** [comment]
No idea,  it was something that was added in 4.2.10 i think

**Comment by MartijnKaijser** [comment]
Can you put back the original icon or replace it with a high resolution version. Also the svg file can go I guess

**Comment by skipmodea1** [comment]
Ok, i'll make a new pr.

**Pull request closed without merging**
