### PR TITLE
[plugin.video.bcf] 1.0.2

### PR DESCRIPTION
**Pull request by FraserChapman**
### Description

Fixes unplayable news items - plus housekeeping 

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by Rechi** [comment]
@FraserChapman this add-on isn't Python 3 compatible. Future updates have to be compatible with Python 3.
Have a look at https://kodi.tv/article/attention-addon-developers-migration-python-3 for more information.

**Comment by FraserChapman** [comment]
@Rechi - thanks for that - OOI what is the incompatibility issue with Python 3? I had endeavoured to code the plugin so it was 2/3 compatible...When I run a code inspection with Python 3.7 in Pycharm the only thing it flags are the unresolved references to the xbmc modules, etc - plus a weak warning about PEP 8 naming convention  on the CamelCase to lower case import in the cache.  

Unfortunately I don't have access to a win/linux box ATM to run the test builds of Kodi 18.

**Comment by Rechi** [comment]
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
   Error Type: <class 'TypeError'>
   Error Contents: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
   Traceback (most recent call last):
     File "<...>\plugin.video.bcf\main.py", line 3, in <module>
       from resources.lib import plugin
     File "<...>\plugin.video.bcf\resources\lib\plugin.py", line 13, in <module>
       from resources.lib import search as bcfs
     File "<...>\plugin.video.bcf\resources\lib\search.py", line 12, in <module>
       from .cache import Cache, datetime_to_httpdate
     File "<...>\plugin.video.bcf\resources\lib\cache.py", line 19, in <module>
       kodilogging.config()
     File "<...>\plugin.video.bcf\resources\lib\kodilogging.py", line 42, in config
       logger.addHandler(KodiLogHandler())
     File "<...>\plugin.video.bcf\resources\lib\kodilogging.py", line 16, in __init__
       prefix = b"[%s] " % addon_id
   TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
   -->End of Python script error report<--
```

**Comment by FraserChapman** [comment]
@Rechi  Many thanks again :)

**Pull request merged**
