### PR TITLE
[plugin.video.slice.canada] 3.0.1

### PR DESCRIPTION
**Pull request by learningit**
New video addon for Slice Canada

### CODE REVIEW

**Comment by phil65** [comment]
might be worth redoing the icon based on fanart? quality of the icon atm looks quite bad.

**Comment by phil65** [comment]
...and one thing i forgot: (applies to all plug-ins): strings.xml is the outdated way for localizing add-ons, it is now recommended to use .po files.

**Comment by learningit** [comment]
With or without the redo the icon is butt-ugly.
I need to read up on the .po files, haven't used them yet. These 3 add-ons(slice, showcase, etcanada) would be good for that as Canadians do things bilingually.

**Comment by phil65** [comment]
There  is some tool available somewhere which converts  the xml files to po files.... Would have to searcch for it though.

**Comment by learningit** [comment]
Don't bother. I want to understand how they work. These add-ons have very limited use of language strings anyway.

**Comment by MartijnKaijser** [comment]
How they work is basically the same as the xml but just in different format. http://kodi.wiki/view/Language_support#Layout_of_the_strings.po_file

In Isengard we also changed folder layout for language with backwards compatibility. 
We now use the ISO code in the folder names. https://github.com/xbmc/xbmc/tree/master/addons/skin.estuary/language as example

**Pull request merged**
