### PR TITLE
[plugin.video.iplayerwww] 2.4.0

### PR DESCRIPTION
**Pull request by CaptainTK**

### CODE REVIEW

**Comment by CaptainTK** [comment]
@learningit it looks to me like something has gone wrong with this PR. I am trying to create a new PR for 2.4.1 from my fork, but it tells me there is a merge conflict. Basically, GitHub doesn't seem to be aware that you already merged this and I would get a PR with two commits (2.4.0 and 2.4.1).

Can you please check if you can see any problems?

**Comment by learningit** [comment]
I think you can one of two things: create the branch for your new PR from the previous branch for 2.4.0 (if you haven't deleted it) or do a rebase against the xbmc/repo-plugins to bring your branch up to date with the repo. Let me know if you have more questions

**Comment by CaptainTK** [comment]
Actually, I just updated the branch using subtree merging as always (and as described in the [How-To](http://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging). It always worked flawless. Until this time.

Rebase doesn't work because of some stupid CRLF/LF conflict in a totally unrelated file so it looks like I need to delete the whole fork and fork again.

**Comment by CaptainTK** [comment]
Sorted it out and created a new PR for 2.4.1. Thanks for your help.

**Pull request merged**
