### PR TITLE
[plugin.video.tv3play.dk] v3.0.1: Updated to using the new MTGx API

### PR DESCRIPTION
**Pull request by anorm**
The API to access the data has been completely changed by MTG (the owner of TV3 play). This new version, uses the new MTGx API.

### CODE REVIEW

**Comment by phil65** [comment]
please just addon id and version number as commit message.

**Comment by anorm** [comment]
Ah sorry. Do you want me to close this ånd create a new PR?

**Comment by phil65** [comment]
you can just update the  current PR by force-pushing to same branch.

**Comment by anorm** [comment]
Will do

**Comment by anorm** [comment]
OK, done

**Comment by phil65** [comment]
thx. code looks fine to me.

**Pull request merged**
