### PR TITLE
[plugin.video.intergalacticfm] 2.3.0

### PR DESCRIPTION
**Pull request by dromer**
### Description
Version 2.3.0
Added Austin Cassel and The Dream Machine
Temp disable YouTube channels (needs API key)

Version 2.2.0
Added IFM and Viewlexx YouTube channels

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by dromer** [comment]
Hmm, I'm not sure what the conflicts on these files are.

Will investigate.

**Comment by PanderMusubi** [comment]
@MartijnKaijser can you help us out what could be the cause of this?

**Comment by enen92** [comment]
Please rebase on top of the current state of the krypton branch

**Comment by dromer** [comment]
This is odd, because I did a `git pull origin` before I made this commit.

**Pull request closed without merging**
