### PR TITLE
[plugin.video.youtube] 5.2.1

### PR DESCRIPTION
**Pull request by jdf76**

### CODE REVIEW

**Comment by Razzeee** [comment]
This PR looks okay, from the commit/branch etc.
Haven't looked into the code, as you closed it directly.

**Comment by jdf76** [comment]
hrm weird, i’m sorry about that. I’ll resubmit. 

Thanks for the help.

Jeff

**Comment by jdf76** [comment]
ok i resubmitted. I apologize again for the inconvenience. If this is all correct. I’ll document it for me and my group.

Thanks again!

Jeff

**Comment by Razzeee** [comment]
If you can put your finger on why it's difficult for you, please let us know, so that we can update the documentation accordingly.

**Comment by jdf76** [comment]
Absolutely. I think i had trouble because i wasn’t sure exactly what to do. I’ll document how i did it. I appreciate you guys helping me through this process.

Jeff

**Pull request closed without merging**
