### PR TITLE
 Fix files with incorrect CRLF line-endings

### PR DESCRIPTION
**Pull request by dagwieers**
### Description
Without this fix my git is always complaining about changes to these files
that I did not touch. Because of a bug in git you are no longer able to
pull/rebase, and this issue cannot be stashed or fixed except by
modifying .gitattributes.

### CODE REVIEW

**Comment by basrieter** [comment]
I think you should report this to the original dev (I think it is @CaptainTK) of the add-on, as he/she would just push the original file back again with the next update.

**Comment by CaptainTK** [comment]
What exactly is the issue with the file, @dagwieers ? Line endings?

In any case, please create a PR for the add-on itself: https://github.com/vonH/plugin.video.iplayerwww/tree/krypton.

**Comment by dagwieers** [comment]
The problem is that (probably because of the git version of my system) git thinks the file is modified from the one in HEAD (because the line-endings are incorrect to what git is configured to do), but I cannot stash it and I cannot reset it. And it blocks everything. I can't update my master branch, or any branch for that matter. And I always have to restart from a fresh clone. Which is stupid.

I guess that this Git-specific issue is the reason why the rules of this repositories demands normalized (LF) line endings. (cfr. `.gitattributes`). Also *plugin.video.psvue/resources/lib/sony.py* has the same problem now.

I can also remove this entry from `.gitattributes` but I guess it is there for a reason.

**Comment by dagwieers** [comment]
There is even more, but my Git has not complained about these:
```
[dag@moria xbmc-repo-plugins]$ find . -type f -exec file {} \; | grep 'CRLF'
./plugin.video.ad6/addon.xml: XML 1.0 document, ASCII text, with CRLF line terminators
./plugin.video.ad6/changelog.txt: ASCII text, with CRLF line terminators
./plugin.video.ad6/main.py: Python script, ASCII text executable, with CRLF line terminators
./plugin.video.ad6/resources/lib/kodilogging.py: Python script, ASCII text executable, with CRLF line terminators
./plugin.video.ad6/resources/lib/kodiutils.py: Python script, ASCII text executable, with CRLF line terminators
./plugin.video.ad6/resources/lib/plugin.py: Python script, ASCII text executable, with CRLF line terminators
./plugin.video.ad6/resources/settings.xml: XML 1.0 document, ASCII text, with CRLF line terminators
./plugin.video.eurosportplayer/resources/language/resource.language.de_de/strings.po: GNU gettext message catalogue, UTF-8 Unicode text, with CRLF line terminators
./plugin.video.eurosportplayer/resources/language/resource.language.en_gb/strings.po: GNU gettext message catalogue, ASCII text, with CRLF line terminators
./plugin.video.eurosportplayer/resources/settings.xml: XML 1.0 document, ASCII text, with CRLF line terminators
./plugin.video.hrmagplayer/resources/language/resource.language.en_gb/strings.po: GNU gettext message catalogue, ISO-8859 text, with CRLF line terminators
./plugin.video.hrmagplayer/resources/settings.xml: XML 1.0 document, ASCII text, with CRLF line terminators
./plugin.video.iplayerwww/changelog.txt: ASCII text, with CRLF line terminators
./plugin.video.psvue/resources/lib/sony.py: C++ source, ASCII text, with CRLF line terminators
```

**Comment by dagwieers** [comment]
@CaptainTK The newline requirements are specific to this repository, they are not a requirement on upstream repositories. It actually should be a sanity check to this repository.

**Comment by dagwieers** [comment]
Example, of how this issue completely locks me into a specific branch with no way to recover except removing the complete clone, and starting from scratch.
```
[dag@moria xbmc-repo-plugins]$ git status
# On branch plugin.video.vrt.nu-2.2.0
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   plugin.video.psvue/resources/lib/sony.py
#
no changes added to commit (use "git add" and/or "git commit -a")
[dag@moria xbmc-repo-plugins]$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	plugin.video.psvue/resources/lib/sony.py
Please, commit your changes or stash them before you can switch branches.
Aborting
[dag@moria xbmc-repo-plugins]$ git checkout -- plugin.video.psvue/resources/lib/sony.py
[dag@moria xbmc-repo-plugins]$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	plugin.video.psvue/resources/lib/sony.py
Please, commit your changes or stash them before you can switch branches.
Aborting
[dag@moria xbmc-repo-plugins]$ git stash
Saved working directory and index state WIP on plugin.video.vrt.nu-2.2.0: 3ed917f [plugin.video.vrt.nu] 2.2.0
HEAD is now at 3ed917f [plugin.video.vrt.nu] 2.2.0
[dag@moria xbmc-repo-plugins]$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	plugin.video.psvue/resources/lib/sony.py
Please, commit your changes or stash them before you can switch branches.
Aborting
[dag@moria xbmc-repo-plugins]$ git reset -- plugin.video.psvue/resources/lib/sony.py
Unstaged changes after reset:
M	plugin.video.psvue/resources/lib/sony.py
[dag@moria xbmc-repo-plugins]$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	plugin.video.psvue/resources/lib/sony.py
Please, commit your changes or stash them before you can switch branches.
Aborting
[dag@moria xbmc-repo-plugins]$ git stash
Saved working directory and index state WIP on plugin.video.vrt.nu-2.2.0: 3ed917f [plugin.video.vrt.nu] 2.2.0
HEAD is now at 3ed917f [plugin.video.vrt.nu] 2.2.0
[dag@moria xbmc-repo-plugins]$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	plugin.video.psvue/resources/lib/sony.py
Please, commit your changes or stash them before you can switch branches.
Aborting
```

**Comment by dagwieers** [comment]
And to give you an example of how I get into this state, just clone the repository and switch to the **krypton** branch:
```
[dag@moria home-made]$ rm -rf xbmc-repo-plugins/
[dag@moria home-made]$ git clone git@github.com:xbmc/repo-plugins.git xbmc-repo-plugins
Cloning into 'xbmc-repo-plugins'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 78128 (delta 1), reused 0 (delta 0), pack-reused 78123
Receiving objects: 100% (78128/78128), 745.99 MiB | 16.57 MiB/s, done.
Resolving deltas: 100% (31248/31248), done.
[dag@moria home-made]$ cd xbmc-repo-plugins/
[dag@moria xbmc-repo-plugins]$ git checkout krypton
Branch krypton set up to track remote branch krypton from origin.
Switched to a new branch 'krypton'
[dag@moria xbmc-repo-plugins]$ git checkout -b fix-ipplayerwww-changelog
M	plugin.video.psvue/resources/lib/sony.py
Switched to a new branch 'fix-ipplayerwww-changelog'
```

**Comment by dagwieers** [comment]
Oh no, some of these files no longer comply to the rules :-(

**Comment by dagwieers** [comment]
Can we please get this merged, despite the errors, as these are a problem with the current tree anyway? And then add a new check for incorrect CRLF files?

**Comment by enen92** [comment]
Please send the fixes upstream. Only the original author is allowed to push changes for the addon, unless it gets unmaintained and someone else takes over the development.

**Comment by dagwieers** [comment]
Why would the upstream repositories care about CRLF if this repository does not enforce it.
We better disable the forced LF in this repository that is causing these issues then.

**Comment by CaptainTK** [comment]
Because only complete releases are merged here, not single commits on files. I really don't care about line endings. If it helps you, I'll be happy to merge it upstream and include in the next release. However, merging here - especially in the way you ask for - just does not work.

**Comment by basrieter** [comment]
I think @enen92 already asked for this to be fixed upstream and then to be PR-ed here. That can be done with the next release.

**Comment by dagwieers** [comment]
I don't think anyone really understands the problem and the impact this has.
https://stackoverflow.com/questions/19151789/git-complains-about-randomly-changed-files-when-switching-branches

**Comment by dagwieers** [comment]
It currently has to be fixed for 5 add-ons in the Krypton branch, and potentially more in the Leia branch, and it will not prevent a similar problem in the future. So I don't think fixing without enforcing it makes any sense TBH. It's better to disable the cause from .gitattributes IMO.

**Pull request closed without merging**
