### PR TITLE
[plugin.video.plutotv] 1.0.0

### PR DESCRIPTION
**Pull request by Lunatixz**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by learningit** [comment]
Please squash these into a single commit. Pain to review in separate commits.

**Comment by Lunatixz** [comment]
I've never been able to squash/merge, something about write permission? but @enen92 told me from his end he can squash/merge b4 committing. Maybe he can help?

**Comment by learningit** [comment]
Did you try this?
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

Personally I won't review anything with multiple commits. Difficult to comment on and a pain even looking at the summary changes, it's not always right. Easiest thing is to have a dev squash. never heard of write permission issues for a squash.

**Comment by Lunatixz** [comment]
I understand, in the past team members squashed for me... I've tried rebasing, and a bunch of force merges... probably an issue on my end, in the past i've done some damage using git shell =)

How are you reviewing, via browser? because if you click "file changed" there is a option to review all changes, ie all commits at once.

**Comment by learningit** [comment]
I'll pass on this, someone else can review.

**Comment by Lunatixz** [comment]
@learningit okay...

**Comment by Lunatixz** [comment]
Need to deal with playlist foreground issue, i'll fix and resubmit.

**Pull request closed without merging**
