### PR TITLE
[plugin.video.putiov2] deprecate

### PR DESCRIPTION
**Pull request by igungor**
This plugin is broken and deprecated. plugin.video.putio can be used instead.

### CODE REVIEW

**Comment by Razzeee** [comment]
Well if it already has a broken tag, it's already marked as broken. So this will only change the broken message. Why exactly are you trying to remove this?

**Comment by igungor** [comment]
plugin.video.putio is maintained by the put.io team. putiov2 is not maintained anymore and causes confusion for put.io users. it'd be nice to nuke it completely.

**Comment by Razzeee** [comment]
It should show up as broken in every addon browser frontend. 

CC @tamland

**Comment by tamland** [comment]
Yeah, this change doesn't make any sense.. It just changes the message. It's already not installable and users who had it installed have already been notified.

Since it was marked broken in january, I think it should be fine to remove completely now.

**Comment by igungor** [comment]
Yeah, the intention was to remove the plugin completely from this repo, even though the commit doesn't make sense.

**Comment by cenk** [comment]
Is it possible to remove the old and broken plugin please? It confuses some users.

**Comment by phil65** [comment]
Could you update the PR to remove the add-on completely? @tamland already stated that a removal is fine in this case.

**Comment by igungor** [comment]
Already done that but closed due to removing is a 'no-go'. https://github.com/xbmc/repo-plugins/pull/454

Just re-opened the previous PR for you.

**Comment by Razzeee** [comment]
@igungor sorry for that, wasn't aware, that it was already set as broken

**Comment by tamland** [comment]
done

**Comment by igungor** [comment]
thanks!

**Pull request closed without merging**
