### PR TITLE
[plugin.program.AML] 0.9.9

### PR DESCRIPTION
**Pull request by Wintermute0110**
### Description

Version 0.9.9 of Advanced MAME Launcher. Diff looks huge because a code refactoring/cleaning, but the number of new features is not that big. Please have a look at the changelog.txt for a detailed list of new additions to this version.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Wintermute0110** [comment]
I will try to remove as much travis warnings as possible and rebase everything into one commit.

**Comment by Wintermute0110** [comment]
OK, I got rid of all Travis errors and most warnings. Some notes:

  1) I'm using Windows Tortoise Git. I know how to merge several commits into one, but I don't know how to get rid of the commit `Merge pull request #1 from xbmc/krypton`. I need help.

  2) I am aware of the policy that addons submitted to Leia **must** be Python2 and 3 compatible. However, AML is a huge addon and what I want to do is to update the Krypton version, which is Leia compatible, and then when M**** is released I will do a total conversion from Python 2 to Python 3.

    Actually, AML and AEL already are quite Pyhton 3 ready (for example, by using `from __future__ import unicode_literals`, using exclusively string.format(), etc.). Implementing some of the Travis suggestions will may incur on a huge performance penalty, for example, converting dic.iteritems() to dic.items() in Python 2 will return lists instead of iterators. In AML these list can be huge.

**Comment by Rechi** [comment]
To fix your pull request execute the following commands (origin is your repo, upstream is the xbmc repo)

```
git fetch upstream
git checkout plugin.program.AML-0.9.9
git reset --hard upstream/krypton
git checkout origin/plugin.program.AML-0.9.9 -- plugin.program.AML/
git commit -m '[plugin.program.AML] 0.9.9'
git push -f origin plugin.program.AML-0.9.9
```
\
I'm aware that some of the fixes reported only as INFO may decrease performance and are not always required for Python3 compatibility. As those are only infos, they do not cause a CI failure.

**Comment by Wintermute0110** [comment]
I managed to do it! Thanks @Rechi for your help.

**Comment by Wintermute0110** [comment]
@Rechi, guys. The addon has been waiting for two weeks. Is everything all right? Is there anything I can to do to help? Thanks a lot.

**Pull request merged**
