### PR TITLE
[plugin.program.remote.control.browser] 1.3.1

### PR DESCRIPTION
**Pull request by chadparry**
### Description
This plugin for watching Netflix and YouTube and other websites from Kodi now supports PulseAudio.
### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] 1.0.0

### CODE REVIEW

**Comment by chadparry** [comment]
NB. I fixed a Travis error by documenting the add-on's website. The most recent Travis test failure is an expected violation because two of the add-on script files are executable. This is a complex add-on that involves starting an external browser, so some scripts are supposed to be executable.

This pull request is safe and ready to be merged. Thanks!

**Comment by raptor2101** [comment]
Something gone wrong during the CI Build ...
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/kodi-addon-checker", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/kodi_addon_checker/__main__.py", line 89, in main
    report.add(check_artifact(directory, args, args.branch, all_repo_addons, args.PR))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/kodi_addon_checker/__main__.py", line 55, in check_artifact
    return check_addon.start(artifact_path, branch_name, all_repo_addons, pr, config)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/kodi_addon_checker/check_addon.py", line 49, in start
    check_old_addon.check_for_existing_addon(addon_report, addon_path, all_repo_addons, pr)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/kodi_addon_checker/check_old_addon.py", line 31, in check_for_existing_addon
    if addon_name in repo_addons:
TypeError: argument of type 'NoneType' is not iterable

im uncertain how to fix this ...

**Comment by enen92** [comment]
@chadparry can you fix the following errors for merging?

```
ERROR: ./plugin.program.remote.control.browser/retrieve.py is marked as stand-alone executable
ERROR: ./plugin.program.remote.control.browser/browse.py is marked as stand-alone executable
```

You need to drop the executable permissions from the said files:

`chmod -x files`

**Comment by chadparry** [comment]
As I've said, "This is a complex add-on that involves starting an external browser, so some scripts are supposed to be executable." Removing the executable permissions is the wrong way to build an add-on like this. But, since nobody will merge my new features if I do it the right way, I'll just remove the permissions.

**Pull request merged**
