### PR TITLE
[plugin.video.rtlxl] 1.1.2

### PR DESCRIPTION
**Pull request by Opvolger**
[plugin.video.rtlxl] 1.1.2

### CODE REVIEW

**Comment by Razzeee** [comment]
Please change your commit message to ```[plugin.video.rtlxl] 1.1.2```

**Comment by Opvolger** [comment]
Done

**Comment by Razzeee** [comment]
Seems like you didn't push? You will need to force push.

**Comment by Opvolger** [comment]
like this?

**Comment by Razzeee** [comment]
Nope, how do you interact with git? Git bash or a git client?

In essence you need to change the commit message for your commit. https://github.com/xbmc/repo-plugins/pull/417/commits/1f0e81269969ae174f402378b4f84e83e5928c2d
So an amend and a force push should be enough to change it.

**Comment by Opvolger** [comment]
This is not working. I will make a new PR.

**Pull request closed without merging**
