### PR TITLE
[plugin.service.gto] 2.0.2

### PR DESCRIPTION
**Pull request by b-jesch**

### CODE REVIEW

**Comment by phil65** [comment]
Again: just one commit please, you have to squash :)

**Comment by b-jesch** [comment]
Sorry, I'm not familar with git. I've tried this serveral times but ran from one issue into another. Found several methods to squash but that never worked for me. For any help I would be grateful.

**Comment by BigNoid** [comment]
```git rebase -i HEAD~6```
change the last 5 to ```fixup```
```git push -f origin jarvis```

**Comment by b-jesch** [comment]
Got another error: 'Could not apply a6b805ad2764715ef026ee19a58528f8ad246538... [plugin.service.gto] 2.0.2'. Giving it up. Opened just another PR

**Comment by BigNoid** [comment]
Just for the record, you can always start again without making a new PR. Backup your plugin folder and do a reset: ```git reset --hard upstream/jarvis```
Where upstream is ```git@github.com:xbmc/repo-plugins.git```. (This will make the branch even with jarvis from upstream)
Copy back the plugin folder and make a new commit and force push your branch with ```git push -f origin jarvis```

**Pull request closed without merging**
