### PR TITLE
script.100fm v0.2.0

### PR DESCRIPTION
**Pull request by nire0510**
### Description
New music add-on.
100FM radio station Kodi add-on. The add-on offers live listening to dozens different musical genres: 80's, 90's, Rock, Pop, Oldies and many more
### Checklist:
- [ X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ X] Each add-on submission should be a sinlge commit with using the following style: [plugin.video.foo] v1.0.0

Addtional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuesly monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

100FM radio station Kodi add-on. The add-on offers live listening to dozens different musical genres: 80's, 90's, Rock, Pop, Oldies and many more

### CODE REVIEW

**Comment by nire0510** [comment]
@phil65 Hi, plugin type changed per your request + your other comments were fixed.
Thanks

**Comment by phil65** [comment]
Thx for the quick adjustments, looks good on first sight. @learningit mind havin a quick look, too?

**Comment by phil65** [comment]
Oh, you´re still PR´ing to the wrong repo. Please use https://github.com/xbmc/repo-scripts

**Comment by nire0510** [comment]
@phil65 submitted a [new PR to repo-scripts](https://github.com/xbmc/repo-scripts/pull/281). Hope that this time it'll go smooth :)

**Comment by nire0510** [comment]
Hi @phil65 haven't heard from you since I submitted my PR to repo-scripts, as you requested. Are there still issues which prevent my PR from being merged?
Thanks in advance.

**Pull request closed without merging**
