### PR TITLE
[plugin.video.specialfeatures] 3.0.1

### PR DESCRIPTION
**Pull request by smitchell6879**
### Description
I misunderstood the new language file format didn't realize it had been lost in code... so this is a hot fix so that the words show up as they are supposed too. Please double check that it works, as I do find myself with corky results sometimes.

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by Rechi** [comment]
You have to increment version in addon.xml and commit message has to be `[plugin.video.foo] v1.0.0`.

**Comment by Lunatixz** [comment]
@smitchell6879 Please follow submission title rules [plugin.video.specialfeatures] 3.0.0

**Comment by smitchell6879** [comment]
My apologizes I am still trying to get used to the GitHub stuff. I bumped the version to 3.0.1 and updated the title.

**Comment by smitchell6879** [comment]
- icon has been changed to .jpg
 - language folder append path has been removed

**Comment by Rechi** [comment]
> Each add-on submission should be a single commit [...]

Can you also squash your commits?

**Comment by smitchell6879** [comment]
@Rechi  I can close this pull request and open another one... other then that I do not know how to squash commits after I have already opened the pull request... I did see where you can squash on merge but once again that will be on your side. 

please advise if I should close this pull request and reopen with on commit

**Comment by enen92** [comment]
I think the icon has to a png file

**Comment by smitchell6879** [comment]
Personally it doesn't matter to me about the icon it was just something I threw together. I honestly am not sure how much I  really like it. But I don't know how to use gimp or photoshop to make a really good one so my little paint.net will have to do hahaha.

**Comment by Lunatixz** [comment]
Icons are *.png fanart is *.jpg both cannot be transparent :)

**Comment by smitchell6879** [comment]
so do I need to change it back to a *.png or leave it as a .jpg ... I changed it to .jpg because I assumed that's what @enen92 was requesting me to do. Also what about the commit squash issue? do I need to reopen as a new pull request? I am using the web version of GitHub along with the gitdesk for windows... so I do not know how to squash commits into one after I have already made the initial pull request with one commit... the other commits are fixing things that where requested . 

Please advise

**Comment by Lunatixz** [comment]
Icons are *.png fanart is *.jpg both cannot be transparent :)

All PR's should contain one single commit. Use git rebase to squash multiple commits into one.

**Comment by smitchell6879** [comment]
Alright. I still don't know how to do that yet and I am trying to get this fixed asap since atm the addon is useless to another that downloads it. So I will learn on another PR, I am closing this one and will open a new one with one commit.

**Comment by Lunatixz** [comment]
You can make the requested changes and we can "squash" your commits; while you learn how to rebase on your end.

**Pull request closed without merging**
