### PR TITLE
[plugin.video.sarpur] v4.3.0

### PR DESCRIPTION
**Pull request by Dagur**
### Description
Localization
Featured
Categories

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
Why have you checked 'Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0', if you haven't done it?

**Comment by Dagur** [comment]
Sorry, I thought it only applied to the add-on submission. The wording could be a bit clearer.

**Comment by enen92** [comment]
@dagur can you rename tour commit please to follow our submission standards? Thanks

**Comment by Rechi** [comment]
Your PR now contains 3 commits, from what one is even a merge commit.

To fix your pull request execute the following commands (origin is your repo, upstream is the xbmc repo)

```
git fetch upstream
git checkout gotham
git reset --hard upstream/gotham
git checkout origin/gotham -- plugin.video.sarpur/
git commit -m '[plugin.video.sarpur] v4.3.0'
git push -f origin gotham
```

**Comment by sindrig** [comment]
@Dagur are you re-opening this?

**Comment by Dagur** [comment]
I created a new one https://github.com/xbmc/repo-plugins/pull/2059

Sorry, forgot to point that out

**Pull request closed without merging**
