### PR TITLE
[plugin.video.filmsforaction] 1.0.8

### PR DESCRIPTION
**Pull request by jamontes**
### Description
Hi,

This is a new update for plugin.video.filmsforaction over Gotham branch.

Changelog: 1.0.8 (2017.03.13)
- Fixed video scraper due to Dailymotion website changes.
- Fixed category menus due to website changes.
- Fixed search option due to website changes.
- Fixed Next/Previous Page entries due to website changes.
- Improved Vimeo scraper to support non standard video resolutions.
- Updated logging system.
- Updated lutils library to latest version.
- Updated category test case.
- Improved video patterns.
- Code refactored and cleaned.

Many thanks in advance for your help and best regards,

jamontes.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
you also have ESO pluging in this PR

**Comment by jamontes** [comment]
Hi Martijn,

Yes, you are right. That's my fault due to my lack of experience working with PRs. I thought after requested this PR some days ago, i could send another PR in a different commit for ESO add-on without interfere with this one, still open. Then, after sent the push from my local repo-plugins to my fork on GitHub and try to open the new PR for ESO i realized that the new one will include both commits, so i cancelled the new PR and leaved the previous PR (i.e. this one) as is, without noticed it already contained both commits as it remains still opened.

This is something embarrassing for me, because my intention was to operate according to the rule of keep one commit per PR, and honestly i don't know how to proceed with Git and GitHub in order to rollback and keep this PR with just the filmsforaction update, and once this PR is accepted and merged, send another one afterwards with the ESO update.

Please, could you help me with this?

Many thanks in advance for your help and patience and best regards,

jamontes.

**Comment by jamontes** [comment]
Hi Martijn,

In order to work with just one add-on per PR/commit, i could reopen the PR from scratch by re-forking the repo-plugins again and work with a clean-synced version where i can send just a single add-on update per time. I guess this is not the most efficient nor proper way to undo the changes into my fork history (i.e. by deleting and re-forking the repo), but i don't know how to split the commits into separate PRs as they are right now from GitHub. Just let me know if you agree with this solution and i will try to do it in that way asap.

Many thanks in advance for your help and best regards,

jamontes.

**Comment by jamontes** [comment]
Hi, 

I'm closing this PR and try again with a proper one.

Best regards,
jamontes.

**Pull request closed without merging**
