### PR TITLE
[plugin.video.nhkworldtv@matrix] 1.0.5+matrix.1

### PR DESCRIPTION
**Pull request by sbroenne**
### Add-on details:

- **General**
  - Add-on name: NHK World TV
  - Add-on ID: plugin.video.nhkworldtv
  - Version number: 1.0.5+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/sbroenne/plugin.video.nhkworldtv
  

Watch NHK World Japan in Full HD

- Live Stream 
- On demand programs - By program, latest and most watched, categories and playlist. You can also browse and search through all programs.
- Live schedule
- Top Stories and At a Glance
- News programs like NEWSLINE, NEWSLINE IN DEPTH and NEWSROOM TOKYO

Content is retrieved and played directly from the NHK World web site.

Plugin supports fallback to HD if you should encounter buffering issues.
        

### Description of changes:

v1.0.5
- Removed support for Kodi Leia
- Optimizations for Python 3.x
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by sbroenne** [comment]
My previous request to have this NHK World plug-in included in the official repo was denied because there is an existing plugin for this (NHK Live).

**Unfortunately NHK Live has not been working for a few months.**

In the light of this, I would kindly ask you to re-consider your decision from earlier this year so that there is a working NHK plug-in the repo.

**Comment by basrieter** [comment]
> My previous request to have this NHK World plug-in included in the official repo was denied because there is an existing plugin for this (NHK Live).
> 
> **Unfortunately NHK Live has not been working for a few months.**
> 
> In the light of this, I would kindly ask you to re-consider your decision from earlier this year so that there is a working NHK plug-in the repo.

So why not contribute to that one with a fix? @enen92 you reviewed the previous PR: https://github.com/xbmc/repo-plugins/pull/3426. What are your thoughts?

**Comment by enen92** [comment]
It really depends if the maintainer of the old add-on is MIA or not, wasn't it learningit or lunatixz

**Comment by basrieter** [comment]
> It really depends if the maintainer of the old add-on is MIA or not, wasn't it learningit or lunatixz

Yes, I think it was learningit. @learningit could you please let us know what the status of your add-on is? And whether this one might replace the other one?

**Comment by learningit** [comment]
I guess I didn't update the repo in a bit. My version is 4.0.5 and it looks
like the repo is 4.0.2. The current version works fine here in Japan. I'll
issue a pull request in the next day or so with 4.0.5. I've been super busy
here and haven't had any time to play with Kodi in the past several months.

Someone else can decide whether to replace it with a new addon. My addon is
pretty small and straight forward though.

Tim

**Comment by sbroenne** [comment]
I have updated the plug-in to only support Matrix and made optimizations for Python 3.8+.

This plug-in exposes significantly more functionality from NHK World than NHK Live does **plus** also has many features "under-the-hood" to speed up browsing & play-back (e.g. using requests-cache for all requests and  a corresponding web service that resolves on-demand program URLs in milliseconds rather than 5 seconds, etc.).

By default. it also **plays 1080p instead of 720p** (you can fall-back to 720p). NHK has a fantastic-quality 1080p stream and on-demand programs.

Your decision.

**Comment by learningit** [comment]
The current addon in the repo defaults to 1080, falls back to 720. Most users don't care about ms vs 3-5 secs. The current addon is simple, compact and has been very stable with much less "moving parts" and doesn't require mods to existing external modules.

**Comment by learningit** [comment]
The current addon also has the ability to add shows to the Kodi library if the show exists in an info scraper. Some shows work well like Trails to Oshii Tokyo. Not many NHK shows have TMDB entries though so the functionality is limited.

**Comment by sbroenne** [comment]
> The current addon in the repo defaults to 1080, falls back to 720. 

I am using 4.0.5 from the Kodi repo and it **does not play 1080p** on any programs that I tried. You can check with "Barakan discovers: Ainu" or "Cycle around Japan". This is why I was under the impression that it only supports 720p. 

> Most users don't care about ms vs 3-5 secs. 

As they say, your mileage may vary.

> ... and doesn't require mods to existing external modules.

I don't understand your statement that NHK World TV requires mods to existing external modules - it doesn't. It works with what currently exists in the Matrix repo.

Anyway, if it was up-to me, both plug-ins should exist in the repository and give users the choice.

If this is still not possible, then I am happy to withdraw this PR and keep hosting it in a private repo.

**Comment by learningit** [comment]
The 2 programs you mention are in 1080 in 4.0.5 you have to have inputstream configured correctly on some systems, usually laptops with resolutions smaller than 1080. I rely on Kodi settings rather than creating my own for the addon.

The external mod comment was based on the other PRs that I tought were related to this addon. My bad.

I somewhat agree with your comment about multiple versions but I've lived by the those rules as well for a number of years. If I really thought I was doing something better than the addon in the repo I would put a PR on the original author and leave it to him/her to accept the change. Different people have different ideas about how addons should be done. For me having had to support 60 or 70 addons at a time it was about simplicity, less controls and making use of Kodi settings rather doing my own. Less moving parts, less things break.

**Comment by sbroenne** [comment]
> The 2 programs you mention are in 1080 in 4.0.5 you have to have inputstream configured correctly on some systems, usually laptops with resolutions smaller than 1080. I rely on Kodi settings rather than creating my own for the addon.

I am using Win11 on Surface Book 3 with a resolution of 3440x1440 and Sony 4K TV running Android.TV and both play only 720p.

I haven't changed any Kodi or inputstream settings. Which ones do I need to change?

Anyway, this PR is probably not the right place to troubleshoot this ;-)

**Comment by learningit** [comment]
On my Sony 4k tvs Input stream Adaptive is enabled. Max resolution general/secure decoder is 1080p, automatic select streams, override HDCP is on, Ignore Display Resolution is on. Here in Japan I can get 4K streams as well but it requires a subscription.

**Comment by learningit** [comment]
You need to look at video settings to see the actual resolution being played. The 720HD info indicator isn't updated to 1080 if it's playing 1080. The video settings shows the actual.

**Comment by sbroenne** [comment]
> On my Sony 4k tvs Input stream Adaptive is enabled. Max resolution general/secure decoder is 1080p, automatic select streams, override HDCP is on, Ignore Display Resolution is on. 

Okay, that did the trick. However, I would have never found that on my own. Is that documented anywhere? E.g. that you need to change from default *Max* to *1080p* to play 1080p instead of 720p - this is a bit counter-intuitive... but maybe this is just me ;-)

**Comment by learningit** [comment]
Actually I think you'll find that you can leave it set to Max. It's one of the other settings that is needed on some platforms. I always try to use Kodi settings rather than create new redundant settings in an addon.

**Comment by sbroenne** [comment]
I am closing/withdrawing this PR now since I assume the decision is not to include the add-in to the repo.,

**Pull request closed without merging**
