### PR TITLE
plugin.video.kodi_maintenance 

### PR DESCRIPTION
**Pull request by ebs111**
### Description
this addon give a lot of maintenance option such as install /uninstall addon/repo, remove KODI temp files, and let you install a list of addons from a txt list.
### Checklist:

- [ X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
code url: https://github.com/ebs111/plugin.video.kodi_maintenance.
thanks

### CODE REVIEW

**Comment by Razzeee** [comment]
Your branch had some problems and I don't think we will be able to accept something that installs addons from a txt

**Comment by ebs111** [comment]
Hi
Thanks for your replay.
Why cant you accept that it installs addons from txt what is the
difference? Instead of installing one by one it will install alist.

בתאריך 13 ביוני 2017 11:02 אחה״צ,‏ "Razzeee" <notifications@github.com> כתב:

Your branch had some problems and I don't think we will be able to accept
something that installs addons from a txt

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xbmc/repo-plugins/pull/1260#issuecomment-308231451>,
or mute
the thread

**Comment by Razzeee** [comment]
It's making it really easy for box makers/build makers to preload stuff (aka piracy) and that's something we don't want to help with.

**Comment by ebs111** [comment]
it is the same as installing one by one what is the difference installing addon does not mean piracy and installing a list does not mean piracy right?

 

 


  
Ezra Ben Senyor


 <http://www.gamatronic.co.il/> 


טלפון: 

02-5888352



  <http://www.facebook.com/pages/%D7%92%D7%9E%D7%90%D7%98%D7%A8%D7%95%D7%A0%D7%99%D7%A7-%D7%AA%D7%A2%D7%A9%D7%99%D7%95%D7%AA-%D7%90%D7%9C%D7%A7%D7%98%D7%A8%D7%95%D7%A0%D7%99%D7%95%D7%AA-%D7%91%D7%A2%D7%9E/223474817673624?sk=wall> Like us on Facebook   <http://twitter.com/gamatronic/> Follow us on Twitter   <http://www.youtube.com/user/GamatronicLtd> See us on YouTube


 Consider the environment <file:///C:\Users\ezrab.GAMA\Application%20Data\Microsoft\Signatures\P-Webding.png> Please consider the environment before printing this email.

**Comment by Razzeee** [comment]
Correct, the problem is that you can install stuff in BULK. So what would be the usecase for that?

**Comment by ebs111** [comment]
many reason:

1. you can organize your own favorite list of addon script and programs, so that even if you reset the kodi completely you can easily set it back up.

2. sometimes there are so many addons that you don't know what you really need and what not so with this addon no problem remove all and get it back up with just what you want.

3. you can give the list to a friend so you can share your favorite addons.

4. you can create different list for different purposes say one kodi for music one for youtube,halmark,trailers and etc..

5. i am sure there are many many more that other users will find.

 


  
Ezra Ben Senyor


 <http://www.gamatronic.co.il/> 


טלפון: 

02-5888352



  <http://www.facebook.com/pages/%D7%92%D7%9E%D7%90%D7%98%D7%A8%D7%95%D7%A0%D7%99%D7%A7-%D7%AA%D7%A2%D7%A9%D7%99%D7%95%D7%AA-%D7%90%D7%9C%D7%A7%D7%98%D7%A8%D7%95%D7%A0%D7%99%D7%95%D7%AA-%D7%91%D7%A2%D7%9E/223474817673624?sk=wall> Like us on Facebook   <http://twitter.com/gamatronic/> Follow us on Twitter   <http://www.youtube.com/user/GamatronicLtd> See us on YouTube


 Consider the environment <file:///C:\Users\ezrab.GAMA\Application%20Data\Microsoft\Signatures\P-Webding.png> Please consider the environment before printing this email.

**Comment by MartijnKaijser** [comment]
Like hell we will ever accept this

**Comment by ebs111** [comment]
why? what is wrong with that?


  
Ezra Ben Senyor


 <http://www.gamatronic.co.il/> 


טלפון: 

02-5888352



  <http://www.facebook.com/pages/%D7%92%D7%9E%D7%90%D7%98%D7%A8%D7%95%D7%A0%D7%99%D7%A7-%D7%AA%D7%A2%D7%A9%D7%99%D7%95%D7%AA-%D7%90%D7%9C%D7%A7%D7%98%D7%A8%D7%95%D7%A0%D7%99%D7%95%D7%AA-%D7%91%D7%A2%D7%9E/223474817673624?sk=wall> Like us on Facebook   <http://twitter.com/gamatronic/> Follow us on Twitter   <http://www.youtube.com/user/GamatronicLtd> See us on YouTube


 Consider the environment <file:///C:\Users\ezrab.GAMA\Application%20Data\Microsoft\Signatures\P-Webding.png> Please consider the environment before printing this email.

**Pull request closed without merging**
