### PR TITLE
Jarvis

### PR DESCRIPTION
**Pull request by hkastrati7**
This is the official  video addOn of the Radio Television of Kosovo, in which you will be able to watch four of TV channels, and two of Radio stations.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a sinlge commit with using the following style: [plugin.video.foo] v1.0.0

Addtional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuesly monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by learningit** [comment]
Please read this: http://kodi.wiki/view/Submitting_Add-ons and this http://kodi.wiki/view/Add-on_rules very carefully.  There are just too many things incorrect with this submission to even be reviewed starting with the PR naming which need to be of the format plugin.video.name x.y.z to the use of both lower and upper case in the .rtk portion of the plugin name, half the fields in addon.xml are missing, there are numerous print statements in the code which need to be changed to xbmc.log() to the fact that there are 4 commits in a single PR (please see https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit for how ro deal with that.

**Comment by learningit** [comment]
Given all these points, we cannot process this request. I will leave it open for a day so that you can see these comments, after which I will close this PR as it requires far too much work to accepted into the kodi.org repo in its current state.  Please read the submission links very carefully and adhere to them in your next submission. Thanks

**Comment by hkastrati7** [comment]
@learningit yesterday I submitted the same add on and you said to me that I have to change some code in order to resubmit this one. I made those changes, but since I'm new to github,  I think I have disrupted files. So i will create a new branch and a new PR again and  submit  the right one.  When you say: you can make only one commit, is it good if I commit the folder containing all files, because I have 7 of them

**Comment by learningit** [comment]
Your last commit looks a lot better but is cluttered with the older files. Also can you look at addon.xml and make sure that you are actually using the imported addons, a quick glance looks like you're not using them all.  Also make sure that you set xbmc.python to the correct value for the repo your submitting to, please see http://kodi.wiki/view/Addon.xml#Dependency_versions (I think you want "2.24.0")

**Comment by learningit** [comment]
So it would be cleanest if you close this PR and submit a clean one with the new cleaned up files. Thanks

**Comment by learningit** [comment]
BTW I see you are using the URL http://www.rtklive.com/kodi/home.txt  , are you staff for RTK or have the rights to rtklive content?

**Comment by learningit** [comment]
Also please name the new PR plugin.video.rtk 1.0.0, as well as the commit  (the version may be different from 1.0.0, please use the one you want) Thanks

**Comment by hkastrati7** [comment]
Yes I'am programmer in the department of IT in RTK(Radio Television of Kosovo), and it was request from the Head of It to do this add on. Now I changed the structure of add On totally. I downloaded the plugin.video.frikanalen, and made some changes there , replacing all the links to the RTK links. It is in compliance with Kodi to do this?

**Comment by learningit** [comment]
Yes the GPL license allow you to re-use source.  Originally you had some modules from piracy addons that we don't allow in the kodi.org repo, but your last commit looked pretty good but was messy because of all the previously unused modules

**Comment by hkastrati7** [comment]
Now can I ask from you a last question?
This is my directory : https://github.com/hkastrati7/repo-plugins/tree/jarvis
and there are two addOns that I was trying to submit . I cannot delete them. I think there is problem that files was cluttered. How can I delete them?

**Comment by learningit** [comment]
I'm not sure why you can't delete them.  If you delete them on your local system then do a commit to github it should remove the files.  Anyway you can always delete the xbmc/repo-plugins locally and from github, clone it again then start from there with adding your clean add-on into the Jarvis branch.

**Comment by hkastrati7** [comment]
Aha, thank you so much.
I would try this, we'll be in touch

**Comment by hkastrati7** [comment]
hey, I have another problem.
I followed your advice and deleted repo-plugins from my github and also localy. Now I cant set this repo-plugins to my github. Can u please help me

**Comment by learningit** [comment]
Did you fork to your github, then clone to your desktop?

**Comment by hkastrati7** [comment]
how to fork?

**Comment by hkastrati7** [comment]
Ooo silly me,
Sorry for this question

**Comment by hkastrati7** [comment]
I think it ok now

**Comment by learningit** [comment]
I think the steps are:
1) Login to your github account in a browser
2) goto xbmc/repo-plugins in your browser
3) click on Fork at the top of the page
4) once forked goto xbmc/repo-plugins in your github account
5) click on "Clone or download"
6) click on "Open in desktop"
Step 6 will take some time depending on your internet speed

**Comment by hkastrati7** [comment]
Thank you for your help.
I was trying to follow steps descriped in this link: http://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging
But i forgot to fork. Now I'm trying to submitt. Let's see

**Comment by hkastrati7** [comment]
Hey @learningit , thank you so much for all of your help and suggestions. Now I opened a new Pull Request for my add on. Hope that it in compliance with all of Kodi restricitons, and you can put it in kodi.org repo. 
All the best!

**Comment by learningit** [comment]
I will look through later, I am tied up right now. Basically looks OK, but maybe a couple small items. Thanks for your patience.

**Pull request closed without merging**
