### PR TITLE
[plugin.video.myvevo] v3.0.8

### PR DESCRIPTION
**Pull request by idleloop-github**
### Description

version field in json answer doesn't seem valuable (there are values of 2, 3 or 4 at least), and in fact restricting it hides legit videos from loading.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by learningit** [comment]
It's not as simple as that. the version indicates what the video format is, or at least it used to.
Earlier versions of Kodi are unable to play several of those formats which is why it was being checked. it's possible that VEVO is no longer supporting stuff like DASH, but last I looked it was.

Even then, I believe there are a couple of formats that Kodi doesn't play (.wvm, etc) or are just audio. 
So possibly if the change is made to a Krypton or higher version it would be OK, but not for earlier versions. I'll keep this in mind though.

**Comment by idleloop-github** [comment]
Ok! it resolved loading some videos for me, but your criterion is wiser.
Please, fell free to close this push request.
Thanks for your time!

**Comment by idleloop-github** [comment]
needs more coding and testing

**Comment by learningit** [comment]
I need to have a through look at tgis. VEVO is always in a state of flux. But I think we need to filter out some formats which we know won't play in earlie e Jodi versions. It is usually with older videos, so it's not always obvious when you test.

**Comment by learningit** [comment]
I'm going to repoen this to remind me to look into the versioning. I most likely will need to create a Krypton and above version anyway and I think this maybe valid. In a recent change, VEVO has decided to return between 4 to 8 alternate urls for each bitrate in index.m3u8. This cause the auto detect for best stream in the player to go a bit crazy and time out on lower powered platforms. I may need to pull the index.m3u8 apart before passing it to the player to fix this.  Pre-Jarvis versions don't have the issue, or it's less apparent anyway.

**Comment by idleloop-github** [comment]
Yeah, the m3u8 is full of resolution options and three backup urls for each of them. I also had to treat a (less complicated) m3u8 before passing it to the player [in another plugin](https://github.com/idleloop-github/xbmc-earthcam/blob/303047e49cd7ae080422bd9acaa676f8c34054f1/channel.py#L364).
It would be great if resolutions could be selected in addon's options. Something like SD, 720 & 1080. Just a suggestion ;-)

**Comment by learningit** [comment]
Thanks for the time you spent on this. I've updated the add-on in the repo. I ended up using inputstream.adaptive to solve the backup url issue.

**Pull request closed without merging**
