### PR TITLE
[plugin.video.drnu] 5.0.13

### PR DESCRIPTION
**Pull request by TermeHansen**
### Description
- Adding old PR's + minor fixes. last update before kodi 19 and python3
- Change for request-cache for storing web requests locally (in 8hours) #34
- Fix missing thumbnails and added option in settings to choose fan-art image size #29 #35
- Fixed themes menu item #34
- Add support for other plugins to start live tv. #31
- Update logos and entry screen #24
- Change subtitle handling to local srt files, so user also can change for hard-of-hearing subs and change while watching #36

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by enen92** [comment]
Hey @TermeHansen
You're submitting a new addon to Leia but Kodi's latest version in Matrix which is based on python 3. We don't have Leia blocked to new addons (yet) but we do require that new addons are merged into matrix first, then Leia.
Thanks

**Comment by enen92** [comment]
Actually your addon is in the gotham branch, so if you want to have an update before merging to matrix please target the gotham branch

**Comment by enen92** [comment]
if you have only tested leia, please send an aditional PR to mark the addon in gotham as broken

**Comment by TermeHansen** [comment]
Yes I have only tested on Leia, and yes I wanted to make one last update before the change for py3. So If I understand correct we keep this 5.0.13 update PR here for Leia, but I should also make a PR for Gotham that marks 5.0.13 broken there?

**Pull request closed without merging**
