### PR TITLE
plugin.video.viewster 3.0.4

### PR DESCRIPTION
**Pull request by learningit**
Mark as Broken

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by enen92** [comment]
@learningit why do you remove the files? The entrypoint at least is needed as far as I remember.
If you want to remove the code, leave a placeholder in the entrypoint file that just exits the plugin. Otherwise leave it as is and just change the addon.xml

**Comment by learningit** [comment]
That's how I've done it in the past. In fact Martijn told me all that's needed is addon.xml

In some ways it doesn't make sense to care about anything other than broken, particularly if you're doing a takedown.

**Comment by enen92** [comment]
When an addon is marked as broken the user receives the update and may or may not decide to keep the plugin installed. If it decides to keep it, kodi won't be able to find the entrypoint file. If the addon is just broken it's better just to add the broken tag and bump the addon version. If it is a takedown, it makes sense to remove the code but at least leaving the entrypoint with an exit placeholder.

Either way, your addon.xml is broken (you deleted one of the commas on the version)

**Comment by learningit** [comment]
> When an addon is marked as broken the user receives the update and may or may not decide to keep the plugin installed. If it decides to keep it, kodi won't be able to find the entrypoint file. If the addon is just broken it's better just to add the broken tag and bump the addon version. If it is a takedown, it makes sense to remove the code but at least leaving the entrypoint with an exit placeholder.
> 
> Either way, your addon.xml is broken (you deleted one of the commas on the version)

Should be all fixed (broken?) now.

**Pull request merged**
