### PR TITLE
[plugin.video.embycon] remove

### PR DESCRIPTION
**Pull request by faush01**
### Description

Please remove, thanks.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by enen92** [comment]
@faush01 this is not allowed. Please mark it as broken first with a version bump.
Can I ask what was the problem that required a removal?

**Comment by faush01** [comment]
ok I will create a broken version. Does it need to have all the files or just the addon.xml?

To hard and to slow to manage.

**Comment by enen92** [comment]
Needs at least the entrypoints and the artwork appart from the addon.xml. 
I'm sad to hear that. Unfortunately we are really short on numbers and I've been to busy lately to address all the PRs at the rate I used to.

**Comment by faush01** [comment]
Ok got it, thanks.
Kodi does feel like it is slowing down a little, both the addons and the app itself. Its understandable and not anyones fault.
I have bug fixes I am trying to get out and it takes weeks to have a release done so I think I am just going to use a private repo for now.
Thanks for the help.

**Pull request closed without merging**
