### PR TITLE
[plugin.audio.ampache@leia] 1.2.1

### PR DESCRIPTION
**Pull request by lusum**
### Description

**Add-on details:**

*General*

- Add-on name: Kodi Ampache plugin
-  Add-on ID: plugin.audio.ampache
- Version number: 1.2.1
- Kodi/repository version: leia

Code location
- URL: https://github.com/ampache/ampache-xbmc-plugin

New plugin, official ampache server/nexcloud music plugin for kodi

1.2.1 (31.01.2021)

- Apply changes to be included in the official kodi repo plugin

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by lusum** [comment]
I don't understand the abi compatibility error. I have submit two different plugins for two different kodi version, what i have to add in this version?

**Comment by enen92** [comment]
the version in matrix has to be higher than the one in leia so that when users migrate from leia to matrix they are able to download an update from the repository. What we've been doing instead of managing 2 different versions is to add local version identifiers to the matrix version:

Leia: 1.2.1
Matrix: 1.2.1+matrix.1 

Version is the same but 1.2.1+matrix.1 > 1.2.1

**Comment by lusum** [comment]
So, this was an error in my previous push, i have to add 1.2.1+matrx.1 in addon.xml, can i push an update with only the diff of the version?

**Comment by enen92** [comment]
Not an error, if you set this one to 1.2.0 it'll work. But yeah, it's better if you update the other one to keep the versions consistent

**Comment by lusum** [comment]
I have updated the matrix version and issued a new request, so this pull could be merged

**Review by enen92 — APPROVED** [review]

**Pull request merged**
