### PR TITLE
[plugin.video.magaritv] 1.0.0

### PR DESCRIPTION
**Pull request by ogiliberti**
Dear All,

I would like to push my Kodi Addon to the official repository
to allow people to watch MagariTV
* addon - plugin.video.magaritv
* version - 1.0.0
* revision -  ae38b7c
* url - https://github.com/ogiliberti/plugin.video.magaritv
* xbmc version - jarvis

I hope this time my PR is correct.
Apologise in advance for any inconvenience.
Thanks for your kind attention.

Best Regards,

Orazio Giliberti

### CODE REVIEW

**Comment by ogiliberti** [comment]
Hello !

Any news about this plugin ?

Best Regards,

Orazio Giliberti

**Comment by phil65** [comment]
magari.tv looks fishy to me. What should that be?
Also, the commit message is wrong, please stick to our naming scheme.

**Comment by ogiliberti** [comment]
Dear Phil65,

Firstly MagariTV is a registrered trademark in Italy as you can check here:
https://www.tmdn.org/tmview/welcome

Secondly www.magari.tv is a domain registrered at my name ad you can check here:
http://who.is/whois/magari.tv

If you want to tell me precisely what is wrong in the name and what is the correct format it will be appreciated.

Thanks for your kind attention.
Best Regards,

Orazio Giliberti

**Comment by ogiliberti** [comment]
Dear Phil65,

Firstly MagariTV is a registrered trademark in Italy as you can check here:
https://www.tmdn.org/tmview/welcome

Secondly www.magari.tv is a domain registrered at my name ad you can 
check here:
http://who.is/whois/magari.tv

If you want to tell me precisely what is wrong in the name and what is 
the correct format it will be appreciated.

Thanks for your kind attention.
Best Regards,

Orazio Giliberti


Il 05/05/2016 15:26, Philipp Temminghoff ha scritto:
> magari.tv looks fishy to me. What should that be?
> Also, the commit message is wrong, please stick to our naming scheme.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/451#issuecomment-217154098>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Comment by ogiliberti** [comment]
To whom it may concern,


MagariTV is an OTT/Web Tv having www.magari.tv as domain.

The server hardware is in Germany and I live in Italy.

Italy and Germany are part of the European Union that for many business 
is a common space where citizens, goods and services are free to circulate.

Currently the access is restricted to register users, but given that a 
gentleman accused me to push fishy software,
anyone is free to ask me the login details.

Moreover if you use this plugin you can check by yourself that the 
plugin and the magaritv contents are completely harmless.

Login details has been already given to Scotty Roscoe some days ago and 
, if he wants, can confirm.

To anyone understanding italian I give the link to the presentation I 
gave at University of Pisa on 20th May 2015 to present MagariTV.

http://www.labcd.unipi.it/evento/presentazione-magaritv/


The more scared and concerned can simply use google and look for 
"Giliberti" + "Magari" + "TV" + "Pisa" and they get the same link.

You can even find the presentation on Youtube and on Facebook where 
there is a MagariTV page

Moreover MagariTV since  24 March 2016 is a registrered trademark in 
Italy with number 0001669400.

You can check here http://www.uibm.gov.it/uibm/dati/Testo.aspx

by flagging Marchi (in Italian means trademark)
inserting magaritv in the box
pressing "Cerca"  that in Italian means look.


I understand that running a software repository potentially open to any 
kind of people is a heavy task.

However no task, whatever complicated, can be aN entitlement for 
accusing anyone without evidence or without asking any check unless
the Kodi foundation is surprisingly a citadel poisoned by sectarism.


Thanks a lot for your attention.

Best Regards,

Orazio Giliberti

Il 05/05/2016 15:26, Philipp Temminghoff ha scritto:
> magari.tv looks fishy to me. What should that be?
> Also, the commit message is wrong, please stick to our naming scheme.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/repo-plugins/pull/451#issuecomment-217154098>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Comment by phil65** [comment]
Thanks for the additional info, you still need to adjust the commit message though before we can consider this.

**Comment by ogiliberti** [comment]
May you tell me what is wrong ?

**Comment by Razzeee** [comment]
@ogiliberti yes, that would be correct

**Comment by ogiliberti** [comment]
Is ok now ?

**Comment by phil65** [comment]
Nope, your commit message still is "Added files via upload". You have to change that to "[plugin.video.magaritv] 1.0.0"

**Comment by ogiliberti** [comment]
I had sent this plugin by email and I wass suggested to send by github.
Now what do you want ?

**Comment by ogiliberti** [comment]
Dear All,

Despite the information given now there is the story if the commit message.

I submitted a PR once again by web interface, correctly accepted by the 
github system with all data to allow peers to check my software that 
resides on github uniquely identified and in the message thee is even 
the url.

It sounds like the Chicago electoral commission in the 1950s accepting 
only the application forms that once throwed to the office ceiling 
didn't remain attached to the ceiling....

Thanks for the kind attention

Best Regards,

Orazio Giliberti





Il 05/05/2016 17:15, Orazio Giliberti ha scritto:
>
>
> To whom it may concern,
>
>
> MagariTV is an OTT/Web Tv having www.magari.tv as domain.
>
> The server hardware is in Germany and I live in Italy.
>
> Italy and Germany are part of the European Union that for many business
> is a common space where citizens, goods and services are free to circulate.
>
> Currently the access is restricted to register users, but given that a
> gentleman accused me to push fishy software,
> anyone is free to ask me the login details.
>
> Moreover if you use this plugin you can check by yourself that the
> plugin and the magaritv contents are completely harmless.
>
> Login details has been already given to Scotty Roscoe some days ago and
> , if he wants, can confirm.
>
> To anyone understanding italian I give the link to the presentation I
> gave at University of Pisa on 20th May 2015 to present MagariTV.
>
> http://www.labcd.unipi.it/evento/presentazione-magaritv/
>
>
> The more scared and concerned can simply use google and look for
> "Giliberti" + "Magari" + "TV" + "Pisa" and they get the same link.
>
> You can even find the presentation on Youtube and on Facebook where
> there is a MagariTV page
>
> Moreover MagariTV since  24 March 2016 is a registrered trademark in
> Italy with number 0001669400.
>
> You can check here http://www.uibm.gov.it/uibm/dati/Testo.aspx
>
> by flagging Marchi (in Italian means trademark)
> inserting magaritv in the box
> pressing "Cerca"  that in Italian means look.
>
>
> I understand that running a software repository potentially open to any
> kind of people is a heavy task.
>
> However no task, whatever complicated, can be aN entitlement for
> accusing anyone without evidence or without asking any check unless
> the Kodi foundation is surprisingly a citadel poisoned by sectarism.
>
>
> Thanks a lot for your attention.
>
> Best Regards,
>
> Orazio Giliberti
>
> Il 05/05/2016 15:26, Philipp Temminghoff ha scritto:
>> magari.tv looks fishy to me. What should that be?
>> Also, the commit message is wrong, please stick to our naming scheme.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xbmc/repo-plugins/pull/451#issuecomment-217154098>
>>
>

-- 
______________________________________________

Ing. Orazio Giliberti

mobile:  +393389847233
email:   ogiliberti@gmail.com
pec/cem: ogiliberti@pec.ording.roma.it

**Comment by Razzeee** [comment]
Sorry, really not sure what your trying to say. Your PR here is correct and exactly what we want you to do. 
But you need to change the commit message "Added files via upload" to "[plugin.video.magaritv] 1.0.0"
If you did this via github frontend (and can't/won't use anything else), you won't be able to change it to the correct message. Then just resend the PR with the correct message.
But I would recommend to look into git, as problems with your code MIGHT come up, that we want you to look into. And with git you can change the contents of your PR, whenever you want.

**Comment by ronie** [comment]
'making it as easy as possible for devs to submit addons to our repo' has always been our goal.
we're clearly heading in the wrong direction here.

i'm still clueless why the ones handling script/plugin pull-requests choose to ignore the mailing list...
but please reconsider.

**Comment by ogiliberti** [comment]
I send you a .pdf file with all printscreen of the steps I have done.
I didn't find any place to change the commit message "Added files via upload".
If you mind telling what is wrong I will be happy to correct.

Best Regards,

Orazio Giliberti
[SubmitGitHubProcess.pdf](https://github.com/xbmc/repo-plugins/files/251160/SubmitGitHubProcess.pdf)

**Pull request closed without merging**
