### PR TITLE
[plugin.video.videolina] 1.0.0

### PR DESCRIPTION
**Pull request by NextStepUnione**
### Description

Watch Videolina Live streaming directly from this addon.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Razzeee** [comment]
Unfortunatly your commit message (see commit rider) should also have the `[plugin.video.videolina] 1.0.0` format

**Comment by NextStepUnione** [comment]
I have changed the commit message! Is it eligible to be published?

Da: Razzeee [mailto:notifications@github.com]
Inviato: martedì 4 aprile 2017 11:29
A: xbmc/repo-plugins <repo-plugins@noreply.github.com>
Cc: NextStepUnione <nextstep@nextstep.it>; Author <author@noreply.github.com>
Oggetto: Re: [xbmc/repo-plugins] [plugin.video.videolina] 1.0.0 (#1099)

EMAIL MANDATA A NEXTSTEP@NEXTSTEP.IT<mailto:NEXTSTEP@NEXTSTEP.IT>

Unfortunatly your commit message (see commit rider) should also have the [plugin.video.videolina] 1.0.0 format

**Comment by enen92** [comment]
@NextStepUnione  You should make your PR against the krypton branch, you've done this PR against master

**Comment by Razzeee** [comment]
You will have to base your changes in krypton, if we change it it get's conflicts

**Pull request closed without merging**
