### PR TITLE
[plugin.video.dcmtv] 1.0.0

### PR DESCRIPTION
**Pull request by therezacuet**
### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by therezacuet** [comment]
I have checked log but the issue is others 7 addon already exist. How can i fix that?

**Comment by Rechi** [comment]
You have to submit the source files. We do not accept submodules.

**Comment by therezacuet** [comment]
I have used this link for make pull request https://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging
So how can i submit source file? I cant understand. 
I have also create a issue with details https://github.com/xbmc/repo-plugins/issues/2313

**Comment by Rechi** [comment]
With the commands mentioned in that wiki page, I don't see how a submodule could have been added.
I recommend copying the add-on source files from it's repo (on your local disk) into repo-plugins, instead of this complicated procedure.

To fix your pull request execute the following commands (origin is your repo, upstream is the xbmc repo)
```
git fetch upstream
git checkout leia
git reset --hard upstream/leia
mkdir plugin.video.dcmtv/
cp -r <path-to-plugin.video.dcmtv>/ plugin.video.dcmtv/
git add plugin.video.dcmtv/
git commit -m '[plugin.video.dcmtv] 1.0.0'
git push -f origin leia
```

**Pull request closed without merging**
