### PR TITLE
[plugin.video.fernsehkritik] 1.0.2

### PR DESCRIPTION
**Pull request by cdwertmann**
### Description
Update source URL
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by phil65** [comment]
you need to bump the version number.

**Comment by cdwertmann** [comment]
I only changed a URL in the addons.xml which isn't used by Kodi as far as I know. No change to the code was made, therefore I don't think a new version number is needed.

**Comment by phil65** [comment]
@MartijnKaijser opinion? Is this change even needed?

**Comment by cdwertmann** [comment]
I'm making this change because Martijn asked me to do so.

**Comment by phil65** [comment]
ok. @MartijnKaijser no version bump needed for this change?

**Comment by enen92** [comment]
I doubt a version bump is needed for the repo-script to generate a new xml file. I guess this change is only for displaying the link correctly on the addon-website. But I don't know either

**Comment by cdwertmann** [comment]
@enen92 you are right, that is exactly the purpose of this change

**Comment by MartijnKaijser** [comment]
The list is generated from the zip files which are only updated when there's a version bump

**Comment by enen92** [comment]
@cdwertmann please bump the addon version

**Comment by cdwertmann** [comment]
@enen92 done

**Pull request merged**
