### PR TITLE
[plugin.video.ipcams] v0.0.3

### PR DESCRIPTION
**Pull request by b-jesch**
### Description
This addon shows the streams of maximum three surveillance cameras of your own. For this, the URLs of the cams must be entered in the setup. If no stream URLs are entered, a corresponding notification message is issued.
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by Razzeee** [comment]
your `icon.png` has transparency at the top, please fix that :)

**Comment by b-jesch** [comment]
Indeed. Fixed.

**Comment by enen92** [comment]
If this is a new addition you need to target krypton instead of jarvis

**Comment by b-jesch** [comment]
The addon was developed under jarvis. Should I close the PR here and make a new pull request in krypton branch?

**Comment by Razzeee** [comment]
@b-jesch 
you can force push your changes against this branch and you should be able to retarget the correct base branch via editing the PR.

**Comment by b-jesch** [comment]
Sorry, I'm not as familar with git to do this. I'll close this PR and reopen a new one on krypton

**Pull request closed without merging**
