### PR TITLE
[plugin.video.arteplussept] 1.1.5

### PR DESCRIPTION
**Pull request by thomas-ernest**
### Description

Upgrade plugin.video.arteplussept from 1.1.1 to 1.1.5.
 - Organize main menu based on Arte TV API
 - Added search
 - Added live stream
 - AddedPolish translation

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by basrieter** [comment]
@known-as-bmf Are you aware of this PR?

**Comment by known-as-bmf** [comment]
> @known-as-bmf Are you aware of this PR?

Hey, thank you for the heads up

I've been inactive for a long time, please hold, I will get in touch with @thomas-ernest 👍

**Comment by known-as-bmf** [comment]
Hey @basrieter, thanks again for your message.

I just had a call with @thomas-ernest, and I would like to give him the authority to publish new versions of the plugin 🙂

Is there a procedure to follow or is this message enough to grant him this right? I added him as a contributor to the pligin's repository.

**Comment by basrieter** [comment]
> Hey @basrieter, thanks again for your message.
> 
> I just had a call with @thomas-ernest, and I would like to give him the authority to publish new versions of the plugin 🙂
> 
> Is there a procedure to follow or is this message enough to grant him this right? I added him as a contributor to the pligin's repository.

Great! I will do a quick review tomorrow and continue then.

**Comment by thomas-ernest** [comment]
Hello,
Thank you @known-as-bmf for your call and trust.
I will decline this PR, because I delivered new changes and fixes in a v1.1.6, which will require a new pull-request.

**Comment by thomas-ernest** [comment]
New PR open with id https://github.com/xbmc/repo-plugins/pull/4249

**Pull request closed without merging**
