### PR TITLE
[plugin.video.antennasicilia] 1.0

### PR DESCRIPTION
**Pull request by RosarioACali**
Added new plugin that allows live streaming from a local Italian television channel.

### CODE REVIEW

**Comment by learningit** [comment]
A PR should contain a single commit. I can't tell what you want in the PR.

**Comment by Razzeee** [comment]
And only the jarvis branch accepts new addon submissions.
https://github.com/xbmc/repo-plugins/tree/helix#status

**Comment by RosarioACali** [comment]
@learningit I want to add a new addon named antennasicilia.. Sorry this was the first time for me using github and I do not know how to master it yet

**Comment by RosarioACali** [comment]
@Razzeee so, should I move my pr to the Jarvis branch?

**Comment by phil65** [comment]
yup, jarvis branch and only one commit, please.

**Pull request closed without merging**
