### PR TITLE
[plugin.video.embycon] 1.9.3

### PR DESCRIPTION
**Pull request by faush01**
### Description
Apr release with some bug fixes and string lang fixes

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
@faush01 this add-on isn't Python 3 compatible. Future updates have to be compatible with Python 3.
Have a look at https://kodi.tv/article/attention-addon-developers-migration-python-3 for more information.

**Comment by faush01** [comment]
> 
> 
> @faush01 this add-on isn't Python 3 compatible. Future updates have to be compatible with Python 3.
> Have a look at https://kodi.tv/article/attention-addon-developers-migration-python-3 for more information.

So no more pull requests to the krypton branch unless Python 3 compatible?
I thought it would be just limited for new submission to the lia branch.

Based on history Kodi 19 is at least a year away, I am not sure blocking updates to Kodi 18 just because the addon does not support a future release is a good idea.

**Comment by faush01** [comment]
@Rechi 
How do I let users know the addon is no longer supported or updated in the official repo?
Can I do one more release with a message to let them know?

Something like pop up to let them know for future updated to check the forums etc?

**Comment by Rechi** [comment]
With future updates I didn't necessary mean the next updated. As long as there is no Kodi release with python3, it's okay to updated this add-on. Although Kodi 19 is still far away I recommend to look at the python3 compatibility soon.

>  I thought it would be just limited for new submission to the leia branch.

For now yes, but once there is a v19 you either have to make the version in the lower branches python 3 compatible too or submit a py3 compatible one to the v19 branch.

**Comment by faush01** [comment]
@Rechi 
Thanks for clarifying.
I don't want to support python2 and python3, I will make a hard switch from python 2 to python 3 when Kodi 19 Alpha is up.
At that point I will fully switch to Kodi 19 Python 3 support and the old python 2 version will no longer be updated.

**Pull request merged**
