### PR TITLE
[plugin.program.newgrounds] 1.0.5

### PR DESCRIPTION
**Pull request by erfg12**
### Add-on details:
- **General**
  - Add-on name: Newgrounds
  - Add-on ID: newgrounds
  - Version number: 1.0.5
  - Kodi/repository version: Leia
- **Code location**
  - URL: https://github.com/erfg12/kodi-repo/tree/master/plugin.program.newgrounds
  - Revision/tag: c7dee26a70606bea20d9d83efbb7b69db29f2385
  - Branch: Master
### Description of changes:
Changed cURL to JSON API

### CODE REVIEW

**Comment by erfg12** [comment]
Fixed localization of strings.
Fixed empty keyboard entry causing crash.
Removed debug code.

Sorry, I made a new PR because I didn't know how to merge the new fork I made into the old PR.

**Comment by enen92** [comment]
All those items in addon.xml assets should be filled. If you don't want to specifiy a banner, clearlogo, etc, remove the respective elements from the submission

**Comment by enen92** [comment]
@erfg12 new addons must be submitted to the Leia branch (see: https://kodi.wiki/view/Submitting_Add-ons)
Also your addon is not python3 compatible. Addons submitted from now on have to be compatible with python2.7 (because of leia) and python3 (because of matrix).

**Comment by erfg12** [comment]
Closing this one, making a new PR for Leia branch.

**Pull request closed without merging**
