### PR TITLE
[plugin.video.gamegurumania] 1.0.8

### PR DESCRIPTION
**Pull request by skipmodea1**
### Description
v1.0.8 (2022-04-22)
- using https instead of http
- ignoring ssl error
- leia branch (kodi 18)
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by skipmodea1** [comment]
@enen92 my PR failed because of this:
 ERROR: plugin.video.gamegurumania addon already exists with a higher or equal version: 1.0.8 in leia branch. Users in leia won't be able to receive the addon update.
ERROR: plugin.video.gamegurumania addon already exists with a higher or equal version: 1.0.8 in krypton branch. Users in krypton won't be able to receive the addon update.
ERROR: plugin.video.gamegurumania addon already exists with a higher or equal version: 1.0.8 in jarvis branch. Users in jarvis won't be able to receive the addon update.
ERROR: plugin.video.gamegurumania addon already exists with a higher or equal version: 1.0.8 in isengard branch. Users in isengard won't be able to receive the addon update.
ERROR: plugin.video.gamegurumania addon already exists with a higher or equal version: 1.0.8 in helix branch. Users in helix won't be able to receive the addon update.
ERROR: plugin.video.gamegurumania addon already exists with a higher or equal version: 1.0.8 in gotham branch. Users in gotham won't be able to receive the addon update.

I don't quite understand how to fix error. A version of 1.0.8 exists in Gotham but is marked broken. @enen92 can you advise how i can fix this? thanks!

**Comment by enen92** [comment]
The broken status doesnt really matter. If a user is on Gotham and has version 1.0.8 of your add-on installed (even if broken) and then install Leia, the add-on migration/update won't be taking place because Kodi will compare the version available for Leia (1.0.8) and compare it with the already installed one (1.0.8). Leia needs a higher version than Gotham, and matrix an higher version than leia. That's why some add-on use local version identifiers (1.0.8+matrix.1 > 1.0.8 according to how our version subsystem works)

**Comment by skipmodea1** [comment]
@enen92 
So if i understand all this correctly, to fix this i should do the following?!:
Make a PR for matrix 1.0.9+matrix.1 and after that is merged:
Make a PR for leia 1.0.9

**Comment by enen92** [comment]
Yeap, that's it

**Comment by enen92** [comment]
Don't need to wait for the merge to do both prs though, we'll make sure they go in in order and only after repo syncs

**Comment by skipmodea1** [comment]
@enen92 ok thanks for the help :)

**Pull request closed without merging**
