### PR TITLE
[plugin.video.funimationnow] 0.0.3

### PR DESCRIPTION
**Pull request by Protocol-X**

### CODE REVIEW

**Comment by learningit** [comment]
Please squash the commits and rename the resulting commit in the same format as the PR., i.e. plugin.video.blah x.y.z

Code looks good, you may want to consider using xbmc.waitForAbort() rather than the sleep calls in player.py, Also a bit confusing that a couple calls use control.sleep and others use xbmc.sleep - looks like they're the same.

**Comment by Protocol-X** [comment]
Thanks I will take a look.  I did run the commands to squash but it still
showed 2 commits.  I will try again and then get back to you.

**Comment by learningit** [comment]
Just noticed there is an existing funimation add-on in the kodi.org repo. Are you the original author there as well? It's fairly new, though marked broken, so waht to make sure that the original author is ok woth this. At any rate, you need to bump the version beyond 1.2.1

**Comment by learningit** [comment]
You need to do a force push to the branch to update the squash. Please see: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by Protocol-X** [comment]
I have already discussed this with another member.  Funimation and
funimationnow are different.  The names look simular so it can be
overlooked easily

**Comment by learningit** [comment]
Ok, see it now. I was confused because the icon just says "Funimation" without the "now".

**Comment by Protocol-X** [comment]
This is the method I used bit it didn't work.  I am at the office now so I
have no access to try again. I will update it later tonight when I get home
and let you know.  Appreciate the feedback

**Comment by Protocol-X** [comment]
I have ran through this 2 more times and even know there are no errors it always shows 2 commits

**Comment by Protocol-X** [comment]
Please see new request https://github.com/xbmc/repo-plugins/pull/665

**Pull request closed without merging**
