### PR TITLE
[plugin.video.livestream@helix] 2021.6.16

### PR DESCRIPTION
**Pull request by eracknaphobia**
### Add-on details:

- **General**
  - Add-on name: Livestream
  - Add-on ID: plugin.video.livestream
  - Version number: 2021.6.16
  - Kodi/repository version: helix

- **Code location**
  - URL: https://github.com/eracknaphobia/plugin.video.livestream
  
Livestream, formerly known as Mogulus, is a live streaming video platform that allows users to view and broadcast video content using a camera and a computer through the internet.

### Description of changes:

        - Matrix compatibility updates
        - Code clean up
    

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by eracknaphobia** [comment]
How are we supposed to handle this using kodi-addon-submitter to submit py2 & py3 versions when the older versions don't support strings.po language files?

`ERROR: Using the new language directory structure in /home/runner/work/repo-plugins/repo-plugins/plugin.video.livestream/resources/language/resource.language.en_gb for a Kodi version that does notsupport it. Please use the old language file struture or move the addon toan upper branch/kodi version.`

**Comment by enen92** [comment]
Honestly the patch in addon-submitter to allow py2/py3 is more a workaround to allow an easy port to matrix (while still storing the addon in the leia branch) than anything that should be considered long term. I think the way to go is to drop support for those outdated platforms (at least anything < Leia). Hopefully when Nexus is out we can enforce submissions only for python3 (matrix and above)

**Comment by enen92** [comment]
A possible approach is to use named branches like I do in https://github.com/XBMC-Addons/plugin.audio.radio_de

**Comment by eracknaphobia** [comment]
Good point. Support for the older branches could probably be dropped at this point. As always thanks for the info @enen92!

**Pull request closed without merging**
