### PR TITLE
[plugin.video.funimationnow] 0.0.4

### PR DESCRIPTION
**Pull request by Protocol-X**
This plugin version has been marked as broken due to the old api being shut down and the new one incapable of performing the same tasks.

Please merge this PR to disable the broken plugin.

PR https://github.com/xbmc/repo-scripts/pull/369 has been created which is a replacement for this plugin and needs to be merged into the scripts repo to make available to all users as a replacement. 

Any previous users should use the official Kodi repo to install the new one which is marked as version 0.1.0.

Any additional links, Info, and or support can be found using this forum location.
http://forum.kodi.tv/showthread.php?tid=304479

### Description
Old API is no longer in service

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Perhaps you can make the message big more clear telling them to install the new plugin.

**Comment by Protocol-X** [comment]
@MartijnKaijser. I apologize MartijnKaijser, but where would you like me to put this message?  If we mark this as broken they won't be able to install it correct?  Sorry for the questions but I have never marked an addon broken before.

**Comment by MartijnKaijser** [comment]
@Protocol-X the text you put between the <broken>

**Comment by Protocol-X** [comment]
Understood, thank you.

**Pull request closed without merging**
