### PR TITLE
[plugin.video.mediathek] 0.7.5

### PR DESCRIPTION
**Pull request by raptor2101**
### Description
ZDF Completly changes its WebInterface so the plugin is rewriten to adopt that (now using JSON API, hopefully more stable)
Important: ZDF enforces TLSv1 with SNI enabled. Support for this is added in Pyhton 2.7.9. (See here https://github.com/raptor2101/Mediathek/issues/85). I'am unsure how to handle that via Kodi dependency. On Linux based platforms, this should be no problem, even with old Kodi version, on Windows this enforces Kodi 17.
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### Additional information :
I'am aware that the code provided by this PullRequest pusches 129 CodeIssues (regarding to codacy). I  was unaware of that until now and will solve these issues with the next PR.

### CODE REVIEW

**Comment by phil65** [comment]
If python 2.7 is the requirement it might be best to put this addon into our krypton repo and deprecate all previous ones.

**Comment by raptor2101** [comment]
1) How do i mark my plugin as depricated?
2) How to go on? Will this PR be pulled or do I have to resubmit a new one

Current state of the Plugin deployed by the official repository is broken, with this PR most user should "get it working" again.

**Comment by Razzeee** [comment]
1) See: http://kodi.wiki/view/Addon.xml#.3Cbroken.3E
This will cause all users to get a message saying the plugin is broken and should be disabled.
2) If you're targeting python 2.7.9 the user needs to run at least Krypton v18. Due to https://github.com/xbmc/xbmc/pull/8207 and https://github.com/xbmc/xbmc/pull/8491, every release befor that is on a lower version of python.
So you would have to do another PR targeting the Krypton branch of this repo.

**Comment by phil65** [comment]
>> Krypton v18

I think you mean Krypton v17 :)

**Comment by Razzeee** [comment]
Yes, sorry :)

**Comment by raptor2101** [comment]
So then reject this PR. I will create two PRs one for Krypton and one for all other (depcrated)

**Pull request closed without merging**
