### PR TITLE
[plugin.audio.criminalpodcast-kodi18] 1.1.3

### PR DESCRIPTION
**Pull request by leopheard**
### Description
- Add-on ID: plugin.audio.criminalpodcast-kodi18
 - Version number: 1.1.3
 - Kodi/repository version: 18
 - Code location URL: http://www.github.com/leopheard/criminalpodcast-kodi18
 - Revision/tag: 
 - Branch:
 Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by leopheard** [comment]
Errors fixed, not sure how to re-run the check?

**Comment by leopheard** [comment]
Okay, I have accidentally re-commited another audio addon (TheInterceptPodcasts) into this one, how do I undo this?

**Comment by leopheard** [comment]
FFS why are all my pull requests getting mixed up? 

Here's my last commands:

git remote add plugin.audio.democracynowaudio git@github.com:leopheard/democracynowaudio.git

git fetch plugin.audio.democracynowaudio

git checkout -b plugin.audio.democracynowaudio plugin.audio.democracynowaudio/master

git checkout gotham

git read-tree --prexfix=plugin.audio.democracynowaudio/ -u plugin.audio.democracynowaudio

git commit -m "[plugin.audio.democracynowaudio] 1.0.0"

git push origin gotham

**Comment by leopheard** [comment]
@enen92 Looks like the checks passed, not sure what to do now?

**Comment by enen92** [comment]
Add-on needs to be reviewed and you should adapt the changes requested. Furthermore you need to squash the commits into a single one. Plus the add-on needs to be compatible with both py2 and py3. 
Also yOu need to target the Leia branch and not gotham. We do not accept new addons into any other branch except Leia

**Comment by Razzeee** [comment]
I will close this for now. @leopheard if you end up doing the needed work, please feel free to open up a new PR targeting at least the leia branch.

Thank you!

**Pull request closed without merging**
