### PR TITLE
[plugin.video.esa] v1.1.1

### PR DESCRIPTION
**Pull request by jamontes**
Hi,

This is a new maintenance update for the ESA video add-on.

Changelog: 1.1.1 (2018.12.02)
- Quick fix to play newer videos (thanks to idleloop-github).

Many thanks in advance and best regards,

jamontes.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
Can you please migrate your strings.xml to the gettext format (strings.po)? See: https://kodi.wiki/view/Language_support

**Comment by jamontes** [comment]
Hi enen92,

Yes, I can change the files if required, but I always thought that the xml files were still allowed into Gotham.

I'll get you back with the changes, no problem.

**Comment by enen92** [comment]
please keep the language folder layout as it is now. IIRC the new language folder layout is only compatible to Isengard and onwards

**Comment by jamontes** [comment]
Hi enen92,

I did all the changes following your indications. I hope that everything s OK now.

Thanks a lot for your help and effort.

Best regards,

jamontes.

**Pull request merged**
