### PR TITLE
[plugin.video.iplayerwww] 3.0.7

### PR DESCRIPTION
**Pull request by CaptainTK**
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Did you take in account that inpustream is disabled by default and tested if it actually works like you intended?

**Comment by CaptainTK** [comment]
Yes, I did. Switched DASH on, tried Live with and without Autoplay as well as Catchup with and without Autoplay. In between I switched DASH back on and it fell back to HLS as expected. I tested with 17.1 on Linux and simply disabled InputStream Adaptive for the tests.

**Comment by MartijnKaijser** [comment]
No i mean if auto enables the inpustream addon cause that's what the dependency did. Now you rely on users to enable it theirselves

**Comment by CaptainTK** [comment]
Ah, sorry, didn't get that before.

No, this code does not automatically enable inputstream. It simply avoids errors if it is not available. Users now need to activate inputstream and then switch stream protocol to DASH, otherwise it will stick to HLS.

The dependency worked the same way, users had to enable inputstream, otherwise the add-on failed to install. If this was supposed to work automatically as you indicate, then this automatic procedure is broken. It always seemed to me that inputsream, being a binary add-on, was not installed the same way as non-binary add-ons like requests.

HLS is the default stream protocol (again) now. Apart from the issues with inputstream, this is also because there are some programmes that are not available as DASH streams and currently they simply won't play. I tried implementing an automatic fallback, but failed before. Will need to revisit this.

Frankly speaking, I am a little tired by the amount of issues inputstream caused. I was very enthusiastic when Krypton brought support for DASH, but the whole concept how inputstream is invoked seems flawed to me.

Also, I would like to switch to a different mediaselector, but this is blocked by a bug in inputstream. I opened an issue for it, but nothing happened so far.

**Comment by MartijnKaijser** [comment]
Inputstream is still in very early stage so no need to shoot it down

**Pull request merged**
