### PR TITLE
[plugin.video.fosdem] 0.0.8

### PR DESCRIPTION
**Pull request by jelly**
### Description

This PR unbreaks the current broken Fosdem addon in the repo, the last time I forgot to include some files which broke the update. Sorry for the current broken situation in the repository :(

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
@jelly check the failures in addon-checker you need to update higher branches first (with a higher version than this one)

**Comment by basrieter** [comment]
@jelly Can you also provide a Matrix/Nexus version? Otherwise this can't merge.

**Comment by jelly** [comment]
> @jelly check the failures in addon-checker you need to update higher branches first (with a higher version than this one)

I'm a bit confused about what the update procedure is. I thought I should target the lowest cmpatible addon? Or should I start out with the highest addon?

I am slowly losing my mind why this is version 0.0.8, as alas my own [git repo](https://github.com/jelly/plugin.video.fosdem) is 0.0.7

**Comment by jelly** [comment]
Ok, so I opened a PR for matrix here https://github.com/xbmc/repo-plugins/pull/3941 as the nexus repository looks empty still? I hope I'm doing it right, if not sorry for the inconvenience.

I'll fixup this PR to 0.0.7 so if the matrix PR is ok, as the version 0.0.8 here looks wrong.

**Review by basrieter — APPROVED** [review]

**Pull request merged**
