### PR TITLE
[plugin.video.i24News] 1.0.5 mark as broken

### PR DESCRIPTION
**Pull request by learningit**
Mark the addon as broken.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
could you change the commit message as well?  Fee free to do several plugins in one PR if that's easier

**Comment by learningit** [comment]
do you mean add "mark as broken" to the end of the commit name?

**Comment by MartijnKaijser** [comment]
"[plugin.video.i24News] 1.0.5 mark as broken"  or something. Has more meaning than "update addon.xml"

**Comment by learningit** [comment]
I'm being lazy and using the git editor to create the change for broken. I don't seem to be able to go back and change the previous commit messages, but I'll try to set them going forward.

**Comment by learningit** [comment]
Martijn, as you know git well, is the only way to change the commit message by doing an interactive rebase and using the reword cmd? I can't find any other way to go back and change the commit message.

**Pull request merged**
