### PR TITLE
[plugin.service.gto] v2.0.23

### PR DESCRIPTION
**Pull request by b-jesch**
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Update continued from Jarvis branch

- 2.0.23
minor fixes
- 2.0.22
some skin modifications
sports scraper added
- 2.0.18
add record capabilities (only Krypton)

- 2.0.14
Some more properties, e.g. search titles in local database and flag the results

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by learningit** [comment]
Hmm, sorry to inconvenience you again. I missed this first time around:
<extension point="xbmc.python.script" library="default.py" />
<extension point="xbmc.service" library="starter.py" start="startup">

Your add-on should be a script, not a plugin. Please rename the addon script.service.gto and then submit to the xbmc/repo-scripts repository. I don't know how this was missed when you previously submitted this and it was accepted into the kodi.org repo. I'm going to close this PR against the xbmc/repo-plugins as it's not the correct repo.

**Comment by b-jesch** [comment]
The default.py uses function calls from xbmcplugin module and needs a plugin handle to collect and fill in the dynamic list content of the widgets (e.g. gto-widget.xml). These methods are not available outside the xbmcplugin module (Line 432, Line 436). The XMLs itself calls the plugin.service.gto as plugin source (see https://github.com/xbmc/repo-plugins/pull/1426/commits/7392ea23faf8e8fcb353a1d725f25429663e2dde#diff-c36ccdfca8685c6b90a1160267a423fa Line 38)

**Comment by learningit** [comment]
I'm still digesting this and discussing with others, haven't forgotten about it.

**Comment by learningit** [comment]
The long and the short of this is you can't extend xbmc.python.script and then put it into the plugin repo. You probably need to break this into both a script and a plugin if you want to take this approach.

**Pull request closed without merging**
