### PR TITLE
[plugin.video.lbry] 0.1.8+matrix.1

### PR DESCRIPTION
**Pull request by amacchietto**
### Description
Fixes a thrown exception when a search result contain a channel name (introduced in v0.1.7 due a testing oversight).

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Review by enen92 — APPROVED** [review]

**Comment by accumulator** [comment]
ehm.. [add-on rules](http://kodi.wiki/view/Add-on_rules) states: You acknowledge that you are the maintainer of your add-on

This is not the case

WTF

**Comment by enen92** [comment]
my fault @accumulator, I didn't notice that on the phone. Do you want me to revert the update?

**Comment by accumulator** [comment]
actually, yes. This latest version of the plugin seems to work, but I can't vouch for all the changes made, and my name is attached to it as maintainer.

It's also on the leia branch

**Comment by accumulator** [comment]
same for prev version : https://github.com/xbmc/repo-plugins/pull/3850

**Comment by enen92** [comment]
@accumulator for users that received the new version to revert to the previous one I'll need to bump the addon version to 0.1.9. Can you adapt the version from your upstream repository so that they are in sync?

**Comment by accumulator** [comment]
Will do

**Comment by enen92** [comment]
Addressed in https://github.com/xbmc/repo-plugins/pull/3884 and https://github.com/xbmc/repo-plugins/pull/3885 (the last one doesn't seem to be necessary)

**Comment by amacchietto** [comment]
Im going to point out that this plugin was left in a practically unusable state for 3 months whereby users doing a new install could not add channels basically making the plugin effectively worthless. There should be a system in place for dealing with this issue.

[The original v0.1.8 pull request made this issue known so please don't pretend I just walked in here and pretended to be the primary author](https://github.com/xbmc/repo-plugins/pull/3850)

I even left a comment in the Kodi forum asking what the procedure is for seemingly derelict addons to no response.

**Comment by accumulator** [comment]
@amacchietto please calm down. Again, I value your contributions, but this is not the way to go about it.

The plugin was perfectly usable, just the comments feature required a bit older version of lbrynet to work, so saying it was unusable is a bit disingenuous.

You never created a ticket for comment API deprecation (in fact, no-one did) and you added all commits for the new comment API to an unrelated PR (about the addon profile directory presumably not being created, which I couldn't immediately reproduce). On top of that the PR is full of cross-merges which makes review a lot more time consuming and unnecessarily pollutes the history.

If you keep your PR's clean (no cross-merge galore) and targeted (one feature per PR, one PR per branch), I'm sure getting your changes merged (&published) will go much faster.

**Pull request merged**
