### PR TITLE
[plugin.video.pluralsight] v1.1.4 (broken)

### PR DESCRIPTION
**Pull request by mintsoft**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

This addon is completely broken and basically requires a total rewrite to fix

### CODE REVIEW

**Comment by Rechi** [comment]
Before removing the add-on from the repo, it has to be marked broken for some time (see https://kodi.wiki/view/Addon.xml#.3Cbroken.3E). Only that way it gets disabled on all Kodi clients having installed you add-on.

**Comment by Rechi** [comment]
> Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

@mintsoft please squash your commits.

**Comment by mintsoft** [comment]
@Rechi apologies for the noise, all squashed now

**Comment by mintsoft** [comment]
Much appreciated @Rechi !

**Pull request merged**
