### PR TITLE
[plugin.video.ampya] Obsolated, They stoped their Musik Service

### PR DESCRIPTION
**Pull request by tyl0re**
### Description
I dont know how to make an Remove Request, since the Page from the Plugin stoped offering any service

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
We should add the broken tag in the addon.xml with a version bump and remove it some months later

**Comment by enen92** [comment]
ping @tyl0re

**Comment by tyl0re** [comment]
Its o.k for me, should i make an PR with the Broken tag in the addon?

**Comment by enen92** [comment]
Yes please do, and also bump the addon version. This one has to wait a bit before being merged

**Comment by MartijnKaijser** [comment]
i can do as well.

**Comment by MartijnKaijser** [comment]
https://github.com/xbmc/repo-plugins/commit/0020c84db2dd0133c49995eb3a32a224695e9f5d

**Comment by MartijnKaijser** [comment]
i'll close this as we semi automatically clean up once in a while and then it's gone.
thx

**Pull request closed without merging**
