### PR TITLE
[plugin.video.gamekings] 1.2.19

### PR DESCRIPTION
**Pull request by skipmodea1**
### Description
v1.2.19 (2020-11-10)
- fixed premium videos after a website change
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by skipmodea1** [comment]
This is not the matrix version of the plugin, i am planning on updating that one after this one. Why am i getting an matrix error for this leia addon? And how can i fix that?

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
@skipmodea1 update model should follow the opposite direction - first matrix then leia. Matrix must always have a higher version at any time the repo sync, so that users on leia are able to migrate to matrix and receive the update

**Comment by skipmodea1** [comment]
Right, i will make a PR for the matrix version first then. Thanks!

**Comment by skipmodea1** [comment]
Closing it. Gonna make another PR for this after the PR for matrix has gone through.

**Pull request closed without merging**
