### PR TITLE
Update youtube addon: api keys + Krypton support

### PR DESCRIPTION
**Pull request by un1versal**
Im only doing this PR as a special favor to Kolifanes

see http://forum.kodi.tv/showthread.php?tid=200735&pid=2257011#pid2257011

changes from  Kolifanes own API changes plus

http://offshoregit.com/finalmakerr/Fixed%20Addons/plugin.video.youtube-5.1.17.zip
https://github.com/rasberryrabbit/plugin.video.youtube

Im not assuming any responsibility or know anything about python development just passing changes forward for the benefit of the larger community.

@zag was in IRC he read the convo.

IF Im honest this PR should be done by @rasberryrabbit and whoever is maintain the pllugin but there you have it, maybe I picked the wrong person to help.

### CODE REVIEW

**Comment by Kolifanes** [comment]
I registered on GitHub. I have upload here the release 5.1.20 with the YT APIs fixed based on the latest release of bromix (5.1.16)
https://github.com/Kolifanes/plugin.video.youtube

**Comment by un1versal** [comment]
@Kolifanes the **right way** is to fork this repo -> https://github.com/xbmc/repo-plugins/fork make your changes and submit those change via a PR like what I done here with your collection.

Even though this is gpl v2 code and you can grab ANY published code and submit it, its alway nice to let the authors know (because they may have interest in providing those fixes back to min repo as it was done here.

any other way of fixing the addon is inefficient and confusing to everyone.

**Comment by Kolifanes** [comment]
Hope i have do everything correct.
https://github.com/xbmc/repo-plugins/pull/368

Thanks for your support un1versal.

**Comment by tamland** [comment]
Please don't send fixes here. This is not a development repo. Decide on a new upstream, *then* send a pr as described in http://kodi.wiki/view/Submitting_Add-ons#Github

**Comment by un1versal** [comment]
then close this.

**Comment by Kolifanes** [comment]
@tamland I'm not becoming the new maintainer. This is only a fix for APIs.

**Comment by tamland** [comment]
@un1versal you are overreacting and completely missing the point. There are now two open conflicting prs. Please discuss this beforehand and don't bring the chaos here spamming everyone. Then, open a pr that follows the guidelines **that I can actually merge**.

**Pull request closed without merging**
