### PR TITLE
[plugin.video.dailymotion_com] 2.4.3

### PR DESCRIPTION
**Pull request by Gujal00**
### Description
bugfixes
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

### CODE REVIEW

**Comment by Gujal00** [comment]
@enen92 Please merge this too as it is identical to #3773 but for older kodi versions. Thanks

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
@Gujal00 it won't work, the version in matrix has to be higher than this one, not the same. You'll have to bump matrix again.

**Comment by Gujal00** [comment]
@enen92 Sorry looks like i made a mistake.
The matrix addon.xml supposed to have
`<addon id="plugin.video.dailymotion_com" name="DailyMotion.com" version="2.4.3+matrix.1" provider-name="gujal">`
but it has `<addon id="plugin.video.dailymotion_com" name="DailyMotion.com" version="2.4.3" provider-name="gujal">`
Can I do a PR for the matrix version again to up its version so that this PR can be merged. Thanks

**Comment by Gujal00** [comment]
@enen92 Thanks for approving the second PR for the matrix branch. This one is now passing checks. Please merge when possible. Thanks

**Pull request merged**
