### PR TITLE
[plugin.googledrive] 1.2.2

### PR DESCRIPTION
**Pull request by cguZZman**
### Description
- Team Drive support added
- Bug fixes

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by romanvm** [comment]
@enen92 approved this a while ago and it lgtm. Should I merge it or there are some show-stoppers that I'm not aware of?

**Comment by cguZZman** [comment]
pumped to version 1.0.3

**Comment by Lunatixz** [comment]
Waiting for update and https://github.com/xbmc/repo-scripts/pull/691

**Comment by Lunatixz** [comment]
@cguZZman Thanks for updating the code frequently, however in order to review and merge your PR we need to lock in a version for submission. Once this version is merged you can submit updates; Please hold off on updating your PRs till we review/merge the code. THX

**Comment by cguZZman** [comment]
No problem. I'll wait for this PR to be merged before more updates.

**Pull request merged**
