### PR TITLE
[plugin.video.nbcsnliveextra@isengard] 2020.11.6

### PR DESCRIPTION
**Pull request by eracknaphobia**
### Add-on details:

- **General**
  - Add-on name: NBC Sports Live Extra
  - Add-on ID: plugin.video.nbcsnliveextra
  - Version number: 2020.11.6
  - Kodi/repository version: isengard

- **Code location**
  - URL: https://github.com/eracknaphobia/plugin.video.nbcsnliveextra
  
NBC Sports Live Extra is a service that allows you to watch NBC Sports coverage of live events from NBC and NBCSports Network

### Description of changes:

        - Updates for python 3 compatibility
    

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
ERROR: Required dependency script.module.adobepass is not available in current repository

**Comment by enen92** [comment]
It'd be nice if you could take a quick look at the Travis warnings

**Comment by enen92** [comment]
@eracknaphobia I think you submitted this to the wrong branch. Shouldn't it be krypton instead?

**Comment by eracknaphobia** [comment]
I targeted this branch because the language file has been updated.

https://github.com/xbmc/repo-plugins/pull/3216#issuecomment-739481513

**Pull request closed without merging**
