### PR TITLE
[plugin.video.bfi] 1.0.3

### PR DESCRIPTION
**Pull request by FraserChapman**
### Description
Just updated the plugin to reflect changes on the BFI website (to fix broken images)

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by FraserChapman** [comment]
Oops - have  multiple plugins to update and forgot github sends all commits to the same PR!

**Comment by Rechi** [comment]
@FraserChapman this add-on isn't Python 3 compatible. Future updates have to be compatible with Python 3.
Have a look at https://kodi.tv/article/attention-addon-developers-migration-python-3 for more information.

**Comment by FraserChapman** [comment]
@Rechi - Thanks again! ...and again just wondering what the Python 3 incompatibility is here too :)

**Comment by Rechi** [comment]
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
   Error Type: <class 'TypeError'>
   Error Contents: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
   Traceback (most recent call last):
     File "<...>\plugin.video.bfi\main.py", line 3, in <module>
       from resources.lib import plugin
     File "<...>\plugin.video.bfi\resources\lib\plugin.py", line 13, in <module>
       from resources.lib import search as bfis
     File "<...>\plugin.video.bfi\resources\lib\search.py", line 11, in <module>
       from .cache import Cache, datetime_to_httpdate
     File "<...>\plugin.video.bfi\resources\lib\cache.py", line 19, in <module>
       kodilogging.config()
     File "<...>\plugin.video.bfi\resources\lib\kodilogging.py", line 42, in config
       logger.addHandler(KodiLogHandler())
     File "<...>\plugin.video.bfi\resources\lib\kodilogging.py", line 16, in __init__
       prefix = b"[%s] " % addon_id
   TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
   -->End of Python script error report<--
```

**Comment by FraserChapman** [comment]
@Rechi  Many thanks, will take a look and make changes for compatibility :)

**Pull request merged**
